// ============================================================================
// AUTO-GENERATED from language-truth/ui_props.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_props.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_props.py
//
// To modify: edit language-truth/ui_props.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_props.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأسماء مفاتيح خصائص عناصر الواجهة (IR keys).
//   يستهلكه ثلاثةُ منتِجين/مستهلِكين كي لا تنحرف المفاتيح بينهم انحرافًا صامتًا:
//     1. مصنع العناصر في المفسّر (widget_builtins.cpp) — يَكتب المفتاح.
//     2. مُرسِّم سطح المكتب (backends/desktop/renderer*.cpp) — يقرؤه.
//     3. مُصرِّفات الويب/أندرويد/iOS/macOS — تقرؤه.
//   القاعدة: ممنوع سلاسلُ مفاتيحَ حرفيّةٌ مباشرةٌ في أيٍّ من هؤلاء؛ استعمل هذه
//   الثوابت حصرًا (قاعدة المشروع «لا literals منطقيّة مباشرة»).
//
// (EN) Single source of truth for UI IR property-key names, shared by the
//   interpreter widget factory, the desktop renderer, and every codegen backend
//   so the keys can never silently diverge.
// ============================================================================

#pragma once

namespace sad
{
    namespace ui
    {
        namespace props
        {
            // (AR) نصّ العنوان الظاهر للزرّ والشريط والحوار والتبويب — «عنوان».
            inline constexpr const char *TITLE = "\xd8\xb9\xd9\x86\xd9\x88\xd8\xa7\xd9\x86";
            // (AR) محتوى النصّ لعنصر نص_عنصر ونظائره — «محتوى».
            inline constexpr const char *CONTENT = "\xd9\x85\xd8\xad\xd8\xaa\xd9\x88\xd9\x89";
            // (AR) نصّ عامّ (اسم بديل شائع للمحتوى، ونصّ التلميح) — «نص».
            inline constexpr const char *TEXT = "\xd9\x86\xd8\xb5";
            // (AR) رمز/أيقونة الزرّ العائم وزرّ الأيقونة (يقبل رمزًا نصّيًّا) — «أيقونة».
            inline constexpr const char *ICON = "\xd8\xa3\xd9\x8a\xd9\x82\xd9\x88\xd9\x86\xd8\xa9";
            // (AR) مصدر الصورة (مسار أو رابط) — «مصدر».
            inline constexpr const char *SOURCE = "\xd9\x85\xd8\xb5\xd8\xaf\xd8\xb1";
            // (AR) اسم الأيقونة المتجهة (مفتاح عنصر «أيقونة» — لا يخلط بمفتاح ICON) — «اسم».
            inline constexpr const char *NAME = "\xd8\xa7\xd8\xb3\xd9\x85";
            // (AR) نصّ التلميح الافتراضيّ لحقل الإدخال ومنطقة النصّ — «تلميح».
            inline constexpr const char *HINT = "\xd8\xaa\xd9\x84\xd9\x85\xd9\x8a\xd8\xad";
            // (AR) القيمة الحاليّة (عدديّة للمنزلق/شريط التقدّم، منطقيّة للمفتاح/خانة الاختيار) — «قيمة».
            inline constexpr const char *VALUE = "\xd9\x82\xd9\x8a\xd9\x85\xd8\xa9";
            // (AR) نصّ الرسالة لشريط الإشعار — «رسالة».
            inline constexpr const char *MESSAGE = "\xd8\xb1\xd8\xb3\xd8\xa7\xd9\x84\xd8\xa9";
            // (AR) العرض الثابت (بالبكسل) لصندوق المقاس — «عرض».
            inline constexpr const char *WIDTH = "\xd8\xb9\xd8\xb1\xd8\xb6";
            // (AR) الارتفاع الثابت (بالبكسل) لصندوق المقاس — «ارتفاع».
            inline constexpr const char *HEIGHT = "\xd8\xa7\xd8\xb1\xd8\xaa\xd9\x81\xd8\xa7\xd8\xb9";
            // (AR) الحشو الداخليّ للحاوية (بالبكسل) — إزاحة الأبناء داخل حدود العنصر — «حشوة».
            inline constexpr const char *PADDING = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9";
            // (AR) بديل احتياطيّ لاتينيّ (مسار UINode) — يقرؤه المُرسِّم فقط — «text».
            inline constexpr const char *TEXT_LATIN = "text";
        } // namespace props
    } // namespace ui
} // namespace sad
