// ============================================================================
// AUTO-GENERATED from language-truth/ui_props.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_props.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_props.py
//
// To modify: edit language-truth/ui_props.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_props.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأسماء مفاتيح خصائص عناصر الواجهة (IR keys).
//   يستهلكه ثلاثةُ منتِجين/مستهلِكين كي لا تنحرف المفاتيح بينهم انحرافًا صامتًا:
//     1. مصنع العناصر في المفسّر (widget_builtins.cpp) — يَكتب المفتاح.
//     2. مُرسِّم سطح المكتب (backends/desktop/renderer*.cpp) — يقرؤه.
//     3. مُصرِّفات الويب/أندرويد/iOS/macOS — تقرؤه.
//   القاعدة: ممنوع سلاسلُ مفاتيحَ حرفيّةٌ مباشرةٌ في أيٍّ من هؤلاء؛ استعمل هذه
//   الثوابت حصرًا (قاعدة المشروع «لا literals منطقيّة مباشرة»).
//
// (EN) Single source of truth for UI IR property-key names, shared by the
//   interpreter widget factory, the desktop renderer, and every codegen backend
//   so the keys can never silently diverge.
// ============================================================================

#pragma once

namespace sad
{
    namespace ui
    {
        namespace props
        {
            // (AR) نصّ العنوان الظاهر للزرّ والشريط والحوار والتبويب — «عنوان».
            inline constexpr const char *TITLE = "\xd8\xb9\xd9\x86\xd9\x88\xd8\xa7\xd9\x86";
            // (AR) محتوى النصّ لعنصر نص_عنصر ونظائره — «محتوى».
            inline constexpr const char *CONTENT = "\xd9\x85\xd8\xad\xd8\xaa\xd9\x88\xd9\x89";
            // (AR) نصّ عامّ (اسم بديل شائع للمحتوى، ونصّ التلميح) — «نص».
            inline constexpr const char *TEXT = "\xd9\x86\xd8\xb5";
            // (AR) رمز/أيقونة الزرّ العائم وزرّ الأيقونة (يقبل رمزًا نصّيًّا) — «أيقونة».
            inline constexpr const char *ICON = "\xd8\xa3\xd9\x8a\xd9\x82\xd9\x88\xd9\x86\xd8\xa9";
            // (AR) مصدر الصورة (مسار أو رابط) — «مصدر».
            inline constexpr const char *SOURCE = "\xd9\x85\xd8\xb5\xd8\xaf\xd8\xb1";
            // (AR) اسم الأيقونة المتجهة (مفتاح عنصر «أيقونة» — لا يخلط بمفتاح ICON) — «اسم».
            inline constexpr const char *NAME = "\xd8\xa7\xd8\xb3\xd9\x85";
            // (AR) نصّ التلميح الافتراضيّ لحقل الإدخال ومنطقة النصّ — «تلميح».
            inline constexpr const char *HINT = "\xd8\xaa\xd9\x84\xd9\x85\xd9\x8a\xd8\xad";
            // (AR) القيمة الحاليّة (عدديّة للمنزلق/شريط التقدّم، منطقيّة للمفتاح/خانة الاختيار) — «قيمة».
            inline constexpr const char *VALUE = "\xd9\x82\xd9\x8a\xd9\x85\xd8\xa9";
            // (AR) نصّ الرسالة لشريط الإشعار — «رسالة».
            inline constexpr const char *MESSAGE = "\xd8\xb1\xd8\xb3\xd8\xa7\xd9\x84\xd8\xa9";
            // (AR) العرض الثابت (بالبكسل) لصندوق المقاس — «عرض».
            inline constexpr const char *WIDTH = "\xd8\xb9\xd8\xb1\xd8\xb6";
            // (AR) الارتفاع الثابت (بالبكسل) لصندوق المقاس — «ارتفاع».
            inline constexpr const char *HEIGHT = "\xd8\xa7\xd8\xb1\xd8\xaa\xd9\x81\xd8\xa7\xd8\xb9";
            // (AR) المحاذاة. للنصّ: «يمين»/«وسط» (أو right/center) — وإلّا يُحاذى النصّ العربيّ يمينًا تلقائيًّا. لحاويات العمود/الصفّ (المحور المتقاطع): «بداية» (افتراضيّ، اتّجاهيّ: العمود RTL يمينًا واللاتينيّ يسارًا، الصفّ أعلى) · «وسط» · «نهاية» (العمود يسار المحتوى في RTL، الصفّ أسفل) · «تمدّد» (يملأ المحور المتقاطع؛ يتخطّاه الابن ذو المقاس الصريح في ذلك المحور). — «محاذاة».
            inline constexpr const char *ALIGN = "\xd9\x85\xd8\xad\xd8\xa7\xd8\xb0\xd8\xa7\xd8\xa9";
            // (AR) الحشو الداخليّ للحاوية (بالبكسل) — إزاحة الأبناء داخل حدود العنصر — «حشوة».
            inline constexpr const char *PADDING = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9";
            // (AR) الحشو العلويّ للحاوية (بالبكسل) — منطقيّ عموديّ ثابت — «حشوة_أعلى».
            inline constexpr const char *PADDING_TOP = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9_\xd8\xa3\xd8\xb9\xd9\x84\xd9\x89";
            // (AR) الحشو السفليّ للحاوية (بالبكسل) — منطقيّ عموديّ ثابت — «حشوة_أسفل».
            inline constexpr const char *PADDING_BOTTOM = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9_\xd8\xa3\xd8\xb3\xd9\x81\xd9\x84";
            // (AR) حشو جهة البداية (بالبكسل) — منطقيّ واعٍ بالـRTL (start=يمين) — «حشوة_بداية».
            inline constexpr const char *PADDING_START = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9_\xd8\xa8\xd8\xaf\xd8\xa7\xd9\x8a\xd8\xa9";
            // (AR) حشو جهة النهاية (بالبكسل) — منطقيّ واعٍ بالـRTL (end=يسار) — «حشوة_نهاية».
            inline constexpr const char *PADDING_END = "\xd8\xad\xd8\xb4\xd9\x88\xd8\xa9_\xd9\x86\xd9\x87\xd8\xa7\xd9\x8a\xd8\xa9";
            // (AR) الهامش الخارجيّ (بالبكسل) — يُقحِم منطقة محتوى الحاوية — «هامش».
            inline constexpr const char *MARGIN = "\xd9\x87\xd8\xa7\xd9\x85\xd8\xb4";
            // (AR) التباعد (بالبكسل) بين أبناء العمود/الصفّ المتتالين — «تباعد».
            inline constexpr const char *SPACING = "\xd8\xaa\xd8\xa8\xd8\xa7\xd8\xb9\xd8\xaf";
            // (AR) وزن المرونة (flex) — حصّة الابن من المساحة المتبقّية على المحور الرئيسيّ — «وزن».
            inline constexpr const char *WEIGHT = "\xd9\x88\xd8\xb2\xd9\x86";
            // (AR) عدد أعمدة الشبكة (Grid) — «أعمدة».
            inline constexpr const char *COLUMNS = "\xd8\xa3\xd8\xb9\xd9\x85\xd8\xaf\xd8\xa9";
            // (AR) حجم خطّ النصّ (بالبكسل) — يؤثّر على قياس النصّ عرضًا وارتفاعًا — «حجم_خط».
            inline constexpr const char *FONT_SIZE = "\xd8\xad\xd8\xac\xd9\x85_\xd8\xae\xd8\xb7";
            // (AR) هجاء بديل لـ«حجم_خط» (بأل التعريف) — مقبول في القياس — «حجم_الخط».
            inline constexpr const char *FONT_SIZE_ALT = "\xd8\xad\xd8\xac\xd9\x85_\xd8\xa7\xd9\x84\xd8\xae\xd8\xb7";
            // (AR) اسم مختصر لحجم الخطّ (بديل لـ«حجم_خط») — «حجم».
            inline constexpr const char *SIZE = "\xd8\xad\xd8\xac\xd9\x85";
            // (AR) بديل لاتينيّ لـ«وزن» (flex) — يقرؤه التخطيط فقط — «flex».
            inline constexpr const char *FLEX_LATIN = "flex";
            // (AR) بديل لاتينيّ لـ«أعمدة» — يقرؤه التخطيط فقط — «columns».
            inline constexpr const char *COLUMNS_LATIN = "columns";
            // (AR) بديل لاتينيّ لـ«عرض» — يقرؤه التخطيط فقط — «width».
            inline constexpr const char *WIDTH_LATIN = "width";
            // (AR) بديل لاتينيّ لـ«ارتفاع» — يقرؤه التخطيط فقط — «height».
            inline constexpr const char *HEIGHT_LATIN = "height";
            // (AR) اللون العامّ للعنصر (سلسلة سداسيّة #RRGGBB أو اسم لون) — «لون».
            inline constexpr const char *COLOR = "\xd9\x84\xd9\x88\xd9\x86";
            // (AR) لون النصّ — «لون_النص».
            inline constexpr const char *TEXT_COLOR = "\xd9\x84\xd9\x88\xd9\x86_\xd8\xa7\xd9\x84\xd9\x86\xd8\xb5";
            // (AR) هجاء بديل لـ«لون_النص» (بلا أل) — «لون_نص».
            inline constexpr const char *TEXT_COLOR_ALT = "\xd9\x84\xd9\x88\xd9\x86_\xd9\x86\xd8\xb5";
            // (AR) لون الخلفية (مفتاح مختصر) — «خلفية».
            inline constexpr const char *BG = "\xd8\xae\xd9\x84\xd9\x81\xd9\x8a\xd8\xa9";
            // (AR) لون خلفية العنصر (المعدّل الرسميّ) — «لون_خلفية».
            inline constexpr const char *BG_COLOR = "\xd9\x84\xd9\x88\xd9\x86_\xd8\xae\xd9\x84\xd9\x81\xd9\x8a\xd8\xa9";
            // (AR) لون الحالة النشطة (مفتاح/زرّ مفعَّل) — «لون_نشط».
            inline constexpr const char *ACTIVE_COLOR = "\xd9\x84\xd9\x88\xd9\x86_\xd9\x86\xd8\xb4\xd8\xb7";
            // (AR) لون الحدّ الخارجيّ — «حد_لون».
            inline constexpr const char *BORDER_COLOR = "\xd8\xad\xd8\xaf_\xd9\x84\xd9\x88\xd9\x86";
            // (AR) نصف قطر تدوير الزوايا (بالبكسل) — «زوايا».
            inline constexpr const char *CORNER_RADIUS = "\xd8\xb2\xd9\x88\xd8\xa7\xd9\x8a\xd8\xa7";
            // (AR) نصف القطر (للدائرة/التدوير) — «نصف_قطر».
            inline constexpr const char *RADIUS = "\xd9\x86\xd8\xb5\xd9\x81_\xd9\x82\xd8\xb7\xd8\xb1";
            // (AR) سماكة الخطّ/الحدّ (بالبكسل) — «سماكة».
            inline constexpr const char *THICKNESS = "\xd8\xb3\xd9\x85\xd8\xa7\xd9\x83\xd8\xa9";
            // (AR) الشفافية (0.0 شفّاف تمامًا … 1.0 معتِم) — «شفافية».
            inline constexpr const char *OPACITY = "\xd8\xb4\xd9\x81\xd8\xa7\xd9\x81\xd9\x8a\xd8\xa9";
            // (AR) مواصفة الظلّ (وجوده/لونه) — «ظل».
            inline constexpr const char *SHADOW = "\xd8\xb8\xd9\x84";
            // (AR) لون بداية التدرّج — «تدرج».
            inline constexpr const char *GRADIENT = "\xd8\xaa\xd8\xaf\xd8\xb1\xd8\xac";
            // (AR) لون نهاية التدرّج — «تدرج_نهاية».
            inline constexpr const char *GRADIENT_END = "\xd8\xaa\xd8\xaf\xd8\xb1\xd8\xac_\xd9\x86\xd9\x87\xd8\xa7\xd9\x8a\xd8\xa9";
            // (AR) الارتفاع البصريّ (شدّة الظلّ) — «رفع».
            inline constexpr const char *ELEVATION = "\xd8\xb1\xd9\x81\xd8\xb9";
            // (AR) هل العنصر مفعَّل (تفاعليّ) أم مُعطَّل — «مفعل».
            inline constexpr const char *ENABLED = "\xd9\x85\xd9\x81\xd8\xb9\xd9\x84";
            // (AR) القيمة القصوى (لشريط التقدّم/المنزلق) — «المجموع».
            inline constexpr const char *TOTAL = "\xd8\xa7\xd9\x84\xd9\x85\xd8\xac\xd9\x85\xd9\x88\xd8\xb9";
            // (AR) القيمة الحاليّة (لشريط التقدّم/المنزلق) — «الحالي».
            inline constexpr const char *CURRENT = "\xd8\xa7\xd9\x84\xd8\xad\xd8\xa7\xd9\x84\xd9\x8a";
            // (AR) الإزاحة الأفقيّة بالبكسل — تمرير للحاويات القابلة للتمرير، وموضع حرّ لغيرها — «إزاحة_س».
            inline constexpr const char *OFFSET_X = "\xd8\xa5\xd8\xb2\xd8\xa7\xd8\xad\xd8\xa9_\xd8\xb3";
            // (AR) الإزاحة الرأسيّة بالبكسل — تمرير للحاويات القابلة للتمرير، وموضع حرّ لغيرها — «إزاحة_ص».
            inline constexpr const char *OFFSET_Y = "\xd8\xa5\xd8\xb2\xd8\xa7\xd8\xad\xd8\xa9_\xd8\xb5";
            // (AR) هجاء بديل لـ«أيقونة» (بألف بلا همزة) — اسم الأيقونة — «ايقونة».
            inline constexpr const char *ICON_ALT = "\xd8\xa7\xd9\x8a\xd9\x82\xd9\x88\xd9\x86\xd8\xa9";
            // (AR) رمز نصّيّ (مثل محرف الأيقونة) — «رمز».
            inline constexpr const char *SYMBOL = "\xd8\xb1\xd9\x85\xd8\xb2";
            // (AR) محرف واحد يُعرَض (نحو أوّل حرف من عنصر) — «حرف».
            inline constexpr const char *CHAR = "\xd8\xad\xd8\xb1\xd9\x81";
            // (AR) مسار المورد (صورة ونحوها) — «مسار».
            inline constexpr const char *PATH = "\xd9\x85\xd8\xb3\xd8\xa7\xd8\xb1";
            // (AR) اسم مجموعة العنصر (أزرار الاختيار المترابطة ونحوها) — «مجموعة».
            inline constexpr const char *GROUP = "\xd9\x85\xd8\xac\xd9\x85\xd9\x88\xd8\xb9\xd8\xa9";
            // (AR) القيمة الدنيا (منزلق/مدى) — «أدنى».
            inline constexpr const char *MIN = "\xd8\xa3\xd8\xaf\xd9\x86\xd9\x89";
            // (AR) القيمة القصوى (منزلق/مدى) — «أقصى».
            inline constexpr const char *MAX = "\xd8\xa3\xd9\x82\xd8\xb5\xd9\x89";
            // (AR) المجموع الكلّيّ (بديل دلاليّ لـ«المجموع») — «إجمالي».
            inline constexpr const char *TOTAL_SUM = "\xd8\xa5\xd8\xac\xd9\x85\xd8\xa7\xd9\x84\xd9\x8a";
            // (AR) إظهار أرقام الأسطر (محرِّر الشيفرة) — «أرقام_أسطر».
            inline constexpr const char *LINE_NUMBERS = "\xd8\xa3\xd8\xb1\xd9\x82\xd8\xa7\xd9\x85_\xd8\xa3\xd8\xb3\xd8\xb7\xd8\xb1";
            // (AR) حجم الخليّة (بالبكسل) في الشبكة/الجدول — «حجم_خلية».
            inline constexpr const char *CELL_SIZE = "\xd8\xad\xd8\xac\xd9\x85_\xd8\xae\xd9\x84\xd9\x8a\xd8\xa9";
            // (AR) حدود المنطقة (نطاق/إطار) — «حدود».
            inline constexpr const char *BOUNDS = "\xd8\xad\xd8\xaf\xd9\x88\xd8\xaf";
            // (AR) هل الشكل دائريّ (نحو صورة رمزيّة) — «دائرة».
            inline constexpr const char *CIRCLE = "\xd8\xaf\xd8\xa7\xd8\xa6\xd8\xb1\xd8\xa9";
            // (AR) هل السمة داكنة — «داكن».
            inline constexpr const char *DARK = "\xd8\xaf\xd8\xa7\xd9\x83\xd9\x86";
            // (AR) هجاء بديل لـ«سماكة» (سمك الخطّ/الحدّ) — «سمك».
            inline constexpr const char *THICKNESS_ALT = "\xd8\xb3\xd9\x85\xd9\x83";
            // (AR) رقم الصفحة (ترقيم الصفحات) — «صفحة».
            inline constexpr const char *PAGE = "\xd8\xb5\xd9\x81\xd8\xad\xd8\xa9";
            // (AR) نصّ الشيفرة المصدريّة (كتلة/محرِّر شيفرة) — «كود».
            inline constexpr const char *CODE = "\xd9\x83\xd9\x88\xd8\xaf";
            // (AR) لغة الشيفرة (للإبراز النحويّ) — «لغة».
            inline constexpr const char *LANGUAGE = "\xd9\x84\xd8\xba\xd8\xa9";
            // (AR) لون الأيقونة — «لون_الايقونة».
            inline constexpr const char *ICON_COLOR = "\xd9\x84\xd9\x88\xd9\x86_\xd8\xa7\xd9\x84\xd8\xa7\xd9\x8a\xd9\x82\xd9\x88\xd9\x86\xd8\xa9";
            // (AR) لون مقبض المنزلق/المفتاح — «لون_المقبض».
            inline constexpr const char *HANDLE_COLOR = "\xd9\x84\xd9\x88\xd9\x86_\xd8\xa7\xd9\x84\xd9\x85\xd9\x82\xd8\xa8\xd8\xb6";
            // (AR) هل العنصر محدَّد (خانة اختيار/تبويب نشط) — «محدد».
            inline constexpr const char *SELECTED = "\xd9\x85\xd8\xad\xd8\xaf\xd8\xaf";
            // (AR) النصّ البديل (وصف الصورة للوصوليّة) — «نص_بديل».
            inline constexpr const char *ALT_TEXT = "\xd9\x86\xd8\xb5_\xd8\xa8\xd8\xaf\xd9\x8a\xd9\x84";
            // (AR) نوع العنصر (نوع حقل الإدخال ونحوه) — «نوع».
            inline constexpr const char *TYPE = "\xd9\x86\xd9\x88\xd8\xb9";
            // (AR) وصف نصّيّ للعنصر — «وصف».
            inline constexpr const char *DESCRIPTION = "\xd9\x88\xd8\xb5\xd9\x81";
            // (AR) بديل لاتينيّ لـ«محتوى» — «content».
            inline constexpr const char *CONTENT_LATIN = "content";
            // (AR) بديل لاتينيّ لـ«عنوان» — «title».
            inline constexpr const char *TITLE_LATIN = "title";
            // (AR) بديل لاتينيّ لـ«مصدر» — «source».
            inline constexpr const char *SOURCE_LATIN = "source";
            // (AR) بديل لاتينيّ لـ«لغة» — «language».
            inline constexpr const char *LANGUAGE_LATIN = "language";
            // (AR) بديل لاتينيّ لـ«نص_بديل» — «alt».
            inline constexpr const char *ALT_LATIN = "alt";
            // (AR) بديل لاتينيّ لـ«أقصى» — «max».
            inline constexpr const char *MAX_LATIN = "max";
            // (AR) بديل لاتينيّ لـ«أدنى» — «min».
            inline constexpr const char *MIN_LATIN = "min";
            // (AR) خطّ العرض الجغرافيّ (خريطة) — «lat».
            inline constexpr const char *LAT_LATIN = "lat";
            // (AR) خطّ الطول الجغرافيّ (خريطة) — «lng».
            inline constexpr const char *LNG_LATIN = "lng";
            // (AR) بديل لاتينيّ لـ«مسار/مصدر» (مسار الصورة) — «src».
            inline constexpr const char *SRC_LATIN = "src";
            // (AR) بديل لاتينيّ لـ«قيمة» — «value».
            inline constexpr const char *VALUE_LATIN = "value";
            // (AR) بديل لاتينيّ لـ«تلميح» — «placeholder».
            inline constexpr const char *PLACEHOLDER_LATIN = "placeholder";
            // (AR) إزاحة تمرير أفقيّة (مفتاح لاتينيّ داخليّ للمُرسِّم) — «scroll_x».
            inline constexpr const char *SCROLL_X_LATIN = "scroll_x";
            // (AR) إزاحة تمرير رأسيّة (مفتاح لاتينيّ داخليّ للمُرسِّم) — «scroll_y».
            inline constexpr const char *SCROLL_Y_LATIN = "scroll_y";
            // (AR) نصيبُ العنصرِ من المساحةِ الفائضةِ في صفٍّ أو عمود (موسع/مرن) — «مرونة».
            inline constexpr const char *FLEX = "\xd9\x85\xd8\xb1\xd9\x88\xd9\x86\xd8\xa9";
            // (AR) نسبةُ العرضِ إلى الارتفاعِ لعنصرِ «نسبة_عرض» — «نسبة».
            inline constexpr const char *RATIO = "\xd9\x86\xd8\xb3\xd8\xa8\xd8\xa9";
            // (AR) كسرٌ من عرضِ الأبِ (٠–١) لعنصرِ «صندوق_نسبي» — «عامل_العرض».
            inline constexpr const char *WIDTH_FACTOR = "\xd8\xb9\xd8\xa7\xd9\x85\xd9\x84_\xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xb6";
            // (AR) كسرٌ من ارتفاعِ الأبِ (٠–١) لعنصرِ «صندوق_نسبي» — «عامل_الارتفاع».
            inline constexpr const char *HEIGHT_FACTOR = "\xd8\xb9\xd8\xa7\xd9\x85\xd9\x84_\xd8\xa7\xd9\x84\xd8\xa7\xd8\xb1\xd8\xaa\xd9\x81\xd8\xa7\xd8\xb9";
            // (AR) الحدُّ الأدنى للعرضِ في عنصرِ «صندوق_مقيد» — «أدنى_عرض».
            inline constexpr const char *MIN_WIDTH = "\xd8\xa3\xd8\xaf\xd9\x86\xd9\x89_\xd8\xb9\xd8\xb1\xd8\xb6";
            // (AR) الحدُّ الأقصى للعرضِ في عنصرِ «صندوق_مقيد» — «أقصى_عرض».
            inline constexpr const char *MAX_WIDTH = "\xd8\xa3\xd9\x82\xd8\xb5\xd9\x89_\xd8\xb9\xd8\xb1\xd8\xb6";
            // (AR) الحدُّ الأدنى للارتفاعِ في عنصرِ «صندوق_مقيد» — «أدنى_ارتفاع».
            inline constexpr const char *MIN_HEIGHT = "\xd8\xa3\xd8\xaf\xd9\x86\xd9\x89_\xd8\xa7\xd8\xb1\xd8\xaa\xd9\x81\xd8\xa7\xd8\xb9";
            // (AR) الحدُّ الأقصى للارتفاعِ في عنصرِ «صندوق_مقيد» — «أقصى_ارتفاع».
            inline constexpr const char *MAX_HEIGHT = "\xd8\xa3\xd9\x82\xd8\xb5\xd9\x89_\xd8\xa7\xd8\xb1\xd8\xaa\xd9\x81\xd8\xa7\xd8\xb9";
            // (AR) بديل احتياطيّ لاتينيّ (مسار UINode) — يقرؤه المُرسِّم فقط — «text».
            inline constexpr const char *TEXT_LATIN = "text";

            // ================================================================
            // (AR) مفاتيح **عدديّة** (value_type: عدد في ui_props.yaml).
            //   لماذا: المصرّف يختار أوپكود SET_PROP بحسب نوع القيمة وقت الترجمة،
            //   لكنّ قيمًا كثيرة نوعها يتقرّر زمنَ التشغيل (نتيجة `/` مثلًا نوعها
            //   Any لأنّ صحيح/صحيح قد يكون صحيحًا أو عشريًّا). كان المجهولُ يسقط
            //   إلى SET_PROP_STR فتُخزَّن «نصف_قطر» **نصًّا** ويقرؤها المُرسِّم صفرًا
            //   (مقيس بالبكسل: `نصف_قطر(22)` قرصٌ، و`نصف_قطر(قطر / 2)` مربّع).
            //   بهذا الجدول يحسم المصرّفُ بالمفتاح لا بالقيمة، ومن SoT لا بسلسلة
            //   حرفيّة — التزامًا بقاعدة «لا literals منطقيّة مباشرة».
            // (EN) Numeric keys (value_type: عدد). The compiler picks the SET_PROP
            //   opcode from the compile-time value type, but some values are typed
            //   at runtime (`/` yields Any). Unknown fell back to SET_PROP_STR, so a
            //   numeric key was stored as text and read back as 0 by the renderer.
            //   This table lets the compiler decide by key, sourced from the SoT.
            // ================================================================
            inline bool isNumericPropKey(const char *name)
            {
                if (!name)
                    return false;
                static const char *const NUMERIC_KEYS[] = {
                    WIDTH,  // عرض
                    HEIGHT,  // ارتفاع
                    PADDING,  // حشوة
                    PADDING_TOP,  // حشوة_أعلى
                    PADDING_BOTTOM,  // حشوة_أسفل
                    PADDING_START,  // حشوة_بداية
                    PADDING_END,  // حشوة_نهاية
                    MARGIN,  // هامش
                    SPACING,  // تباعد
                    WEIGHT,  // وزن
                    COLUMNS,  // أعمدة
                    FONT_SIZE,  // حجم_خط
                    FONT_SIZE_ALT,  // حجم_الخط
                    SIZE,  // حجم
                    FLEX_LATIN,  // flex
                    COLUMNS_LATIN,  // columns
                    WIDTH_LATIN,  // width
                    HEIGHT_LATIN,  // height
                    CORNER_RADIUS,  // زوايا
                    RADIUS,  // نصف_قطر
                    THICKNESS,  // سماكة
                    OPACITY,  // شفافية
                    ELEVATION,  // رفع
                    TOTAL,  // المجموع
                    CURRENT,  // الحالي
                    OFFSET_X,  // إزاحة_س
                    OFFSET_Y,  // إزاحة_ص
                    MIN,  // أدنى
                    MAX,  // أقصى
                    TOTAL_SUM,  // إجمالي
                    CELL_SIZE,  // حجم_خلية
                    THICKNESS_ALT,  // سمك
                    PAGE,  // صفحة
                    MAX_LATIN,  // max
                    MIN_LATIN,  // min
                    LAT_LATIN,  // lat
                    LNG_LATIN,  // lng
                    SCROLL_X_LATIN,  // scroll_x
                    SCROLL_Y_LATIN,  // scroll_y
                    FLEX,  // مرونة
                    RATIO,  // نسبة
                    WIDTH_FACTOR,  // عامل_العرض
                    HEIGHT_FACTOR,  // عامل_الارتفاع
                    MIN_WIDTH,  // أدنى_عرض
                    MAX_WIDTH,  // أقصى_عرض
                    MIN_HEIGHT,  // أدنى_ارتفاع
                    MAX_HEIGHT,  // أقصى_ارتفاع
                };
                for (const char *k : NUMERIC_KEYS)
                {
                    const char *a = k;
                    const char *b = name;
                    while (*a && *a == *b)
                    {
                        ++a;
                        ++b;
                    }
                    if (*a == '\0' && *b == '\0')
                        return true;
                }
                return false;
            }
            // ================================================================
            // (AR) X(ID) — جردُ **كلِّ** مفاتيحِ الخصائصِ القانونيّة.
            //   يستهلكه المفسّرُ للتحقّقِ من اسمِ المعدّلِ قبلَ كتابتِه: كان فضاءُ
            //   المعدّلاتِ مفتوحًا بلا تحقّق، فخطأٌ إملائيٌّ («نصف_قطرر») يُكتَب
            //   خاصّيّةً لا قارئَ لها ويُبتلَع صامتًا — يظهر أثرُه بكسلًا مفقودًا
            //   لا رسالةَ خطأ. الجردُ من مصدرِ الحقيقةِ فلا قائمةَ ثانيةٌ تنحرف.
            // (EN) X(ID) — inventory of every canonical property key; the
            //   interpreter validates modifier names against it, so a typo warns
            //   instead of being silently written as an unread property.
            // ================================================================
#define SAD_UI_PROP_KEY_LIST(X) \
    X(TITLE) /* عنوان */ \
    X(CONTENT) /* محتوى */ \
    X(TEXT) /* نص */ \
    X(ICON) /* أيقونة */ \
    X(SOURCE) /* مصدر */ \
    X(NAME) /* اسم */ \
    X(HINT) /* تلميح */ \
    X(VALUE) /* قيمة */ \
    X(MESSAGE) /* رسالة */ \
    X(WIDTH) /* عرض */ \
    X(HEIGHT) /* ارتفاع */ \
    X(ALIGN) /* محاذاة */ \
    X(PADDING) /* حشوة */ \
    X(PADDING_TOP) /* حشوة_أعلى */ \
    X(PADDING_BOTTOM) /* حشوة_أسفل */ \
    X(PADDING_START) /* حشوة_بداية */ \
    X(PADDING_END) /* حشوة_نهاية */ \
    X(MARGIN) /* هامش */ \
    X(SPACING) /* تباعد */ \
    X(WEIGHT) /* وزن */ \
    X(COLUMNS) /* أعمدة */ \
    X(FONT_SIZE) /* حجم_خط */ \
    X(FONT_SIZE_ALT) /* حجم_الخط */ \
    X(SIZE) /* حجم */ \
    X(FLEX_LATIN) /* flex */ \
    X(COLUMNS_LATIN) /* columns */ \
    X(WIDTH_LATIN) /* width */ \
    X(HEIGHT_LATIN) /* height */ \
    X(COLOR) /* لون */ \
    X(TEXT_COLOR) /* لون_النص */ \
    X(TEXT_COLOR_ALT) /* لون_نص */ \
    X(BG) /* خلفية */ \
    X(BG_COLOR) /* لون_خلفية */ \
    X(ACTIVE_COLOR) /* لون_نشط */ \
    X(BORDER_COLOR) /* حد_لون */ \
    X(CORNER_RADIUS) /* زوايا */ \
    X(RADIUS) /* نصف_قطر */ \
    X(THICKNESS) /* سماكة */ \
    X(OPACITY) /* شفافية */ \
    X(SHADOW) /* ظل */ \
    X(GRADIENT) /* تدرج */ \
    X(GRADIENT_END) /* تدرج_نهاية */ \
    X(ELEVATION) /* رفع */ \
    X(ENABLED) /* مفعل */ \
    X(TOTAL) /* المجموع */ \
    X(CURRENT) /* الحالي */ \
    X(OFFSET_X) /* إزاحة_س */ \
    X(OFFSET_Y) /* إزاحة_ص */ \
    X(ICON_ALT) /* ايقونة */ \
    X(SYMBOL) /* رمز */ \
    X(CHAR) /* حرف */ \
    X(PATH) /* مسار */ \
    X(GROUP) /* مجموعة */ \
    X(MIN) /* أدنى */ \
    X(MAX) /* أقصى */ \
    X(TOTAL_SUM) /* إجمالي */ \
    X(LINE_NUMBERS) /* أرقام_أسطر */ \
    X(CELL_SIZE) /* حجم_خلية */ \
    X(BOUNDS) /* حدود */ \
    X(CIRCLE) /* دائرة */ \
    X(DARK) /* داكن */ \
    X(THICKNESS_ALT) /* سمك */ \
    X(PAGE) /* صفحة */ \
    X(CODE) /* كود */ \
    X(LANGUAGE) /* لغة */ \
    X(ICON_COLOR) /* لون_الايقونة */ \
    X(HANDLE_COLOR) /* لون_المقبض */ \
    X(SELECTED) /* محدد */ \
    X(ALT_TEXT) /* نص_بديل */ \
    X(TYPE) /* نوع */ \
    X(DESCRIPTION) /* وصف */ \
    X(CONTENT_LATIN) /* content */ \
    X(TITLE_LATIN) /* title */ \
    X(SOURCE_LATIN) /* source */ \
    X(LANGUAGE_LATIN) /* language */ \
    X(ALT_LATIN) /* alt */ \
    X(MAX_LATIN) /* max */ \
    X(MIN_LATIN) /* min */ \
    X(LAT_LATIN) /* lat */ \
    X(LNG_LATIN) /* lng */ \
    X(SRC_LATIN) /* src */ \
    X(VALUE_LATIN) /* value */ \
    X(PLACEHOLDER_LATIN) /* placeholder */ \
    X(SCROLL_X_LATIN) /* scroll_x */ \
    X(SCROLL_Y_LATIN) /* scroll_y */ \
    X(FLEX) /* مرونة */ \
    X(RATIO) /* نسبة */ \
    X(WIDTH_FACTOR) /* عامل_العرض */ \
    X(HEIGHT_FACTOR) /* عامل_الارتفاع */ \
    X(MIN_WIDTH) /* أدنى_عرض */ \
    X(MAX_WIDTH) /* أقصى_عرض */ \
    X(MIN_HEIGHT) /* أدنى_ارتفاع */ \
    X(MAX_HEIGHT) /* أقصى_ارتفاع */ \
    X(TEXT_LATIN) /* text */

#define SAD_UI_PROP_KEY_COUNT 94
        } // namespace props

        // ====================================================================
        // (AR) **قِيَم** الخصائص القانونيّة (لا أسماؤها): «وسط»، «يمين»، «صحيح»…
        //   كانت مكتوبةً حرفيًّا في كلّ مُرسِّمٍ ومولّدٍ على حِدة، فاختلفت القوائم
        //   بينها صامتةً (مُرسِّمُ سطحِ المكتبِ كان يقارن بـ"يمين" الحرفيّةِ بينما
        //   المشترَكُ يقارن بثابتٍ مسمًّى). رفعُها إلى مصدرِ الحقيقةِ يجعل
        //   المقارنةَ واحدةً في كلِّ مسار.
        // (EN) Canonical property *values* (not key names), generated from SoT so
        //   every renderer and code generator compares against one list.
        // ====================================================================
        namespace propval
        {
            // (AR) محاذاةٌ إلى الوسط — «وسط».
            inline constexpr const char *ALIGN_CENTER_AR = "\xd9\x88\xd8\xb3\xd8\xb7";
            // (AR) محاذاةُ الوسطِ — بديلٌ لاتينيّ — «center».
            inline constexpr const char *ALIGN_CENTER_EN = "center";
            // (AR) محاذاةٌ إلى اليمين — «يمين».
            inline constexpr const char *ALIGN_RIGHT_AR = "\xd9\x8a\xd9\x85\xd9\x8a\xd9\x86";
            // (AR) محاذاةُ اليمينِ — بديلٌ لاتينيّ — «right».
            inline constexpr const char *ALIGN_RIGHT_EN = "right";
            // (AR) محاذاةٌ إلى اليسار — «يسار».
            inline constexpr const char *ALIGN_LEFT_AR = "\xd9\x8a\xd8\xb3\xd8\xa7\xd8\xb1";
            // (AR) محاذاةُ اليسارِ — بديلٌ لاتينيّ — «left».
            inline constexpr const char *ALIGN_LEFT_EN = "left";
            // (AR) قيمةٌ منطقيّةٌ صادقة — «صحيح».
            inline constexpr const char *BOOL_TRUE_AR = "\xd8\xb5\xd8\xad\xd9\x8a\xd8\xad";
            // (AR) صادقٌ — بديلٌ لاتينيّ — «true».
            inline constexpr const char *BOOL_TRUE_EN = "true";
            // (AR) صادقٌ مكتوبًا رقمًا — «1».
            inline constexpr const char *BOOL_TRUE_ONE = "1";
            // (AR) مُفعَّلٌ — مرادفُ الصادقِ في مفاتيحِ التفعيل — «مفعل».
            inline constexpr const char *BOOL_ENABLED_AR = "\xd9\x85\xd9\x81\xd8\xb9\xd9\x84";
        } // namespace propval
    } // namespace ui
} // namespace sad
