// ============================================================================
// AUTO-GENERATED from language-truth/ui_modifiers.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_modifiers.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_modifiers.py
//
// To modify: edit language-truth/ui_modifiers.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_modifiers.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأسماء طرق (معدّلات) عناصر الواجهة الانسيابيّة.
//   يستهلكه موزّع المعدّلات في **المحرّكين معًا** (المفسّر ui_widget_method_call.cpp
//   والمترجم call_method_dispatch.cpp) مباشرةً عبر دوالّ is<Id> — فلا اسمَ معدّلٍ
//   حرفيّ في أيٍّ منهما (قاعدة «لا literals منطقيّة مباشرة»).
//   سياسة: الأسماء القانونيّة فقط، لا بدائل (المخطّط يمنع aliases).
// (EN) SoT for SadUI fluent modifier names, consumed DIRECTLY by BOTH engines
//   (interpreter + compiler) via the is<Id> predicates — no literal modifier name
//   in either. Canonical-only policy: no aliases (schema forbids them).
// ============================================================================

#pragma once

#include <string_view>

namespace sad
{
    namespace ui
    {
        namespace mods
        {
            // (AR) يضيف عنصرًا (أو عناصر) أبناءً للعنصر الحاليّ — «ابن».
            inline constexpr const char *CHILD = "\xd8\xa7\xd8\xa8\xd9\x86";
            inline bool isChild(std::string_view m) { return m == "\xd8\xa7\xd8\xa8\xd9\x86"; }

            // (AR) يسجّل معالِج حدث (عند_النقر، عند_التغيير، …) — أيّ اسمٍ يبدأ بالبادئة — «عند_».
            inline constexpr const char *EVENT = "\xd8\xb9\xd9\x86\xd8\xaf_";
            // (AR) يطابق أيّ اسمٍ يبدأ بالبادئة (عائلة عند_*).
            inline bool isEvent(std::string_view m) { return m.rfind("\xd8\xb9\xd9\x86\xd8\xaf_", 0) == 0; }

            // (AR) يبدأ سلسلة تحريك على العنصر (يقبل أنواعًا مركّبة بفاصلة) — «حرك».
            inline constexpr const char *ANIMATE = "\xd8\xad\xd8\xb1\xd9\x83";
            inline bool isAnimate(std::string_view m) { return m == "\xd8\xad\xd8\xb1\xd9\x83"; }

            // (AR) يعيّن مدّة الحركة الحاليّة (بالثواني) — «مدة».
            inline constexpr const char *DURATION = "\xd9\x85\xd8\xaf\xd8\xa9";
            inline bool isDuration(std::string_view m) { return m == "\xd9\x85\xd8\xaf\xd8\xa9"; }

            // (AR) يعيّن منحنى تسارع الحركة — «منحنى».
            inline constexpr const char *EASING = "\xd9\x85\xd9\x86\xd8\xad\xd9\x86\xd9\x89";
            inline bool isEasing(std::string_view m) { return m == "\xd9\x85\xd9\x86\xd8\xad\xd9\x86\xd9\x89"; }

            // (AR) يعيّن تأخير بدء الحركة (بالثواني) — «تأخير».
            inline constexpr const char *DELAY = "\xd8\xaa\xd8\xa3\xd8\xae\xd9\x8a\xd8\xb1";
            inline bool isDelay(std::string_view m) { return m == "\xd8\xaa\xd8\xa3\xd8\xae\xd9\x8a\xd8\xb1"; }

            // (AR) يعيّن عدد تكرارات الحركة — «تكرار».
            inline constexpr const char *REPEAT = "\xd8\xaa\xd9\x83\xd8\xb1\xd8\xa7\xd8\xb1";
            inline bool isRepeat(std::string_view m) { return m == "\xd8\xaa\xd9\x83\xd8\xb1\xd8\xa7\xd8\xb1"; }

            // (AR) يعكس الحركة تلقائيًّا بعد انتهائها — «عكس_تلقائي».
            inline constexpr const char *AUTO_REVERSE = "\xd8\xb9\xd9\x83\xd8\xb3_\xd8\xaa\xd9\x84\xd9\x82\xd8\xa7\xd8\xa6\xd9\x8a";
            inline bool isAutoReverse(std::string_view m) { return m == "\xd8\xb9\xd9\x83\xd8\xb3_\xd8\xaa\xd9\x84\xd9\x82\xd8\xa7\xd8\xa6\xd9\x8a"; }
        } // namespace mods
    } // namespace ui
} // namespace sad
