// بسم الله الرحمن الرحيم
// ==============================================================================
// cli_main.cpp - نقطة الدخول الرئيسية لأداة ص
// Main Entry Point for SAD CLI Tool
// ==============================================================================
//
// هذا الملف يحتوي على نقطة الدخول الرئيسية لأداة سطر الأوامر "ص"
// وهي الواجهة الرئيسية للتعامل مع لغة ص.
//
// الأداة تدعم الأوامر التالية:
// ----------------------------
//   ص بناء    - ترجمة الكود إلى ملف تنفيذي
//   ص شغّل    - ترجمة وتشغيل برنامج
//   ص اختبر   - تشغيل اختبارات المشروع
//   ص جديد    - إنشاء مشروع جديد
//   ص أضف     - إضافة اعتمادية
//   ص نشر     - نشر حزمة
//   ص وثّق    - توليد التوثيق
//   ص نسّق    - تنسيق الكود
//   ص تحقق    - التحقق من الكود
//   ص نسخة    - عرض الإصدار
//   ص مساعدة  - عرض المساعدة
//
// طريقة الاستخدام:
// ---------------
//   ص <أمر> [خيارات] [ملفات]
//   sad <command> [options] [files]
//
// المؤلف: فريق تطوير لغة ص
// التاريخ: 2026-01-23
// الإصدار: 1.0.0
// ==============================================================================

#include "cli_commands.hpp"
#include "mobile_project_gen.hpp"
#include "android_target.hpp"
#include "utf8_args.h"
#include <iostream>
#include <clocale>
#include <fstream>
#include <filesystem>
#include <sstream>

#ifdef _WIN32
#include <windows.h>
#include <io.h>
#include <fcntl.h>
#include <algorithm>
#endif

namespace sad
{
    namespace cli
    {

        void MobileCommand::generateGradleWrapper(const std::filesystem::path &android_dir)
        {
            namespace fs = std::filesystem;

            // إنشاء مجلد gradle/wrapper
            fs::create_directories(android_dir / "gradle" / "wrapper");

            // إنشاء gradle-wrapper.properties
            {
                std::ofstream out(android_dir / "gradle" / "wrapper" / "gradle-wrapper.properties");
                out << "distributionBase=GRADLE_USER_HOME\n";
                out << "distributionPath=wrapper/dists\n";
                out << "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.4-bin.zip\n";
                out << "networkTimeout=10000\n";
                out << "validateDistributionUrl=true\n";
                out << "zipStoreBase=GRADLE_USER_HOME\n";
                out << "zipStorePath=wrapper/dists\n";
            }

            // إنشاء gradlew.bat (Windows)
            {
                std::ofstream out(android_dir / "gradlew.bat");
                out << "@rem\n";
                out << "@rem Gradle startup script for Windows - Generated by SAD Language\n";
                out << "@rem\n\n";
                out << "@if \"%DEBUG%\"==\"\" @echo off\n";
                out << "@rem Set local scope for the variables with windows NT shell\n";
                out << "if \"%OS%\"==\"Windows_NT\" setlocal\n\n";
                out << "set DIRNAME=%~dp0\n";
                out << "if \"%DIRNAME%\"==\"\" set DIRNAME=.\n";
                out << "@rem This is normally unused\n";
                out << "set APP_BASE_NAME=%~n0\n";
                out << "set APP_HOME=%DIRNAME%\n\n";
                out << "@rem Resolve any \".\" and \"..\" in APP_HOME to make it shorter.\n";
                out << "for %%i in (\"%APP_HOME%\") do set APP_HOME=%%~fi\n\n";
                out << "@rem Add default JVM options here.\n";
                out << "set DEFAULT_JVM_OPTS=\"-Xmx64m\" \"-Xms64m\"\n\n";
                out << "@rem Find java.exe\n";
                out << "if defined JAVA_HOME goto findJavaFromJavaHome\n\n";
                out << "set JAVA_EXE=java.exe\n";
                out << "%JAVA_EXE% -version >NUL 2>&1\n";
                out << "if %ERRORLEVEL% equ 0 goto execute\n\n";
                out << "echo.\n";
                out << "echo ERROR: JAVA_HOME is not set and no 'java' command found.\n";
                out << "echo Please set the JAVA_HOME variable in your environment.\n";
                out << "goto fail\n\n";
                out << ":findJavaFromJavaHome\n";
                out << "set JAVA_HOME=%JAVA_HOME:\"=%\n";
                out << "set JAVA_EXE=%JAVA_HOME%/bin/java.exe\n\n";
                out << "if exist \"%JAVA_EXE%\" goto execute\n\n";
                out << "echo.\n";
                out << "echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%\n";
                out << "goto fail\n\n";
                out << ":execute\n";
                out << "@rem Setup the command line\n";
                out << "set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar\n\n";
                out << "@rem Execute Gradle\n";
                out << "\"%JAVA_EXE%\" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "
                    << "\"-Dorg.gradle.appname=%APP_BASE_NAME%\" "
                    << "-classpath \"%CLASSPATH%\" "
                    << "org.gradle.wrapper.GradleWrapperMain %*\n\n";
                out << ":end\n";
                out << "@rem End local scope for the variables with windows NT shell\n";
                out << "if \"%OS%\"==\"Windows_NT\" endlocal\n\n";
                out << ":omega\n";
                out << "exit /b %ERRORLEVEL%\n\n";
                out << ":fail\n";
                out << "exit /b 1\n";
            }

            // إنشاء gradlew (Unix/Mac)
            {
                std::ofstream out(android_dir / "gradlew");
                out << "#!/bin/sh\n";
                out << "# Gradle startup script for UNIX - Generated by SAD Language\n\n";
                out << "APP_NAME=\"Gradle\"\n";
                out << "APP_BASE_NAME=$(basename \"$0\")\n";
                out << "DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'\n\n";
                out << "# Resolve the true real path of the script\n";
                out << "PRG=\"$0\"\n";
                out << "while [ -h \"$PRG\" ]; do\n";
                out << "    ls=$(ls -ld \"$PRG\")\n";
                out << "    link=$(expr \"$ls\" : '.*-> \\(.*\\)$')\n";
                out << "    if expr \"$link\" : '/.*' > /dev/null; then\n";
                out << "        PRG=\"$link\"\n";
                out << "    else\n";
                out << "        PRG=$(dirname \"$PRG\")/\"$link\"\n";
                out << "    fi\n";
                out << "done\n";
                out << "APP_HOME=$(cd \"$(dirname \"$PRG\")\" && pwd -P)\n\n";
                out << "CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar\n\n";
                out << "# Determine the Java command to use\n";
                out << "if [ -n \"$JAVA_HOME\" ]; then\n";
                out << "    JAVACMD=\"$JAVA_HOME/bin/java\"\n";
                out << "else\n";
                out << "    JAVACMD=\"java\"\n";
                out << "fi\n\n";
                out << "# Execute Gradle\n";
                out << "exec \"$JAVACMD\" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "
                    << "\"-Dorg.gradle.appname=$APP_BASE_NAME\" "
                    << "-classpath \"$CLASSPATH\" "
                    << "org.gradle.wrapper.GradleWrapperMain \"$@\"\n";
            }

            // ملاحظة: gradle-wrapper.jar يجب أن يكون موجوداً
            auto jar_path = android_dir / "gradle" / "wrapper" / "gradle-wrapper.jar";
            if (!fs::exists(jar_path))
            {
// 1. محاولة من مجلد resources بجوار الملف التنفيذي
#ifdef _WIN32
                {
                    // الحصول على مسار الملف التنفيذي
                    char exe_path[MAX_PATH];
                    GetModuleFileNameA(NULL, exe_path, MAX_PATH);
                    fs::path exe_dir = fs::path(exe_path).parent_path();
                    // البحث بالتسلسل: بجوار exe → في resources → في tools/compiler/resources
                    for (auto &candidate : {
                             exe_dir / "gradle-wrapper.jar",
                             exe_dir / "resources" / "gradle-wrapper.jar",
                             exe_dir / ".." / ".." / ".." / "tools" / "compiler" / "resources" / "gradle-wrapper.jar"})
                    {
                        if (fs::exists(candidate))
                        {
                            fs::copy_file(candidate, jar_path, fs::copy_options::skip_existing);
                            break;
                        }
                    }
                }
#endif

                // 2. محاولة نسخ jar من Gradle المثبت
                if (!fs::exists(jar_path))
                {
                    const char *gradle_home = std::getenv("GRADLE_HOME");
                    if (gradle_home)
                    {
                        fs::path local_jar = fs::path(gradle_home) / "lib" / "gradle-wrapper.jar";
                        if (fs::exists(local_jar))
                        {
                            fs::copy_file(local_jar, jar_path, fs::copy_options::skip_existing);
                        }
                    }
                }

                // 3. محاولة من مسار المستخدم ~/.gradle (بحث موسع)
                if (!fs::exists(jar_path))
                {
#ifdef _WIN32
                    const char *user_home = std::getenv("USERPROFILE");
#else
                    const char *user_home = std::getenv("HOME");
#endif

                    if (user_home)
                    {
                        fs::path gradle_cache = fs::path(user_home) / ".gradle" / "wrapper" / "dists";
                        if (fs::exists(gradle_cache))
                        {
                            // البحث عن أي ملف jar يحتوي على "gradle-wrapper" في الاسم
                            for (auto &entry : fs::recursive_directory_iterator(gradle_cache))
                            {
                                std::string fname = entry.path().filename().string();
                                if (fname == "gradle-wrapper.jar" ||
                                    (fname.find("gradle-wrapper") != std::string::npos &&
                                     fname.find(".jar") != std::string::npos &&
                                     fname.find("shared") == std::string::npos))
                                {
                                    fs::copy_file(entry.path(), jar_path, fs::copy_options::skip_existing);
                                    break;
                                }
                            }
                        }
                    }
                }

                if (!fs::exists(jar_path))
                {
                    print_warning_ar("⚠ لم يُعثر على gradle-wrapper.jar");
                    print_info_ar("  شغّل 'gradle wrapper' في مجلد android/ لتوليده");
                }
            }
        }

        std::string MobileCommand::generateKotlinFromSadSource(const std::string &sad_source,
                                                               const std::string &screen_name)
        {
            std::ostringstream kt;

            // تحليل بسيط لملف ص واستخراج المكونات
            // البحث عن تعريفات الواجهة: واجهة اسم_الشاشة { ... }

            // استخراج معلومات من المصدر
            struct UIComponent
            {
                std::string type;     // نص، زر، عمود، صف، صورة، حقل_نص
                std::string content;  // المحتوى النصي
                std::string modifier; // المعدّلات
                std::vector<std::string> children;
            };

            // تحليل المكونات من كود ص
            std::vector<UIComponent> components;
            std::vector<std::pair<std::string, std::string>> state_vars; // اسم، نوع
            std::string view_name = screen_name;

            std::istringstream stream(sad_source);
            std::string line;
            bool in_view = false;
            bool in_display = false;

            while (std::getline(stream, line))
            {
                // تنظيف
                std::string trimmed = line;
                size_t start = trimmed.find_first_not_of(" \t\r\n");
                if (start == std::string::npos)
                    continue;
                trimmed = trimmed.substr(start);

                // تخطي التعليقات
                if (trimmed.substr(0, 2) == "//")
                    continue;

                // اكتشاف واجهة
                if (trimmed.find("واجهة ") == 0)
                {
                    auto space_pos = trimmed.find(' ');
                    auto brace_pos = trimmed.find('{');
                    if (space_pos != std::string::npos)
                    {
                        view_name = trimmed.substr(space_pos + 1);
                        if (brace_pos != std::string::npos)
                        {
                            view_name = trimmed.substr(space_pos + 1, brace_pos - space_pos - 1);
                        }
                        // إزالة مسافات
                        while (!view_name.empty() && (view_name.back() == ' ' || view_name.back() == '{'))
                            view_name.pop_back();
                        in_view = true;
                    }
                    continue;
                }

                // اكتشاف حالة (@حالة)
                if (in_view && trimmed.find("@حالة") != std::string::npos)
                {
                    // @حالة اسم: نوع = قيمة
                    auto colon_pos = trimmed.find(':');
                    auto eq_pos = trimmed.find('=');
                    if (colon_pos != std::string::npos)
                    {
                        std::string var_part = trimmed.substr(trimmed.find("حالة") + 5, colon_pos - trimmed.find("حالة") - 5);
                        // تنظيف
                        while (!var_part.empty() && var_part.front() == ' ')
                            var_part.erase(var_part.begin());
                        while (!var_part.empty() && var_part.back() == ' ')
                            var_part.pop_back();

                        std::string type_part = "عدد"; // افتراضي
                        if (colon_pos != std::string::npos)
                        {
                            size_t end = (eq_pos != std::string::npos) ? eq_pos : trimmed.length();
                            type_part = trimmed.substr(colon_pos + 1, end - colon_pos - 1);
                            while (!type_part.empty() && type_part.front() == ' ')
                                type_part.erase(type_part.begin());
                            while (!type_part.empty() && type_part.back() == ' ')
                                type_part.pop_back();
                        }

                        state_vars.push_back({var_part, type_part});
                    }
                    continue;
                }

                // اكتشاف عرض
                if (in_view && trimmed.find("عرض()") != std::string::npos)
                {
                    in_display = true;
                    continue;
                }

                // اكتشاف المكونات
                if (in_display)
                {
                    if (trimmed.find("نص(") == 0 || trimmed.find("نص(") != std::string::npos)
                    {
                        auto paren_start = trimmed.find("نص(") + 4;
                        if (trimmed.find("نص(") == 0)
                            paren_start = 3;
                        // البحث بعد "نص("
                        std::string text_start = trimmed.substr(trimmed.find("نص(") + 3);
                        auto quote_start = text_start.find('"');
                        auto quote_end = text_start.rfind('"');
                        std::string text_content;
                        if (quote_start != std::string::npos && quote_end > quote_start)
                        {
                            text_content = text_start.substr(quote_start + 1, quote_end - quote_start - 1);
                        }
                        else
                        {
                            // expression - e.g., "العداد: " + نص(عداد)
                            auto paren_end = text_start.rfind(')');
                            if (paren_end != std::string::npos)
                            {
                                text_content = text_start.substr(0, paren_end);
                            }
                        }
                        components.push_back({"نص", text_content, "", {}});
                    }
                    else if (trimmed.find("زر(") != std::string::npos)
                    {
                        auto quote_start = trimmed.find('"');
                        auto quote_end = trimmed.rfind('"');
                        std::string btn_text;
                        if (quote_start != std::string::npos && quote_end > quote_start)
                        {
                            btn_text = trimmed.substr(quote_start + 1, quote_end - quote_start - 1);
                        }
                        components.push_back({"زر", btn_text, "", {}});
                    }
                }
            }

            // إنشاء ملف Kotlin/Compose
            kt << "// ╔════════════════════════════════════════════════════════════════════╗\n";
            kt << "// ║    مُولَّد تلقائياً بواسطة مترجم لغة ص                            ║\n";
            kt << "// ║    Generated by SAD Language Compiler                             ║\n";
            kt << "// ╚════════════════════════════════════════════════════════════════════╝\n\n";

            kt << "package com.example.app\n\n";

            kt << "import android.os.Bundle\n";
            kt << "import androidx.activity.ComponentActivity\n";
            kt << "import androidx.activity.compose.setContent\n";
            kt << "import androidx.compose.foundation.layout.*\n";
            kt << "import androidx.compose.material3.*\n";
            kt << "import androidx.compose.runtime.*\n";
            kt << "import androidx.compose.ui.Alignment\n";
            kt << "import androidx.compose.ui.Modifier\n";
            kt << "import androidx.compose.ui.graphics.Color\n";
            kt << "import androidx.compose.ui.text.style.TextAlign\n";
            kt << "import androidx.compose.ui.unit.dp\n";
            kt << "import androidx.compose.ui.unit.sp\n";
            kt << "import androidx.compose.ui.platform.LocalLayoutDirection\n";
            kt << "import androidx.compose.ui.unit.LayoutDirection\n";
            kt << "import androidx.compose.runtime.CompositionLocalProvider\n\n";

            // توليد الشاشة الرئيسية
            kt << "/**\n";
            kt << " * الشاشة الرئيسية - مُولَّدة من كود لغة ص\n";
            kt << " */\n";
            kt << "@Composable\n";
            kt << "fun " << screen_name << "Screen() {\n";
            kt << "    // دعم الاتجاه من اليمين لليسار\n";
            kt << "    CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {\n";

            // متغيرات الحالة
            for (const auto &[name, type] : state_vars)
            {
                std::string kt_type = "Int";
                std::string kt_default = "0";
                if (type == "نص" || type == "String")
                {
                    kt_type = "String";
                    kt_default = "\"\"";
                }
                else if (type == "منطقي" || type == "Boolean")
                {
                    kt_type = "Boolean";
                    kt_default = "false";
                }
                else if (type == "عشري" || type == "Double")
                {
                    kt_type = "Double";
                    kt_default = "0.0";
                }

                kt << "        var " << name << " by remember { mutableStateOf(" << kt_default << ") }\n";
            }

            if (!state_vars.empty())
                kt << "\n";

            kt << "        Surface(\n";
            kt << "            modifier = Modifier.fillMaxSize(),\n";
            kt << "            color = MaterialTheme.colorScheme.background\n";
            kt << "        ) {\n";
            kt << "            Column(\n";
            kt << "                modifier = Modifier\n";
            kt << "                    .fillMaxSize()\n";
            kt << "                    .padding(16.dp),\n";
            kt << "                verticalArrangement = Arrangement.Center,\n";
            kt << "                horizontalAlignment = Alignment.CenterHorizontally\n";
            kt << "            ) {\n";

            // المكونات
            for (const auto &comp : components)
            {
                if (comp.type == "نص")
                {
                    kt << "                Text(\n";

                    // فحص ما إذا كان تعبيراً أو نصاً ثابتاً
                    if (comp.content.find('+') != std::string::npos || comp.content.find("نص(") != std::string::npos)
                    {
                        // تعبير ديناميكي - تحويل بسيط
                        std::string expr = comp.content;
                        // استبدال "نص(VARNAME)" بـ "$VARNAME"
                        // بسيط: نترك كتعليق وقيمة ثابتة
                        kt << "                    text = \"" << comp.content << "\", // TODO: dynamic expression\n";
                    }
                    else
                    {
                        kt << "                    text = \"" << comp.content << "\",\n";
                    }

                    kt << "                    style = MaterialTheme.typography.headlineMedium,\n";
                    kt << "                    textAlign = TextAlign.Center\n";
                    kt << "                )\n";
                    kt << "                Spacer(modifier = Modifier.height(16.dp))\n";
                }
                else if (comp.type == "زر")
                {
                    kt << "                Button(\n";
                    kt << "                    onClick = { /* TODO: action */ },\n";
                    kt << "                    modifier = Modifier.padding(8.dp)\n";
                    kt << "                ) {\n";
                    kt << "                    Text(\"" << comp.content << "\")\n";
                    kt << "                }\n";
                    kt << "                Spacer(modifier = Modifier.height(8.dp))\n";
                }
            }

            // إذا لم نجد مكونات، أضف شاشة افتراضية
            if (components.empty())
            {
                kt << "                Text(\n";
                kt << "                    text = \"مرحباً من لغة ص! 🌟\",\n";
                kt << "                    style = MaterialTheme.typography.headlineLarge,\n";
                kt << "                    textAlign = TextAlign.Center\n";
                kt << "                )\n";
                kt << "                Spacer(modifier = Modifier.height(16.dp))\n";
                kt << "                Text(\n";
                kt << "                    text = \"تطبيق مُولَّد تلقائياً\",\n";
                kt << "                    style = MaterialTheme.typography.bodyLarge,\n";
                kt << "                    color = MaterialTheme.colorScheme.secondary\n";
                kt << "                )\n";
            }

            kt << "            }\n";
            kt << "        }\n";
            kt << "    }\n";
            kt << "}\n";

            return kt.str();
        }

        std::string MobileCommand::generateSwiftUIFromSadSource(const std::string &sad_source,
                                                                const std::string &screen_name)
        {
            std::ostringstream sw;

            sw << "// ╔════════════════════════════════════════════════════════════════════╗\n";
            sw << "// ║    مُولَّد تلقائياً بواسطة مترجم لغة ص                            ║\n";
            sw << "// ║    Generated by SAD Language Compiler                             ║\n";
            sw << "// ╚════════════════════════════════════════════════════════════════════╝\n\n";

            sw << "import SwiftUI\n\n";

            sw << "/// الشاشة الرئيسية - مُولَّدة من كود لغة ص\n";
            sw << "struct " << screen_name << "View: View {\n";

            // تحليل بسيط لاستخراج حالات
            std::istringstream stream(sad_source);
            std::string line;
            std::vector<std::pair<std::string, std::string>> state_vars;

            while (std::getline(stream, line))
            {
                std::string trimmed = line;
                size_t start = trimmed.find_first_not_of(" \t\r\n");
                if (start == std::string::npos)
                    continue;
                trimmed = trimmed.substr(start);

                if (trimmed.find("@حالة") != std::string::npos)
                {
                    auto colon_pos = trimmed.find(':');
                    if (colon_pos != std::string::npos)
                    {
                        std::string var_part = trimmed.substr(trimmed.find("حالة") + 5, colon_pos - trimmed.find("حالة") - 5);
                        while (!var_part.empty() && var_part.front() == ' ')
                            var_part.erase(var_part.begin());
                        while (!var_part.empty() && var_part.back() == ' ')
                            var_part.pop_back();

                        auto eq_pos = trimmed.find('=');
                        std::string type_part = trimmed.substr(colon_pos + 1, (eq_pos != std::string::npos ? eq_pos : trimmed.length()) - colon_pos - 1);
                        while (!type_part.empty() && type_part.front() == ' ')
                            type_part.erase(type_part.begin());
                        while (!type_part.empty() && type_part.back() == ' ')
                            type_part.pop_back();

                        std::string swift_type = "Int";
                        std::string swift_default = "0";
                        if (type_part == "نص" || type_part == "String")
                        {
                            swift_type = "String";
                            swift_default = "\"\"";
                        }
                        else if (type_part == "منطقي" || type_part == "Bool")
                        {
                            swift_type = "Bool";
                            swift_default = "false";
                        }

                        sw << "    @State private var " << var_part << ": " << swift_type << " = " << swift_default << "\n";
                        state_vars.push_back({var_part, swift_type});
                    }
                }
            }

            if (!state_vars.empty())
                sw << "\n";

            sw << "    var body: some View {\n";
            sw << "        NavigationView {\n";
            sw << "            VStack(spacing: 20) {\n";
            sw << "                Text(\"مرحباً من لغة ص! 🌟\")\n";
            sw << "                    .font(.largeTitle)\n";
            sw << "                    .fontWeight(.bold)\n";
            sw << "                    .multilineTextAlignment(.center)\n";
            sw << "\n";
            sw << "                Text(\"تطبيق مُولَّد تلقائياً\")\n";
            sw << "                    .font(.title2)\n";
            sw << "                    .foregroundColor(.secondary)\n";

            for (const auto &[name, type] : state_vars)
            {
                sw << "\n";
                sw << "                Text(\"" << name << ": \\(" << name << ")\")\n";
                sw << "                    .font(.title3)\n";
            }

            sw << "            }\n";
            sw << "            .padding()\n";
            sw << "            .environment(\\.layoutDirection, .rightToLeft)\n";
            sw << "        }\n";
            sw << "    }\n";
            sw << "}\n\n";

            sw << "#Preview {\n";
            sw << "    " << screen_name << "View()\n";
            sw << "}\n";

            return sw.str();
        }

        int MobileCommand::execute_info(const ParsedOptions &options)
        {
            std::cout << colors::BOLD << colors::CYAN;
            std::cout << R"(
    ╔═══════════════════════════════════════════════════╗
    ║     📱 نظام تطبيقات الهاتف بلغة ص                ║
    ║     Mobile Application System for SAD Language    ║
    ╚═══════════════════════════════════════════════════╝
)" << colors::RESET << std::endl;

            std::cout << colors::BOLD << "المنصات المدعومة:" << colors::RESET << std::endl;
            std::cout << "  🤖 أندرويد (Android 5.0+) - NDK + Jetpack Compose" << std::endl;
            std::cout << "  🍎 iOS (14.0+) - Swift + SwiftUI" << std::endl;
            std::cout << std::endl;

            std::cout << colors::BOLD << "الميزات:" << colors::RESET << std::endl;
            std::cout << "  • واجهة مستخدم تصريحية بالعربية" << std::endl;
            std::cout << "  • كود واحد لجميع المنصات" << std::endl;
            std::cout << "  • توليد كود أصلي (Kotlin/Swift)" << std::endl;
            std::cout << "  • بناء APK فعلي عبر Gradle" << std::endl;
            std::cout << "  • تثبيت وتشغيل عبر ADB" << std::endl;
            std::cout << "  • دعم الكاميرا والموقع والمستشعرات" << std::endl;
            std::cout << std::endl;

            std::cout << colors::BOLD << "حالة الأدوات:" << colors::RESET << std::endl;

            const char *ndk = std::getenv("ANDROID_NDK_HOME");
            if (ndk)
            {
                std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " Android NDK: " << ndk << std::endl;
            }
            else
            {
                std::cout << "  " << colors::RED << "✗" << colors::RESET << " Android NDK: غير معين (ANDROID_NDK_HOME)" << std::endl;
            }

            const char *sdk = std::getenv("ANDROID_HOME");
            if (sdk)
            {
                std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " Android SDK: " << sdk << std::endl;
            }
            else
            {
                std::cout << "  " << colors::RED << "✗" << colors::RESET << " Android SDK: غير معين (ANDROID_HOME)" << std::endl;
            }

            const char *java_home = std::getenv("JAVA_HOME");
            if (java_home)
            {
                std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " JAVA_HOME: " << java_home << std::endl;
            }
            else
            {
                std::cout << "  " << colors::RED << "✗" << colors::RESET << " JAVA_HOME: غير معين" << std::endl;
            }

// التحقق من ADB
#ifdef _WIN32
            int adb_ret = std::system("adb version > nul 2>&1");
#else
            int adb_ret = std::system("adb version > /dev/null 2>&1");
#endif

            if (adb_ret == 0)
            {
                std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " ADB: متوفر" << std::endl;
            }
            else
            {
                std::cout << "  " << colors::RED << "✗" << colors::RESET << " ADB: غير متوفر" << std::endl;
            }

// التحقق من Gradle
#ifdef _WIN32
            int gradle_ret = std::system("gradle --version > nul 2>&1");
#else
            int gradle_ret = std::system("gradle --version > /dev/null 2>&1");
#endif

            if (gradle_ret == 0)
            {
                std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " Gradle: متوفر" << std::endl;
            }
            else
            {
                std::cout << "  " << colors::YELLOW << "⚠" << colors::RESET << " Gradle: غير متوفر (ليس مطلوباً مع Gradle Wrapper)" << std::endl;
            }

#ifdef __APPLE__
            std::cout << "  " << colors::GREEN << "✓" << colors::RESET << " Xcode: متوفر" << std::endl;
#else
            std::cout << "  " << colors::YELLOW << "⚠" << colors::RESET << " Xcode: غير متوفر (يتطلب macOS)" << std::endl;
#endif

            std::cout << std::endl;
            std::cout << colors::BOLD << "الأوامر:" << colors::RESET << std::endl;
            std::cout << "  ص هاتف جديد <اسم>     إنشاء مشروع هاتف جديد" << std::endl;
            std::cout << "  ص هاتف بناء            بناء APK (يتطلب JDK + Android SDK)" << std::endl;
            std::cout << "  ص هاتف شغّل             تثبيت وتشغيل على الجهاز (يتطلب ADB)" << std::endl;
            std::cout << "  ص هاتف واجهة <ملف>     توليد كود Kotlin/Swift من كود ص" << std::endl;
            std::cout << "  ص هاتف معلومات          عرض هذه المعلومات" << std::endl;
            std::cout << std::endl;

            return 0;
        }

        std::vector<CommandOption> MobileCommand::get_options() const
        {
            return {
                {"-a", "--android", "--اندرويد", "Target Android platform", "استهداف منصة أندرويد", false, "", true},
                {"-i", "--ios", "--آيفون", "Target iOS platform", "استهداف منصة iOS", false, "", true},
                {"", "--all", "--الكل", "Target all platforms", "استهداف جميع المنصات", false, "", true},
                {"-o", "--output", "--إخراج", "Output directory", "مجلد الإخراج", true, ".", false},
                {"-n", "--name", "--اسم", "Project/app name", "اسم المشروع/التطبيق", true, "", false},
                {"", "--release", "--إصدار", "Build in release mode", "بناء بوضع الإصدار", false, "", true},
            };
        }

        void MobileCommand::print_examples(std::ostream &os) const
        {
            os << colors::BOLD << "أمثلة الاستخدام / Usage Examples:" << colors::RESET << std::endl;
            os << std::endl;
            os << "  " << colors::GREEN << "# إنشاء مشروع هاتف جديد" << colors::RESET << std::endl;
            os << "  ص هاتف جديد تطبيقي --اندرويد" << std::endl;
            os << "  ص هاتف جديد تطبيقي --آيفون" << std::endl;
            os << "  ص هاتف جديد تطبيقي --الكل" << std::endl;
            os << std::endl;
            os << "  " << colors::GREEN << "# بناء التطبيق" << colors::RESET << std::endl;
            os << "  ص هاتف بناء --اندرويد" << std::endl;
            os << "  ص هاتف بناء --آيفون" << std::endl;
            os << std::endl;
            os << "  " << colors::GREEN << "# تشغيل على المحاكي" << colors::RESET << std::endl;
            os << "  ص هاتف شغّل --اندرويد" << std::endl;
            os << std::endl;
            os << "  " << colors::GREEN << "# توليد كود الواجهة" << colors::RESET << std::endl;
            os << "  ص هاتف واجهة شاشتي.ص --اندرويد" << std::endl;
            os << "  ص هاتف واجهة شاشتي.ص --آيفون" << std::endl;
            os << std::endl;
            os << "  " << colors::GREEN << "# معلومات النظام" << colors::RESET << std::endl;
            os << "  ص هاتف معلومات" << std::endl;
            os << std::endl;
        }

        // ==============================================================================
        // تنفيذ CommandManager
        // ==============================================================================

        CommandManager::CommandManager()
        {
            register_default_commands();
        }

        void CommandManager::register_default_commands()
        {
            // تسجيل جميع الأوامر الافتراضية
            register_command(std::make_shared<BuildCommand>());
            register_command(std::make_shared<RunCommand>());
            register_command(std::make_shared<TestCommand>());
            register_command(std::make_shared<FormatCommand>());     // 📝 أمر التنسيق
            register_command(std::make_shared<NewProjectCommand>()); // 📁 أمر مشروع جديد
            register_command(std::make_shared<MobileCommand>());     // 📱 أمر الهاتف

            auto help_cmd = std::make_shared<HelpCommand>();
            register_command(help_cmd);

            register_command(std::make_shared<VersionCommand>());

            // تعيين مرجع الأوامر لأمر المساعدة
            help_cmd->set_commands(commands_);
        }

        void CommandManager::register_command(std::shared_ptr<Command> cmd)
        {
            std::string name = cmd->get_name();
            std::string arabic_name = cmd->get_arabic_name();

            commands_[name] = cmd;
            arabic_to_english_[arabic_name] = name;
        }

        std::shared_ptr<Command> CommandManager::get_command(const std::string &name) const
        {
            // البحث بالاسم الإنجليزي
            auto it = commands_.find(name);
            if (it != commands_.end())
            {
                return it->second;
            }

            // البحث بالاسم العربي
            auto ar_it = arabic_to_english_.find(name);
            if (ar_it != arabic_to_english_.end())
            {
                return commands_.at(ar_it->second);
            }

            return nullptr;
        }

        int CommandManager::run(int argc, char *argv[])
        {
            // التحقق من دعم الألوان وتفعيلها
            if (!colors::is_supported())
            {
                colors::disable();
            }

            // إذا لم تُعطَ وسائط، عرض المساعدة
            if (argc < 2)
            {
                auto help = get_command("help");
                if (help)
                {
                    return help->execute({});
                }
                return 1;
            }

            // الحصول على اسم الأمر
            std::string cmd_name = argv[1];

            // التعامل مع خيارات المساعدة والإصدار السريعة
            if (cmd_name == "--help" || cmd_name == "-h" || cmd_name == "--مساعدة")
            {
                auto help = get_command("help");
                return help ? help->execute({}) : 1;
            }

            if (cmd_name == "--version" || cmd_name == "-V" || cmd_name == "--نسخة")
            {
                auto version = get_command("version");
                return version ? version->execute({}) : 1;
            }

            // البحث عن الأمر
            auto cmd = get_command(cmd_name);
            if (!cmd)
            {
                std::cerr << colors::RED;
                std::cerr << "أمر غير معروف: " << cmd_name << std::endl;
                std::cerr << "Unknown command: " << cmd_name << std::endl;
                std::cerr << colors::RESET;
                std::cerr << std::endl;
                std::cerr << "استخدم 'ص مساعدة' لعرض الأوامر المتاحة" << std::endl;
                std::cerr << "Use 'sad help' to see available commands" << std::endl;
                return 1;
            }

            // تحليل الخيارات
            ParsedOptions options = parse_args(argc - 2, argv + 2, cmd.get());

            // التحقق من أخطاء التحليل
            if (!options.errors.empty())
            {
                for (const auto &error : options.errors)
                {
                    std::cerr << colors::RED << symbols::FAILURE << " " << error << colors::RESET << std::endl;
                }
                return 1;
            }

            // تنفيذ الأمر
            return cmd->execute(options);
        }

        ParsedOptions CommandManager::parse_args(int argc, char *argv[], const Command *cmd) const
        {
            ParsedOptions result;

            auto cmd_options = cmd->get_options();

            for (int i = 0; i < argc; ++i)
            {
                std::string arg = argv[i];

                // التحقق مما إذا كان خياراً
                if (arg.length() > 1 && arg[0] == '-')
                {
                    bool found = false;

                    for (const auto &opt : cmd_options)
                    {
                        if (arg == opt.short_name || arg == opt.long_name || arg == opt.arabic_name)
                        {
                            found = true;

                            // اسم الخيار الموحد (بدون الشرطات)
                            std::string opt_name = opt.long_name;
                            if (opt_name.length() > 2 && opt_name[0] == '-' && opt_name[1] == '-')
                            {
                                opt_name = opt_name.substr(2);
                            }

                            if (opt.requires_value)
                            {
                                if (i + 1 < argc)
                                {
                                    result.options[opt_name] = argv[++i];
                                }
                                else
                                {
                                    result.errors.push_back("الخيار " + arg + " يتطلب قيمة");
                                }
                            }
                            else
                            {
                                result.options[opt_name] = "true";
                            }
                            break;
                        }
                    }

                    // التعامل مع خيارات = مثل --output=file
                    if (!found && arg.find('=') != std::string::npos)
                    {
                        auto pos = arg.find('=');
                        std::string opt_part = arg.substr(0, pos);
                        std::string val_part = arg.substr(pos + 1);

                        for (const auto &opt : cmd_options)
                        {
                            if (opt_part == opt.long_name || opt_part == opt.arabic_name)
                            {
                                std::string opt_name = opt.long_name;
                                if (opt_name.length() > 2)
                                    opt_name = opt_name.substr(2);
                                result.options[opt_name] = val_part;
                                found = true;
                                break;
                            }
                        }
                    }

                    if (!found)
                    {
                        result.errors.push_back("خيار غير معروف: " + arg);
                    }
                }
                else
                {
                    // وسيط موضعي
                    result.positional_args.push_back(arg);
                }
            }

            return result;
        }

        void CommandManager::print_banner(std::ostream &os) const
        {
            os << colors::CYAN << colors::BOLD;
            os << R"(
      ___           ___           ___     
     /\__\         /\  \         /\  \    
    /:/ _/_       /::\  \       /::\  \   
   /:/ /\  \     /:/\:\  \     /:/\:\  \  
  /:/ /::\  \   /:/ /::\  \   /:/  \:\__\ 
 /:/_/:/\:\__\ /:/_/:/\:\__\ /:/__/ \:|__|
 \:\/:/ /:/  / \:\/:/  \/__/ \:\  \ /:/  /
  \::/ /:/  /   \::/__/       \:\  /:/  / 
   \/_/:/  /     \:\  \        \:\/:/  /  
     /:/  /       \:\__\        \::/__/   
     \/__/         \/__/         ~~       
    )" << colors::RESET
               << std::endl;
        }

        // ==============================================================================
        // (AR) التنفيذ الحقيقي للأوامر موجود في الملفات التالية:
        //   - build_command.cpp → BuildCommand::execute(), get_options(), print_examples()
        //   - run_command.cpp   → RunCommand::execute(), get_options(), print_examples()
        //   - test_command.cpp  → TestCommand::execute(), get_options(), print_examples()
        //   - formatter.cpp     → formatter_main()
        //
        // (EN) Real command implementations are in their respective files.
        // ==============================================================================

        // ==============================================================================
        // FormatCommand - أمر التنسيق
        // ==============================================================================

        // Forward declaration of formatter_main from formatter.cpp (in ::sad::formatter namespace)

    } // temporarily close cli namespace
} // temporarily close sad namespace

namespace sad
{
    namespace formatter
    {
        // (AR) إعادة توجيه إلى Sad::Format::formatter_main
        // (EN) Forward to Sad::Format::formatter_main
        int formatter_main(int argc, char *argv[]);
    }
}

// (AR) التنفيذ الحقيقي: يستدعي الدالة من فضاء Sad::Format
// (EN) Real implementation: calls the function from Sad::Format namespace
namespace Sad
{
    namespace Format
    {
        int formatter_main(int argc, char *argv[]);
    }
}
int sad::formatter::formatter_main(int argc, char *argv[])
{
    return Sad::Format::formatter_main(argc, argv);
}

namespace sad
{
    namespace cli
    {

        int FormatCommand::execute(const ParsedOptions &options)
        {
            // Build argv for formatter_main
            std::vector<std::string> args_storage;
            args_storage.push_back("sad-fmt");

            // Check for --check flag
            if (options.has("check") || options.has("تحقق"))
            {
                args_storage.push_back("--check");
            }

            // Check for --stdin flag
            if (options.has("stdin"))
            {
                args_storage.push_back("--stdin");
            }

            // Check for --config option
            if (options.has("config"))
            {
                args_storage.push_back("--config");
                args_storage.push_back(options.get("config"));
            }

            // Add positional arguments (files/directories)
            for (const auto &arg : options.positional_args)
            {
                args_storage.push_back(arg);
            }

            if (args_storage.size() < 2)
            {
                print_error_ar("يجب تحديد ملف أو مجلد للتنسيق");
                print_info_ar("استخدم: ص نسّق <ملف.ص> أو ص نسّق <مجلد>");
                return 1;
            }

            // Convert to char* argv
            std::vector<char *> c_args;
            for (auto &s : args_storage)
            {
                c_args.push_back(s.data());
            }

            return ::sad::formatter::formatter_main(static_cast<int>(c_args.size()), c_args.data());
        }

        std::vector<CommandOption> FormatCommand::get_options() const
        {
            return {
                {"", "--check", "--تحقق", "Check formatting without modifying", "التحقق من التنسيق بدون تعديل", false, "", true},
                {"", "--stdin", "", "Read from stdin", "القراءة من stdin", false, "", true},
                {"", "--config", "--إعدادات", "Specify config file", "تحديد ملف إعدادات التنسيق", true, "", false},
            };
        }

        void FormatCommand::print_examples(std::ostream &os) const
        {
            os << "أمثلة:\n";
            os << "  ص نسّق برنامج.ص          # تنسيق ملف\n";
            os << "  ص نسّق src/               # تنسيق مجلد\n";
            os << "  ص نسّق --تحقق برنامج.ص   # التحقق بدون تعديل\n";
            os << "\n";
            os << "Examples:\n";
            os << "  sad format program.ص     # Format a file\n";
            os << "  sad format src/            # Format a directory\n";
            os << "  sad format --check file.ص # Check without modifying\n";
        }

        // NewProjectCommand — أمر إنشاء مشروع جديد (stub حتى يُنقل لملف مستقل)
        int NewProjectCommand::execute(const ParsedOptions &options)
        {
            if (options.positional_args.empty())
            {
                print_error_ar("يجب تحديد اسم المشروع");
                print_info_ar("استخدم: ص جديد <اسم_المشروع>");
                return 1;
            }

            std::string project_name = options.positional_args[0];
            print_info_ar("📁 إنشاء مشروع جديد: " + project_name);

            // إنشاء هيكل المشروع
            namespace fs = std::filesystem;
            fs::path project_dir = fs::current_path() / project_name;

            if (fs::exists(project_dir))
            {
                print_error_ar("المجلد موجود مسبقاً: " + project_name);
                return 1;
            }

            fs::create_directories(project_dir / "src");
            fs::create_directories(project_dir / "tests");

            // إنشاء الملف الرئيسي
            {
                std::ofstream main_file(project_dir / "src" / "main.ص");
                main_file << "# " << project_name << " - مشروع لغة ص\n\n"
                          << "دالة رئيسية()\n"
                          << "    اطبع_سطر(\"مرحباً من " << project_name << "!\")\n"
                          << "نهاية\n";
            }

            // إنشاء ملف اختبار
            {
                std::ofstream test_file(project_dir / "tests" / "test_main.ص");
                test_file << "# اختبارات " << project_name << "\n\n"
                          << "دالة رئيسية()\n"
                          << "    اطبع_سطر(\"الاختبارات...\")\n"
                          << "    اطبع_سطر(\"✅ نجح!\")\n"
                          << "نهاية\n";
            }

            print_success_ar("تم إنشاء المشروع: " + project_name);
            print_info_ar("  ابدأ بـ: cd " + project_name + " && ص شغّل src/main.ص");
            return 0;
        }

        std::vector<CommandOption> NewProjectCommand::get_options() const
        {
            return {
                {"", "--lib", "--مكتبة", "Create library project", "إنشاء مشروع مكتبة", false, "", true},
                {"", "--cli", "--سطر-أوامر", "Create CLI project", "إنشاء مشروع سطر أوامر", false, "", true},
            };
        }

        void NewProjectCommand::print_examples(std::ostream &os) const
        {
            os << "  ص جديد مشروعي          # إنشاء مشروع جديد\n";
            os << "  ص جديد مكتبتي --مكتبة  # إنشاء مشروع مكتبة\n";
            os << "  ص هاتف جديد تطبيقي --اندرويد  # مشروع هاتف\n";
        }

        // ==============================================================================
        // تنفيذ الدوال المساعدة
        // Utility Functions Implementation
        // ==============================================================================

        namespace utils
        {

            bool file_exists(const std::string &path)
            {
                return std::filesystem::exists(path) && std::filesystem::is_regular_file(path);
            }

            bool directory_exists(const std::string &path)
            {
                return std::filesystem::exists(path) && std::filesystem::is_directory(path);
            }

            bool create_directory(const std::string &path)
            {
                try
                {
                    return std::filesystem::create_directories(path);
                }
                catch (...)
                {
                    return false;
                }
            }

            std::optional<std::string> read_file(const std::string &path)
            {
                std::ifstream file(path, std::ios::binary);
                if (!file)
                    return std::nullopt;

                std::ostringstream ss;
                ss << file.rdbuf();
                return ss.str();
            }

            bool write_file(const std::string &path, const std::string &content)
            {
                std::ofstream file(path, std::ios::binary);
                if (!file)
                    return false;

                file << content;
                return file.good();
            }

            std::string get_extension(const std::string &path)
            {
                auto pos = path.rfind('.');
                if (pos == std::string::npos)
                    return "";
                return path.substr(pos);
            }

            std::string change_extension(const std::string &path, const std::string &new_ext)
            {
                auto pos = path.rfind('.');
                if (pos == std::string::npos)
                    return path + new_ext;
                return path.substr(0, pos) + new_ext;
            }

            std::string get_filename(const std::string &path)
            {
                return std::filesystem::path(path).filename().string();
            }

            std::string get_current_directory()
            {
                return std::filesystem::current_path().string();
            }

            std::optional<std::string> find_project_root()
            {
                std::filesystem::path current = std::filesystem::current_path();

                while (true)
                {
                    // البحث عن ص.toml أو sad.toml
                    if (std::filesystem::exists(current / "ص.toml") ||
                        std::filesystem::exists(current / "sad.toml"))
                    {
                        return current.string();
                    }

                    // الصعود للمجلد الأب
                    auto parent = current.parent_path();
                    if (parent == current)
                        break; // وصلنا للجذر
                    current = parent;
                }

                return std::nullopt;
            }

            std::string to_lower(const std::string &str)
            {
                std::string result = str;
                std::transform(result.begin(), result.end(), result.begin(),
                               [](unsigned char c)
                               { return std::tolower(c); });
                return result;
            }

            std::vector<std::string> split(const std::string &str, char delimiter)
            {
                std::vector<std::string> parts;
                std::istringstream ss(str);
                std::string part;
                while (std::getline(ss, part, delimiter))
                {
                    parts.push_back(part);
                }
                return parts;
            }

            std::string join(const std::vector<std::string> &parts, const std::string &delimiter)
            {
                std::string result;
                for (size_t i = 0; i < parts.size(); ++i)
                {
                    if (i > 0)
                        result += delimiter;
                    result += parts[i];
                }
                return result;
            }

            std::optional<std::filesystem::file_time_type> get_modification_time(const std::string &path)
            {
                try
                {
                    return std::filesystem::last_write_time(path);
                }
                catch (...)
                {
                    return std::nullopt;
                }
            }

        } // namespace utils

    } // namespace cli
} // namespace sad

// ==============================================================================
// نقطة الدخول الرئيسية
// Main Entry Point
// ==============================================================================

#ifdef SAD_CLI_MAIN

int main(int argc, char *argv[])
{
#ifdef _WIN32
    // تفعيل دعم Unicode على ويندوز
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);

    // تفعيل وضع ANSI للألوان
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    if (hOut != INVALID_HANDLE_VALUE)
    {
        DWORD dwMode = 0;
        if (GetConsoleMode(hOut, &dwMode))
        {
            dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
            SetConsoleMode(hOut, dwMode);
        }
    }
#endif

    // تعيين الموقع للدعم العربي
    std::setlocale(LC_ALL, "");

    // (AR) ربط argv بـUTF-8 لدعم الأسماء/المسارات العربية على ويندوز
    Sad::Utils::Utf8ArgvHolder _argvHolder(argc, argv);

    // إنشاء مدير الأوامر وتشغيله
    sad::cli::CommandManager manager;
    return manager.run(argc, argv);
}

#endif // SAD_CLI_MAIN
