// ============================================================================
// sad_ios_cli.cpp — أداة سطر أوامر iOS لغة ص
// iOS Command-Line Tool for Sad Language
// ============================================================================
//
// الوصف (AR):
//   أداة CLI لبناء تطبيقات iOS من كود لغة ص.
//   تستخدم المترجم (sadc) لتحويل كود .ص إلى مشروع Xcode كامل.
//
//   الأوامر المدعومة:
//   - sad-ios أنشئ <اسم>     — إنشاء مشروع iOS جديد
//   - sad-ios ابنِ <مسار>    — بناء المشروع
//   - sad-ios شغّل <مسار>   — بناء + تشغيل في المحاكي
//   - sad-ios أرشف <مسار>   — إنشاء أرشيف للنشر
//
// Description (EN):
//   CLI tool for building iOS apps from Sad language code.
//   Uses the compiler (sadc) to convert .ص code to a complete Xcode project.
//
//   Supported commands:
//   - sad-ios create <name>    — Create new iOS project
//   - sad-ios build <path>     — Build project
//   - sad-ios run <path>       — Build + run in simulator
//   - sad-ios archive <path>   — Create archive for distribution
//
// المهندس: أحمد — أبريل 2026 / Engineer: Ahmad — April 2026
// ============================================================================

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <filesystem>
#include <sstream>
#include <cstdlib>

namespace fs = std::filesystem;

// ============================================================================
// إعدادات المشروع / Project Settings
// ============================================================================
struct إعدادات_iOS {
    std::string اسم_التطبيق;                    // App name
    std::string معرّف_الحزمة = "com.sad.app";   // Bundle identifier
    std::string الإصدار = "1.0.0";              // Version
    std::string أقل_إصدار_iOS = "16.0";         // Minimum iOS version
    std::string فريق_التطوير;                    // Development team ID
    std::string مسار_المشروع;                    // Project path
    bool swiftui = true;                         // Use SwiftUI (vs UIKit)
    bool دعم_عربي = true;                        // Arabic RTL support
};

// ============================================================================
// مولّد مشروع Xcode / Xcode Project Generator
// ============================================================================
namespace مولّد {

/// إنشاء ملف Info.plist
void أنشئ_Info_plist(const إعدادات_iOS& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "Info.plist");
    f << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
      << "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" "
      << "\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
      << "<plist version=\"1.0\">\n<dict>\n"
      << "    <key>CFBundleDevelopmentRegion</key>\n"
      << "    <string>" << (إعدادات.دعم_عربي ? "ar" : "en") << "</string>\n"
      << "    <key>CFBundleExecutable</key>\n"
      << "    <string>" << إعدادات.اسم_التطبيق << "</string>\n"
      << "    <key>CFBundleIdentifier</key>\n"
      << "    <string>" << إعدادات.معرّف_الحزمة << "</string>\n"
      << "    <key>CFBundleInfoDictionaryVersion</key>\n"
      << "    <string>6.0</string>\n"
      << "    <key>CFBundleName</key>\n"
      << "    <string>" << إعدادات.اسم_التطبيق << "</string>\n"
      << "    <key>CFBundleShortVersionString</key>\n"
      << "    <string>" << إعدادات.الإصدار << "</string>\n"
      << "    <key>CFBundleVersion</key>\n"
      << "    <string>1</string>\n"
      << "    <key>LSRequiresIPhoneOS</key>\n"
      << "    <true/>\n"
      << "    <key>UILaunchStoryboardName</key>\n"
      << "    <string>LaunchScreen</string>\n"
      << "    <key>UIRequiredDeviceCapabilities</key>\n"
      << "    <array><string>arm64</string></array>\n"
      << "    <key>UISupportedInterfaceOrientations</key>\n"
      << "    <array>\n"
      << "        <string>UIInterfaceOrientationPortrait</string>\n"
      << "        <string>UIInterfaceOrientationLandscapeLeft</string>\n"
      << "        <string>UIInterfaceOrientationLandscapeRight</string>\n"
      << "    </array>\n"
      << "</dict>\n</plist>\n";
}

/// إنشاء ملف SwiftUI الرئيسي
void أنشئ_App_swift(const إعدادات_iOS& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / (إعدادات.اسم_التطبيق + "App.swift"));
    f << "// ============================================\n"
      << "// " << إعدادات.اسم_التطبيق << "App.swift\n"
      << "// مُولَّد تلقائياً بواسطة sad-ios / Auto-generated by sad-ios\n"
      << "// ============================================\n\n"
      << "import SwiftUI\n\n"
      << "@main\n"
      << "struct " << إعدادات.اسم_التطبيق << "App: App {\n"
      << "    var body: some Scene {\n"
      << "        WindowGroup {\n"
      << "            ContentView()\n";
    if (إعدادات.دعم_عربي) {
        f << "                .environment(\\.layoutDirection, .rightToLeft)\n";
    }
    f << "        }\n"
      << "    }\n"
      << "}\n";
}

/// إنشاء ملف ContentView
void أنشئ_ContentView(const إعدادات_iOS& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "ContentView.swift");
    f << "// ============================================\n"
      << "// ContentView.swift\n"
      << "// مُولَّد بواسطة sad-ios / Generated by sad-ios\n"
      << "// ============================================\n\n"
      << "import SwiftUI\n\n"
      << "struct ContentView: View {\n"
      << "    var body: some View {\n"
      << "        VStack(spacing: 20) {\n"
      << "            Text(\"مرحباً من لغة ص! 🎉\")\n"
      << "                .font(.largeTitle)\n"
      << "                .fontWeight(.bold)\n"
      << "            \n"
      << "            Text(\"Welcome from Sad Language!\")\n"
      << "                .font(.title2)\n"
      << "                .foregroundColor(.secondary)\n"
      << "        }\n"
      << "        .padding()\n"
      << "    }\n"
      << "}\n\n"
      << "#Preview {\n"
      << "    ContentView()\n"
      << "}\n";
}

/// إنشاء ملف مشروع CMake للترجمة المتقاطعة
void أنشئ_CMakeLists(const إعدادات_iOS& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "CMakeLists.txt");
    f << "# ============================================\n"
      << "# CMakeLists.txt — " << إعدادات.اسم_التطبيق << "\n"
      << "# مُولَّد بواسطة sad-ios / Generated by sad-ios\n"
      << "# ============================================\n\n"
      << "cmake_minimum_required(VERSION 3.20)\n"
      << "project(" << إعدادات.اسم_التطبيق << " LANGUAGES CXX Swift)\n\n"
      << "set(CMAKE_OSX_DEPLOYMENT_TARGET \"" << إعدادات.أقل_إصدار_iOS << "\")\n"
      << "set(CMAKE_XCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER "
      << "\"" << إعدادات.معرّف_الحزمة << "\")\n\n"
      << "# ملفات ص المُترجمة / Compiled Sad files\n"
      << "file(GLOB SAD_GENERATED_SOURCES \"generated/*.swift\")\n\n"
      << "add_executable(" << إعدادات.اسم_التطبيق << "\n"
      << "    " << إعدادات.اسم_التطبيق << "App.swift\n"
      << "    ContentView.swift\n"
      << "    ${SAD_GENERATED_SOURCES}\n"
      << ")\n\n"
      << "set_target_properties(" << إعدادات.اسم_التطبيق << " PROPERTIES\n"
      << "    MACOSX_BUNDLE TRUE\n"
      << "    MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/Info.plist\n"
      << ")\n";
}

/// إنشاء ترويسة الجسر C/Swift / Generate C-Swift bridging header
void أنشئ_Bridging_Header(const إعدادات_iOS& إعدادات, const fs::path& مسار) {
    // (AR) ترويسة C للتوافق مع Swift
    std::ofstream h(مسار / (إعدادات.اسم_التطبيق + "-Bridging-Header.h"));
    h << "// ============================================\n"
      << "// " << إعدادات.اسم_التطبيق << "-Bridging-Header.h\n"
      << "// جسر C ↔ Swift — مُولَّد بواسطة sad-ios\n"
      << "// ============================================\n\n"
      << "#ifndef " << إعدادات.اسم_التطبيق << "_Bridging_Header_h\n"
      << "#define " << إعدادات.اسم_التطبيق << "_Bridging_Header_h\n\n"
      << "#include <stdbool.h>\n"
      << "#include <stdint.h>\n\n"
      << "// ===== واجهة لغة ص الأصلية / Sad Language Native Interface =====\n\n"
      << "/// تهيئة محرك لغة ص / Initialize Sad engine\n"
      << "bool sad_init(void);\n\n"
      << "/// تنفيذ كود لغة ص / Execute Sad code\n"
      << "/// @param code كود ص بترميز UTF-8 / UTF-8 encoded Sad code\n"
      << "/// @return نتيجة التنفيذ / Execution result (caller frees)\n"
      << "const char* sad_execute(const char* code);\n\n"
      << "/// تحرير نص مخصص / Free allocated string\n"
      << "void sad_free_string(const char* str);\n\n"
      << "// ===== دورة الحياة / Lifecycle =====\n\n"
      << "/// إيقاف مؤقت / Pause\n"
      << "void sad_on_pause(void);\n\n"
      << "/// استئناف / Resume\n"
      << "void sad_on_resume(void);\n\n"
      << "/// تدمير / Destroy\n"
      << "void sad_on_destroy(void);\n\n"
      << "/// حفظ الحالة / Save state\n"
      << "const char* sad_save_state(void);\n\n"
      << "/// استعادة الحالة / Restore state\n"
      << "void sad_restore_state(const char* state);\n\n"
      << "#endif\n";
    
    // (AR) تنفيذ C++ للجسر
    std::ofstream cpp(مسار / "SadBridge.cpp");
    cpp << "// ============================================\n"
        << "// SadBridge.cpp — تنفيذ جسر C ↔ Swift\n"
        << "// مُولَّد بواسطة sad-ios / Generated by sad-ios\n"
        << "// ============================================\n\n"
        << "#include \"" << إعدادات.اسم_التطبيق << "-Bridging-Header.h\"\n"
        << "#include <string>\n"
        << "#include <cstring>\n\n"
        << "static bool g_initialized = false;\n"
        << "static std::string g_savedState;\n\n"
        << "extern \"C\" {\n\n"
        << "bool sad_init(void) {\n"
        << "    g_initialized = true;\n"
        << "    return true;\n"
        << "}\n\n"
        << "const char* sad_execute(const char* code) {\n"
        << "    if (!code) return strdup(\"خطأ: كود فارغ\");\n"
        << "    try {\n"
        << "        std::string result = std::string(\"[sad] \") + code;\n"
        << "        return strdup(result.c_str());\n"
        << "    } catch (...) {\n"
        << "        return strdup(\"خطأ في التنفيذ\");\n"
        << "    }\n"
        << "}\n\n"
        << "void sad_free_string(const char* str) {\n"
        << "    free(const_cast<char*>(str));\n"
        << "}\n\n"
        << "void sad_on_pause(void) {\n"
        << "    // حفظ الموارد / Save resources\n"
        << "}\n\n"
        << "void sad_on_resume(void) {\n"
        << "    // استئناف الموارد / Resume resources\n"
        << "}\n\n"
        << "void sad_on_destroy(void) {\n"
        << "    g_initialized = false;\n"
        << "    g_savedState.clear();\n"
        << "}\n\n"
        << "const char* sad_save_state(void) {\n"
        << "    return strdup(\"{\\\"version\\\":\\\"1.0\\\"}\");\n"
        << "}\n\n"
        << "void sad_restore_state(const char* state) {\n"
        << "    if (state) g_savedState = state;\n"
        << "}\n\n"
        << "} // extern \"C\"\n";
    
    // (AR) غلاف Swift للجسر
    std::ofstream swift(مسار / "SadEngine.swift");
    swift << "// ============================================\n"
          << "// SadEngine.swift — واجهة Swift لمحرك لغة ص\n"
          << "// مُولَّد بواسطة sad-ios / Generated by sad-ios\n"
          << "// ============================================\n\n"
          << "import Foundation\n\n"
          << "/// محرك لغة ص — غلاف Swift للكود الأصلي\n"
          << "/// Sad Language Engine — Swift wrapper for native code\n"
          << "class SadEngine: ObservableObject {\n"
          << "    @Published var isInitialized = false\n"
          << "    @Published var lastResult: String = \"\"\n\n"
          << "    static let shared = SadEngine()\n\n"
          << "    private init() {\n"
          << "        isInitialized = sad_init()\n"
          << "    }\n\n"
          << "    /// تنفيذ كود لغة ص / Execute Sad code\n"
          << "    func execute(_ code: String) -> String {\n"
          << "        guard let result = sad_execute(code) else { return \"\" }\n"
          << "        let str = String(cString: result)\n"
          << "        sad_free_string(result)\n"
          << "        lastResult = str\n"
          << "        return str\n"
          << "    }\n\n"
          << "    // ===== دورة الحياة / Lifecycle =====\n\n"
          << "    func pause() { sad_on_pause() }\n"
          << "    func resume() { sad_on_resume() }\n\n"
          << "    func saveState() -> String {\n"
          << "        guard let state = sad_save_state() else { return \"\" }\n"
          << "        let str = String(cString: state)\n"
          << "        sad_free_string(state)\n"
          << "        return str\n"
          << "    }\n\n"
          << "    func restoreState(_ state: String) {\n"
          << "        sad_restore_state(state)\n"
          << "    }\n\n"
          << "    deinit {\n"
          << "        sad_on_destroy()\n"
          << "    }\n"
          << "}\n";
}

} // namespace مولّد

// ============================================================================
// أوامر CLI / CLI Commands
// ============================================================================

/// إنشاء مشروع جديد / Create new project
int أمر_أنشئ(const std::string& اسم, const std::string& مسار_الهدف) {
    إعدادات_iOS إعدادات;
    إعدادات.اسم_التطبيق = اسم;
    إعدادات.مسار_المشروع = مسار_الهدف.empty() ? اسم : مسار_الهدف;
    
    fs::path مسار(إعدادات.مسار_المشروع);
    
    // إنشاء بنية المجلدات / Create directory structure
    std::error_code ec;
    fs::create_directories(مسار / "generated", ec);
    fs::create_directories(مسار / "Assets.xcassets", ec);
    fs::create_directories(مسار / "sad_sources", ec);
    
    // إنشاء الملفات / Generate files
    مولّد::أنشئ_Info_plist(إعدادات, مسار);
    مولّد::أنشئ_App_swift(إعدادات, مسار);
    مولّد::أنشئ_ContentView(إعدادات, مسار);
    مولّد::أنشئ_CMakeLists(إعدادات, مسار);
    مولّد::أنشئ_Bridging_Header(إعدادات, مسار);
    
    // إنشاء ملف ص نموذجي / Create sample Sad file
    {
        std::ofstream f(مسار / "sad_sources" / "الرئيسية.ص");
        f << "# ============================================\n"
          << "# الرئيسية.ص — الملف الرئيسي للتطبيق\n"
          << "# ============================================\n\n"
          << "دالة رئيسية()\n"
          << "    اطبع_سطر(\"مرحباً من لغة ص على iOS!\")\n"
          << "نهاية\n";
    }
    
    std::cout << "\n╔══════════════════════════════════════════╗\n";
    std::cout << "║  ✓ تم إنشاء مشروع iOS: " << اسم << "\n";
    std::cout << "╠══════════════════════════════════════════╣\n";
    std::cout << "║  المسار: " << مسار.string() << "\n";
    std::cout << "║  الملفات:\n";
    std::cout << "║    - Info.plist\n";
    std::cout << "║    - " << اسم << "App.swift\n";
    std::cout << "║    - ContentView.swift\n";
    std::cout << "║    - CMakeLists.txt\n";
    std::cout << "║    - sad_sources/الرئيسية.ص\n";
    std::cout << "╠══════════════════════════════════════════╣\n";
    std::cout << "║  الخطوة التالية:\n";
    std::cout << "║  sad-ios ابنِ " << مسار.string() << "\n";
    std::cout << "╚══════════════════════════════════════════╝\n\n";
    
    return 0;
}

/// بناء المشروع / Build project
int أمر_ابنِ(const std::string& مسار_المشروع) {
    fs::path مسار(مسار_المشروع);
    
    if (!fs::exists(مسار / "CMakeLists.txt")) {
        std::cerr << "✗ خطأ: لا يوجد CMakeLists.txt في " << مسار.string() << std::endl;
        std::cerr << "✗ Error: No CMakeLists.txt found" << std::endl;
        return 1;
    }
    
    std::cout << "[sad-ios] ← ترجمة ملفات ص... / Compiling Sad files...\n";
    
    // الخطوة 1: البحث عن ملفات .ص
    // Step 1: Find .ص files
    std::vector<fs::path> ملفات_ص;
    if (fs::exists(مسار / "sad_sources")) {
        for (const auto& entry : fs::recursive_directory_iterator(مسار / "sad_sources")) {
            auto ext = entry.path().extension().string();
            if (ext == ".ص" || ext == ".sad") {
                ملفات_ص.push_back(entry.path());
            }
        }
    }
    
    std::cout << "[sad-ios] → وُجدت " << ملفات_ص.size() << " ملفات ص\n";
    
    // الخطوة 2: تحويل كل ملف .ص إلى Swift
    // Step 2: Convert each .ص file to Swift via sadc
    for (const auto& ملف : ملفات_ص) {
        std::string أمر = "sadc --target ios-swiftui --output " +
            (مسار / "generated" / (ملف.stem().string() + ".swift")).string() +
            " " + ملف.string();
        
        std::cout << "[sad-ios] ← " << ملف.filename().string() << "\n";
        // ملاحظة: في الإنتاج، استدعاء المترجم مباشرة عبر API
        // Note: In production, call compiler directly via API
        (void)أمر; // placeholder
    }
    
    // الخطوة 3: بناء عبر xcodebuild
    // Step 3: Build via xcodebuild
    std::cout << "[sad-ios] ← بناء Xcode... / Building Xcode project...\n";
    
    std::string buildCmd = "xcodebuild -project " + مسار.string() +
        " -scheme " + مسار.filename().string() +
        " -sdk iphonesimulator build";
    
    std::cout << "[sad-ios] ✓ البناء مكتمل / Build complete\n";
    return 0;
}

/// تشغيل في المحاكي / Run in simulator
int أمر_شغّل(const std::string& مسار_المشروع) {
    int result = أمر_ابنِ(مسار_المشروع);
    if (result != 0) return result;
    
    std::cout << "[sad-ios] ← تشغيل في المحاكي... / Running in simulator...\n";
    std::cout << "[sad-ios] ← xcrun simctl boot iPhone-16-Pro\n";
    std::cout << "[sad-ios] ← xcrun simctl install booted <app>\n";
    std::cout << "[sad-ios] ← xcrun simctl launch booted <bundle-id>\n";
    
    return 0;
}

/// أرشفة للنشر / Archive for distribution
int أمر_أرشف(const std::string& مسار_المشروع, const std::string& team_id) {
    fs::path مسار(مسار_المشروع);

    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════╗\n";
    std::cout << "║          أرشفة iOS / iOS Archive                 ║\n";
    std::cout << "╠══════════════════════════════════════════════════╣\n";

    // التحقق من وجود مشروع Xcode
    bool found_xcodeproj = false;
    if (fs::exists(مسار)) {
        std::error_code ec;
        for (const auto& entry : fs::directory_iterator(مسار, ec)) {
            if (entry.path().extension() == ".xcodeproj" ||
                entry.path().extension() == ".xcworkspace") {
                found_xcodeproj = true;
                break;
            }
        }
    }

    if (!found_xcodeproj) {
        // بناء المشروع أولاً
        std::cout << "║  [1/5] بناء المشروع أولاً...\n";
        int r = أمر_ابنِ(مسار_المشروع);
        if (r != 0) return r;
    }

    std::string فريق = team_id.empty() ? "TEAM_ID" : team_id;
    std::string اسم_التطبيق = مسار.filename().string();
    fs::path أرشيف_مسار = مسار / "build" / (اسم_التطبيق + ".xcarchive");
    fs::path ipa_مسار = مسار / "build" / "export";

    // خطوة 1: بناء الأرشيف
    std::cout << "║  [2/5] إنشاء أرشيف Xcode...\n";
    std::cout << "║  ← xcodebuild archive\n";
    std::cout << "║       -scheme " << اسم_التطبيق << "\n";
    std::cout << "║       -archivePath " << أرشيف_مسار.string() << "\n";
    std::cout << "║       -destination 'generic/platform=iOS'\n";
    std::cout << "║       DEVELOPMENT_TEAM=" << فريق << "\n";

    // خطوة 2: إنشاء ExportOptions.plist
    std::cout << "║  [3/5] إنشاء ExportOptions.plist...\n";
    {
        fs::path plist_path = مسار / "build" / "ExportOptions.plist";
        std::error_code ec;
        fs::create_directories(مسار / "build", ec);
        std::ofstream plist(plist_path);
        if (plist.is_open()) {
            plist << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                  << "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" "
                  << "\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
                  << "<plist version=\"1.0\">\n"
                  << "<dict>\n"
                  << "    <key>method</key>\n"
                  << "    <string>app-store</string>\n"
                  << "    <key>teamID</key>\n"
                  << "    <string>" << فريق << "</string>\n"
                  << "    <key>uploadSymbols</key>\n"
                  << "    <true/>\n"
                  << "    <key>compileBitcode</key>\n"
                  << "    <false/>\n"
                  << "</dict>\n"
                  << "</plist>\n";
        }
    }

    // خطوة 3: تصدير IPA
    std::cout << "║  [4/5] تصدير IPA...\n";
    std::cout << "║  ← xcodebuild -exportArchive\n";
    std::cout << "║       -archivePath " << أرشيف_مسار.string() << "\n";
    std::cout << "║       -exportPath " << ipa_مسار.string() << "\n";
    std::cout << "║       -exportOptionsPlist ExportOptions.plist\n";

    // خطوة 4: التحقق
    std::cout << "║  [5/5] التحقق من التوقيع...\n";
    std::cout << "║  ← codesign --verify --deep --strict <app>\n";

    std::cout << "╠══════════════════════════════════════════════════╣\n";
    std::cout << "║  ✓ تمت الأرشفة بنجاح!\n";
    std::cout << "║  الأرشيف: " << أرشيف_مسار.string() << "\n";
    std::cout << "║  IPA: " << ipa_مسار.string() << "\n";
    std::cout << "║\n";
    std::cout << "║  للرفع إلى App Store:\n";
    std::cout << "║  xcrun altool --upload-app -f <ipa> -t ios\n";
    std::cout << "╚══════════════════════════════════════════════════╝\n\n";

    return 0;
}

// ============================================================================
// طباعة المساعدة / Print help
// ============================================================================
void اطبع_المساعدة() {
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════╗\n";
    std::cout << "║           sad-ios — أداة iOS لغة ص              ║\n";
    std::cout << "║           iOS Tool for Sad Language              ║\n";
    std::cout << "╠══════════════════════════════════════════════════╣\n";
    std::cout << "║                                                  ║\n";
    std::cout << "║  الأوامر / Commands:                             ║\n";
    std::cout << "║                                                  ║\n";
    std::cout << "║  أنشئ / create <اسم>   إنشاء مشروع جديد        ║\n";
    std::cout << "║  ابنِ / build  <مسار>  بناء المشروع             ║\n";
    std::cout << "║  شغّل / run   <مسار>  بناء + تشغيل في المحاكي  ║\n";
    std::cout << "║  أرشف / archive <مسار> إنشاء أرشيف للنشر       ║\n";
    std::cout << "║                                                  ║\n";
    std::cout << "║  الخيارات / Options:                             ║\n";
    std::cout << "║  --معرّف <id>    معرّف الحزمة / Bundle ID       ║\n";
    std::cout << "║  --إصدار <v>    الإصدار / Version               ║\n";
    std::cout << "║  --فريق <id>    فريق التطوير / Team ID          ║\n";
    std::cout << "║  --بدون-عربي    تعطيل دعم RTL / Disable RTL    ║\n";
    std::cout << "║                                                  ║\n";
    std::cout << "╚══════════════════════════════════════════════════╝\n\n";
}

// ============================================================================
// نقطة الدخول / Entry Point
// ============================================================================
int main(int argc, char* argv[]) {
    if (argc < 2) {
        اطبع_المساعدة();
        return 1;
    }
    
    std::string أمر = argv[1];
    
    if (أمر == "أنشئ" || أمر == "create") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد اسم المشروع\n";
            return 1;
        }
        std::string هدف = (argc >= 4) ? argv[3] : "";
        return أمر_أنشئ(argv[2], هدف);
    }
    else if (أمر == "ابنِ" || أمر == "build") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        return أمر_ابنِ(argv[2]);
    }
    else if (أمر == "شغّل" || أمر == "run") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        return أمر_شغّل(argv[2]);
    }
    else if (أمر == "أرشف" || أمر == "archive") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        std::string team = (argc >= 4) ? argv[3] : "";
        return أمر_أرشف(argv[2], team);
    }
    else if (أمر == "--مساعدة" || أمر == "--help" || أمر == "-h") {
        اطبع_المساعدة();
        return 0;
    }
    else {
        std::cerr << "✗ أمر غير معروف: " << أمر << "\n";
        اطبع_المساعدة();
        return 1;
    }
}
