# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/mnt/c/s_lang/s-programming-language;/mnt/c/s_lang/s-programming-language/build_linux")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "interpreter;compiler;tools;stdlib;docs;examples")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_COMPILER_DESCRIPTION "مترجم LLVM لتوليد ملفات تنفيذية أصلية")
set(CPACK_COMPONENT_COMPILER_DISPLAY_NAME "المترجم / Compiler (sadc)")
set(CPACK_COMPONENT_DOCS_DESCRIPTION "الكتاب التعليمي والمراجع")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME "التوثيق / Documentation")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "برامج .ص نموذجية")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "الأمثلة / Examples")
set(CPACK_COMPONENT_INTERPRETER_DESCRIPTION "المفسر الرئيسي لتشغيل ملفات .ص")
set(CPACK_COMPONENT_INTERPRETER_DISPLAY_NAME "المفسر / Interpreter (sad)")
set(CPACK_COMPONENT_INTERPRETER_REQUIRED "ON")
set(CPACK_COMPONENT_STDLIB_DESCRIPTION "المكتبات العربية: io, math, string, network, graphics")
set(CPACK_COMPONENT_STDLIB_DISPLAY_NAME "المكتبة القياسية / Standard Library")
set(CPACK_COMPONENT_TOOLS_DESCRIPTION "LSP server, formatter, package manager")
set(CPACK_COMPONENT_TOOLS_DISPLAY_NAME "الأدوات / Tools")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.31), libstdc++6 (>= 10)")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://sad-lang.org")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Sad Language Team <team@sad-lang.org>")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "SadLanguage built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/mnt/c/s_lang/s-programming-language;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "لغة ص — Sad Programming Language")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_MUI_ICON "/mnt/c/s_lang/s-programming-language/website/docs/public/sad-icon.ico")
set(CPACK_NSIS_PACKAGE_NAME "Sad Language")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://sad-lang.org")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/mnt/c/s_lang/s-programming-language/build_linux/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "team@sad-lang.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "لغة ص — لغة برمجة عربية حديثة / Sad — Modern Arabic Programming Language")
set(CPACK_PACKAGE_FILE_NAME "sad-lang-1.0.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://sad-lang.org")
set(CPACK_PACKAGE_ICON "/mnt/c/s_lang/s-programming-language/website/docs/public/sad-icon.png")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "sad-lang 1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "sad-lang 1.0.0")
set(CPACK_PACKAGE_NAME "sad-lang")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Sad Language Team")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/mnt/c/s_lang/s-programming-language/LICENSE")
set(CPACK_RESOURCE_FILE_README "/mnt/c/s_lang/s-programming-language/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Languages")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_REQUIRES "glibc >= 2.31, libstdc++ >= 10")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_URL "https://sad-lang.org")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/mnt/c/s_lang/s-programming-language;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/mnt/c/s_lang/s-programming-language/build_linux/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "sad-lang-1.0.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/mnt/c/s_lang/s-programming-language/build_linux/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
