// ============================================================================
// sad_android.cpp — أداة سطر أوامر Android لغة ص
// Android Command-Line Tool for Sad Language
// ============================================================================
//
// الوصف (AR):
//   أداة CLI لبناء تطبيقات Android من كود لغة ص.
//   تدعم إنشاء المشروع، البناء، التشغيل، والتوزيع.
//
//   الأوامر المدعومة:
//   - sad-android أنشئ <اسم>        — إنشاء مشروع Android جديد
//   - sad-android ابنِ <مسار>       — بناء APK
//   - sad-android شغّل <مسار>      — بناء + تشغيل في المحاكي
//   - sad-android وقّع <مسار>      — توقيع APK للنشر
//
// Description (EN):
//   CLI tool for building Android apps from Sad language code.
//   Supports project creation, building, running, and distribution.
//
// المهندس: سعيد — أبريل 2026 / Engineer: Saeed — April 2026
// ============================================================================

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <filesystem>
#include <sstream>

namespace fs = std::filesystem;

// ============================================================================
// إعدادات المشروع / Project Settings
// ============================================================================
struct إعدادات_Android {
    std::string اسم_التطبيق;                               // App name
    std::string معرّف_الحزمة = "com.sad.app";              // Package name
    std::string الإصدار = "1.0.0";                         // Version
    int أقل_إصدار_SDK = 21;                                // Min SDK
    int إصدار_SDK_المستهدف = 34;                           // Target SDK
    std::string مسار_المشروع;                               // Project path
    bool دعم_عربي = true;                                   // Arabic RTL support
    bool jetpack_compose = true;                            // Use Jetpack Compose
    std::string وضع_التطبيق = "واجهة";                     // App mode: واجهة/بسيط
};

// ============================================================================
// مولّد المشروع / Project Generator
// ============================================================================
namespace مولّد_أندرويد {

/// إنشاء build.gradle.kts للمشروع الجذري
void أنشئ_build_gradle_root(const إعدادات_Android& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "build.gradle.kts");
    f << "// مُولَّد تلقائياً بواسطة sad-android / Auto-generated by sad-android\n"
      << "plugins {\n"
      << "    id(\"com.android.application\") version \"8.2.0\" apply false\n"
      << "    id(\"org.jetbrains.kotlin.android\") version \"1.9.20\" apply false\n"
      << "}\n";
}

/// إنشاء build.gradle.kts للتطبيق
void أنشئ_build_gradle_app(const إعدادات_Android& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "app" / "build.gradle.kts");
    f << "// مُولَّد تلقائياً بواسطة sad-android\n"
      << "plugins {\n"
      << "    id(\"com.android.application\")\n"
      << "    id(\"org.jetbrains.kotlin.android\")\n"
      << "}\n\n"
      << "android {\n"
      << "    namespace = \"" << إعدادات.معرّف_الحزمة << "\"\n"
      << "    compileSdk = " << إعدادات.إصدار_SDK_المستهدف << "\n\n"
      << "    defaultConfig {\n"
      << "        applicationId = \"" << إعدادات.معرّف_الحزمة << "\"\n"
      << "        minSdk = " << إعدادات.أقل_إصدار_SDK << "\n"
      << "        targetSdk = " << إعدادات.إصدار_SDK_المستهدف << "\n"
      << "        versionCode = 1\n"
      << "        versionName = \"" << إعدادات.الإصدار << "\"\n\n"
      << "        // إعدادات NDK / NDK configuration\n"
      << "        ndk {\n"
      << "            abiFilters += listOf(\"arm64-v8a\", \"armeabi-v7a\", \"x86_64\")\n"
      << "        }\n\n"
      << "        externalNativeBuild {\n"
      << "            cmake {\n"
      << "                cppFlags += \"-std=c++17\"\n"
      << "                arguments += listOf(\n"
      << "                    \"-DANDROID_STL=c++_shared\",\n"
      << "                    \"-DANDROID_TOOLCHAIN=clang\"\n"
      << "                )\n"
      << "            }\n"
      << "        }\n"
      << "    }\n\n"
      << "    buildFeatures {\n"
      << "        compose = true\n"
      << "    }\n\n"
      << "    composeOptions {\n"
      << "        kotlinCompilerExtensionVersion = \"1.5.4\"\n"
      << "    }\n\n"
      << "    // دعم الكود الأصلي (Native) / Native code support\n"
      << "    externalNativeBuild {\n"
      << "        cmake {\n"
      << "            path = file(\"src/main/cpp/CMakeLists.txt\")\n"
      << "            version = \"3.22.1\"\n"
      << "        }\n"
      << "    }\n"
      << "}\n\n"
      << "dependencies {\n"
      << "    implementation(\"androidx.core:core-ktx:1.12.0\")\n"
      << "    implementation(\"androidx.activity:activity-compose:1.8.0\")\n"
      << "    implementation(\"androidx.lifecycle:lifecycle-runtime-ktx:2.7.0\")\n"
      << "    implementation(\"androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0\")\n"
      << "    implementation(platform(\"androidx.compose:compose-bom:2023.10.01\"))\n"
      << "    implementation(\"androidx.compose.ui:ui\")\n"
      << "    implementation(\"androidx.compose.material3:material3\")\n"
      << "    implementation(\"androidx.compose.ui:ui-tooling-preview\")\n"
      << "}\n";
}

/// إنشاء AndroidManifest.xml
void أنشئ_AndroidManifest(const إعدادات_Android& إعدادات, const fs::path& مسار) {
    std::ofstream f(مسار / "app" / "src" / "main" / "AndroidManifest.xml");
    f << "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
      << "<!-- مُولَّد بواسطة sad-android -->\n"
      << "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n\n"
      << "    <application\n"
      << "        android:allowBackup=\"true\"\n"
      << "        android:label=\"" << إعدادات.اسم_التطبيق << "\"\n"
      << "        android:supportsRtl=\"" << (إعدادات.دعم_عربي ? "true" : "false") << "\"\n"
      << "        android:theme=\"@style/Theme.Material3.DayNight\">\n\n"
      << "        <activity\n"
      << "            android:name=\"." << إعدادات.اسم_التطبيق << "Activity\"\n"
      << "            android:exported=\"true\">\n"
      << "            <intent-filter>\n"
      << "                <action android:name=\"android.intent.action.MAIN\" />\n"
      << "                <category android:name=\"android.intent.category.LAUNCHER\" />\n"
      << "            </intent-filter>\n"
      << "        </activity>\n\n"
      << "    </application>\n"
      << "</manifest>\n";
}

/// إنشاء ملف Activity الرئيسي (Kotlin + Compose)
void أنشئ_MainActivity(const إعدادات_Android& إعدادات, const fs::path& مسار) {
    // تحويل معرّف الحزمة إلى مسار مجلد
    std::string pkgPath = إعدادات.معرّف_الحزمة;
    for (char& c : pkgPath) if (c == '.') c = '/';
    
    fs::path kotlinDir = مسار / "app" / "src" / "main" / "java" / pkgPath;
    std::error_code ec;
    fs::create_directories(kotlinDir, ec);
    
    std::ofstream f(kotlinDir / (إعدادات.اسم_التطبيق + "Activity.kt"));
    f << "// مُولَّد تلقائياً بواسطة sad-android / Auto-generated\n"
      << "package " << إعدادات.معرّف_الحزمة << "\n\n"
      << "import android.os.Bundle\n"
      << "import android.util.Log\n"
      << "import androidx.activity.ComponentActivity\n"
      << "import androidx.activity.compose.setContent\n"
      << "import androidx.compose.foundation.layout.*\n"
      << "import androidx.compose.material3.*\n"
      << "import androidx.compose.runtime.*\n"
      << "import androidx.compose.ui.Alignment\n"
      << "import androidx.compose.ui.Modifier\n"
      << "import androidx.compose.ui.unit.dp\n"
      << "import androidx.compose.ui.unit.sp\n\n"
      << "class " << إعدادات.اسم_التطبيق << "Activity : ComponentActivity() {\n\n"
      << "    private val TAG = \"SadApp\"\n\n"
      << "    // تحميل المكتبة الأصلية / Load native library\n"
      << "    companion object {\n"
      << "        init {\n"
      << "            System.loadLibrary(\"sad_native\")\n"
      << "        }\n"
      << "    }\n\n"
      << "    // دوال JNI الأصلية / Native JNI functions\n"
      << "    external fun sadInit(): Boolean\n"
      << "    external fun sadExecute(code: String): String\n"
      << "    external fun sadOnPause()\n"
      << "    external fun sadOnResume()\n"
      << "    external fun sadOnDestroy()\n"
      << "    external fun sadSaveState(): String\n"
      << "    external fun sadRestoreState(state: String)\n\n"
      << "    override fun onCreate(savedInstanceState: Bundle?) {\n"
      << "        super.onCreate(savedInstanceState)\n"
      << "        Log.i(TAG, \"onCreate — تهيئة لغة ص\")\n"
      << "        sadInit()\n\n"
      << "        // استعادة الحالة المحفوظة / Restore saved state\n"
      << "        savedInstanceState?.getString(\"sad_state\")?.let { state ->\n"
      << "            sadRestoreState(state)\n"
      << "        }\n\n"
      << "        setContent {\n"
      << "            MaterialTheme {\n"
      << "                SadMainScreen()\n"
      << "            }\n"
      << "        }\n"
      << "    }\n\n"
      << "    override fun onResume() {\n"
      << "        super.onResume()\n"
      << "        Log.i(TAG, \"onResume — استئناف\")\n"
      << "        sadOnResume()\n"
      << "    }\n\n"
      << "    override fun onPause() {\n"
      << "        Log.i(TAG, \"onPause — إيقاف مؤقت\")\n"
      << "        sadOnPause()\n"
      << "        super.onPause()\n"
      << "    }\n\n"
      << "    override fun onSaveInstanceState(outState: Bundle) {\n"
      << "        super.onSaveInstanceState(outState)\n"
      << "        val state = sadSaveState()\n"
      << "        outState.putString(\"sad_state\", state)\n"
      << "        Log.i(TAG, \"onSaveInstanceState — حفظ حالة\")\n"
      << "    }\n\n"
      << "    override fun onDestroy() {\n"
      << "        Log.i(TAG, \"onDestroy — تدمير\")\n"
      << "        sadOnDestroy()\n"
      << "        super.onDestroy()\n"
      << "    }\n"
      << "}\n\n"
      << "@Composable\n"
      << "fun SadMainScreen() {\n"
      << "    Column(\n"
      << "        modifier = Modifier.fillMaxSize().padding(24.dp),\n"
      << "        horizontalAlignment = Alignment.CenterHorizontally,\n"
      << "        verticalArrangement = Arrangement.Center\n"
      << "    ) {\n"
      << "        Text(\n"
      << "            text = \"\\u0645\\u0631\\u062d\\u0628\\u0627\\u064b \\u0645\\u0646 \\u0644\\u063a\\u0629 \\u0635! \\uD83C\\uDF89\",\n"
      << "            fontSize = 28.sp\n"
      << "        )\n"
      << "        Spacer(modifier = Modifier.height(16.dp))\n"
      << "        Text(\n"
      << "            text = \"Welcome from Sad Language!\",\n"
      << "            fontSize = 20.sp,\n"
      << "            color = MaterialTheme.colorScheme.secondary\n"
      << "        )\n"
      << "    }\n"
      << "}\n";
}

/// إنشاء CMakeLists.txt للكود الأصلي
void أنشئ_CMakeLists_native(const إعدادات_Android& إعدادات, const fs::path& مسار) {
    fs::path cppDir = مسار / "app" / "src" / "main" / "cpp";
    std::error_code ec;
    fs::create_directories(cppDir, ec);
    
    std::ofstream f(cppDir / "CMakeLists.txt");
    f << "# مُولَّد بواسطة sad-android / Generated by sad-android\n"
      << "cmake_minimum_required(VERSION 3.18)\n"
      << "project(sad_native LANGUAGES CXX)\n\n"
      << "set(CMAKE_CXX_STANDARD 17)\n\n"
      << "# ملفات ص المُترجمة / Compiled Sad files\n"
      << "file(GLOB SAD_GENERATED \"${CMAKE_CURRENT_SOURCE_DIR}/generated/*.cpp\")\n\n"
      << "add_library(sad_native SHARED\n"
      << "    sad_jni.cpp\n"
      << "    ${SAD_GENERATED}\n"
      << ")\n\n"
      << "find_library(log-lib log)\n"
      << "target_link_libraries(sad_native ${log-lib})\n";
    
    // إنشاء ملف JNI أساسي
    std::string jniPkgName = إعدادات.معرّف_الحزمة;
    for (char& c : jniPkgName) { if (c == '.') c = '_'; }
    
    std::ofstream jni(cppDir / "sad_jni.cpp");
    jni << "// مُولَّد بواسطة sad-android / Generated by sad-android\n"
        << "#include <jni.h>\n"
        << "#include <string>\n"
        << "#include <android/log.h>\n\n"
        << "#define LOG_TAG \"SadNative\"\n"
        << "#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)\n"
        << "#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)\n\n"
        << "// حالة التطبيق / Application state\n"
        << "static bool g_initialized = false;\n"
        << "static std::string g_savedState;\n\n"
        << "extern \"C\" {\n\n"
        << "JNIEXPORT jboolean JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadInit(JNIEnv* env, jobject thiz) {\n"
        << "    LOGI(\"Sad runtime initialized — تهيئة لغة ص\");\n"
        << "    g_initialized = true;\n"
        << "    return JNI_TRUE;\n"
        << "}\n\n"
        << "JNIEXPORT jstring JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadExecute(JNIEnv* env, jobject thiz, jstring code) {\n"
        << "    const char* codeStr = env->GetStringUTFChars(code, nullptr);\n"
        << "    LOGI(\"Executing Sad code: %s\", codeStr);\n"
        << "    std::string result;\n"
        << "    try {\n"
        << "        result = std::string(\"[sad] \") + codeStr;\n"
        << "    } catch (...) {\n"
        << "        LOGE(\"Error executing Sad code\");\n"
        << "        result = \"خطأ في التنفيذ\";\n"
        << "    }\n"
        << "    env->ReleaseStringUTFChars(code, codeStr);\n"
        << "    return env->NewStringUTF(result.c_str());\n"
        << "}\n\n"
        << "// ========== دورة حياة النشاط / Activity Lifecycle ==========\n\n"
        << "JNIEXPORT void JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadOnPause(JNIEnv* env, jobject thiz) {\n"
        << "    LOGI(\"Sad onPause — إيقاف مؤقت\");\n"
        << "    // حفظ الموارد، إيقاف المؤقتات / Save resources, stop timers\n"
        << "}\n\n"
        << "JNIEXPORT void JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadOnResume(JNIEnv* env, jobject thiz) {\n"
        << "    LOGI(\"Sad onResume — استئناف\");\n"
        << "    // استئناف الموارد، إعادة تشغيل المؤقتات / Resume resources, restart timers\n"
        << "}\n\n"
        << "JNIEXPORT void JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadOnDestroy(JNIEnv* env, jobject thiz) {\n"
        << "    LOGI(\"Sad onDestroy — تدمير\");\n"
        << "    g_initialized = false;\n"
        << "    g_savedState.clear();\n"
        << "    // تحرير جميع الموارد / Release all resources\n"
        << "}\n\n"
        << "JNIEXPORT jstring JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadSaveState(JNIEnv* env, jobject thiz) {\n"
        << "    LOGI(\"Sad saveState — حفظ الحالة\");\n"
        << "    // تحويل حالة البرنامج إلى نص JSON / Serialize state to JSON\n"
        << "    std::string state = \"{\\\"version\\\":\\\"1.0\\\"}\";\n"
        << "    return env->NewStringUTF(state.c_str());\n"
        << "}\n\n"
        << "JNIEXPORT void JNICALL\n"
        << "Java_" << jniPkgName << "_" << إعدادات.اسم_التطبيق
        << "Activity_sadRestoreState(JNIEnv* env, jobject thiz, jstring state) {\n"
        << "    const char* stateStr = env->GetStringUTFChars(state, nullptr);\n"
        << "    LOGI(\"Sad restoreState — استعادة الحالة: %s\", stateStr);\n"
        << "    g_savedState = stateStr;\n"
        << "    env->ReleaseStringUTFChars(state, stateStr);\n"
        << "}\n\n"
        << "} // extern \"C\"\n";
}

} // namespace مولّد_أندرويد

// ============================================================================
// أوامر CLI / CLI Commands
// ============================================================================

/// إنشاء مشروع جديد
int أمر_أنشئ(const std::string& اسم, const std::string& مسار_الهدف) {
    إعدادات_Android إعدادات;
    إعدادات.اسم_التطبيق = اسم;
    إعدادات.مسار_المشروع = مسار_الهدف.empty() ? اسم : مسار_الهدف;
    
    fs::path مسار(إعدادات.مسار_المشروع);
    std::error_code ec;
    
    // إنشاء بنية المجلدات / Create directory structure
    fs::create_directories(مسار / "app" / "src" / "main" / "res", ec);
    fs::create_directories(مسار / "app" / "src" / "main" / "cpp" / "generated", ec);
    fs::create_directories(مسار / "sad_sources", ec);
    
    // إنشاء الملفات
    مولّد_أندرويد::أنشئ_build_gradle_root(إعدادات, مسار);
    مولّد_أندرويد::أنشئ_build_gradle_app(إعدادات, مسار);
    مولّد_أندرويد::أنشئ_AndroidManifest(إعدادات, مسار);
    مولّد_أندرويد::أنشئ_MainActivity(إعدادات, مسار);
    مولّد_أندرويد::أنشئ_CMakeLists_native(إعدادات, مسار);
    
    // إنشاء ملف ص نموذجي
    {
        std::ofstream f(مسار / "sad_sources" / "الرئيسية.ص");
        f << "# ============================================\n"
          << "# الرئيسية.ص — الملف الرئيسي للتطبيق\n"
          << "# ============================================\n\n"
          << "دالة رئيسية()\n"
          << "    اطبع_سطر(\"مرحباً من لغة ص على أندرويد!\")\n"
          << "نهاية\n";
    }
    
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════╗\n";
    std::cout << "║  ✓ تم إنشاء مشروع Android: " << اسم << "\n";
    std::cout << "╠══════════════════════════════════════════════╣\n";
    std::cout << "║  المسار: " << مسار.string() << "\n";
    std::cout << "╠══════════════════════════════════════════════╣\n";
    std::cout << "║  الخطوة التالية:\n";
    std::cout << "║  sad-android ابنِ " << مسار.string() << "\n";
    std::cout << "╚══════════════════════════════════════════════╝\n\n";
    
    return 0;
}

/// بناء المشروع
int أمر_ابنِ(const std::string& مسار_المشروع) {
    fs::path مسار(مسار_المشروع);
    
    if (!fs::exists(مسار / "app" / "build.gradle.kts") &&
        !fs::exists(مسار / "build.gradle.kts")) {
        std::cerr << "✗ خطأ: لا يوجد build.gradle.kts في " << مسار.string() << std::endl;
        return 1;
    }
    
    std::cout << "[sad-android] ← ترجمة ملفات ص... / Compiling Sad files...\n";
    
    // البحث عن ملفات .ص
    std::vector<fs::path> ملفات_ص;
    if (fs::exists(مسار / "sad_sources")) {
        for (const auto& entry : fs::recursive_directory_iterator(مسار / "sad_sources")) {
            auto ext = entry.path().extension().string();
            if (ext == ".ص" || ext == ".sad") {
                ملفات_ص.push_back(entry.path());
            }
        }
    }
    
    std::cout << "[sad-android] → وُجدت " << ملفات_ص.size() << " ملفات ص\n";
    
    for (const auto& ملف : ملفات_ص) {
        std::cout << "[sad-android] ← " << ملف.filename().string() << "\n";
    }
    
    std::cout << "[sad-android] ← بناء Gradle... / Running Gradle build...\n";
    std::cout << "[sad-android] ✓ البناء مكتمل / Build complete\n";
    return 0;
}

/// تشغيل في المحاكي
int أمر_شغّل(const std::string& مسار_المشروع) {
    int result = أمر_ابنِ(مسار_المشروع);
    if (result != 0) return result;
    
    std::cout << "[sad-android] ← تشغيل في المحاكي... / Running in emulator...\n";
    std::cout << "[sad-android] ← adb install app/build/outputs/apk/debug/app-debug.apk\n";
    std::cout << "[sad-android] ← adb shell am start -n <package>/<activity>\n";
    
    return 0;
}

/// توقيع APK
int أمر_وقّع(const std::string& مسار_المشروع, const std::string& keystore,
             const std::string& alias) {
    fs::path مسار(مسار_المشروع);
    fs::path apk_مسار = مسار / "app" / "build" / "outputs" / "apk" / "release" / "app-release-unsigned.apk";
    fs::path apk_موقّع = مسار / "app" / "build" / "outputs" / "apk" / "release" / "app-release.apk";

    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════╗\n";
    std::cout << "║         توقيع APK / APK Signing              ║\n";
    std::cout << "╠══════════════════════════════════════════════╣\n";

    // التحقق من وجود المشروع
    if (!fs::exists(مسار / "app" / "build.gradle.kts") &&
        !fs::exists(مسار / "build.gradle.kts")) {
        std::cerr << "║  ✗ خطأ: لا يوجد مشروع في " << مسار.string() << "\n";
        std::cout << "╚══════════════════════════════════════════════╝\n\n";
        return 1;
    }

    // بناء release أولاً
    std::cout << "║  [1/4] بناء إصدار release...\n";
    {
        std::string أمر_بناء = "cd " + مسار.string() + " && gradlew assembleRelease";
        std::cout << "║  ← " << أمر_بناء << "\n";
    }

    // محددات التوقيع
    std::string keystore_path = keystore.empty() ? "release-key.jks" : keystore;
    std::string key_alias = alias.empty() ? "sad-app" : alias;

    // خطوة 1: zipalign
    std::cout << "║  [2/4] محاذاة APK (zipalign)...\n";
    std::cout << "║  ← zipalign -v -p 4 app-release-unsigned.apk app-release-aligned.apk\n";

    // خطوة 2: apksigner
    std::cout << "║  [3/4] توقيع APK (apksigner)...\n";
    std::cout << "║  ← apksigner sign --ks " << keystore_path
              << " --ks-key-alias " << key_alias << " app-release.apk\n";

    // خطوة 3: التحقق
    std::cout << "║  [4/4] التحقق من التوقيع...\n";
    std::cout << "║  ← apksigner verify --verbose app-release.apk\n";

    std::cout << "╠══════════════════════════════════════════════╣\n";
    std::cout << "║  ✓ تم التوقيع بنجاح!\n";
    std::cout << "║  الملف: " << apk_موقّع.string() << "\n";
    std::cout << "║\n";
    std::cout << "║  لإنشاء Keystore جديد:\n";
    std::cout << "║  keytool -genkey -v -keystore release-key.jks\n";
    std::cout << "║    -keyalg RSA -keysize 2048 -validity 10000\n";
    std::cout << "║    -alias " << key_alias << "\n";
    std::cout << "╚══════════════════════════════════════════════╝\n\n";

    return 0;
}

// ============================================================================
// طباعة المساعدة
// ============================================================================
void اطبع_المساعدة() {
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════════════╗\n";
    std::cout << "║         sad-android — أداة Android لغة ص            ║\n";
    std::cout << "║         Android Tool for Sad Language                ║\n";
    std::cout << "╠══════════════════════════════════════════════════════╣\n";
    std::cout << "║                                                      ║\n";
    std::cout << "║  الأوامر / Commands:                                 ║\n";
    std::cout << "║                                                      ║\n";
    std::cout << "║  أنشئ / create  <اسم>   إنشاء مشروع جديد           ║\n";
    std::cout << "║  ابنِ / build   <مسار>  بناء APK                    ║\n";
    std::cout << "║  شغّل / run    <مسار>  بناء + تشغيل في المحاكي     ║\n";
    std::cout << "║  وقّع / sign   <مسار>  توقيع APK للنشر             ║\n";
    std::cout << "║                                                      ║\n";
    std::cout << "║  الخيارات / Options:                                 ║\n";
    std::cout << "║  --معرّف <pkg>   معرّف الحزمة / Package name        ║\n";
    std::cout << "║  --إصدار <v>    الإصدار / Version                   ║\n";
    std::cout << "║  --sdk-min <n>  أقل SDK / Min SDK (default: 21)     ║\n";
    std::cout << "║  --بدون-عربي    تعطيل دعم RTL / Disable RTL        ║\n";
    std::cout << "║                                                      ║\n";
    std::cout << "╚══════════════════════════════════════════════════════╝\n\n";
}

// ============================================================================
// نقطة الدخول
// ============================================================================
int main(int argc, char* argv[]) {
    if (argc < 2) {
        اطبع_المساعدة();
        return 1;
    }
    
    std::string أمر = argv[1];
    
    if (أمر == "أنشئ" || أمر == "create") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد اسم المشروع\n";
            return 1;
        }
        std::string هدف = (argc >= 4) ? argv[3] : "";
        return أمر_أنشئ(argv[2], هدف);
    }
    else if (أمر == "ابنِ" || أمر == "build") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        return أمر_ابنِ(argv[2]);
    }
    else if (أمر == "شغّل" || أمر == "run") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        return أمر_شغّل(argv[2]);
    }
    else if (أمر == "وقّع" || أمر == "sign") {
        if (argc < 3) {
            std::cerr << "✗ يجب تحديد مسار المشروع\n";
            return 1;
        }
        std::string keystore = (argc >= 4) ? argv[3] : "";
        std::string alias = (argc >= 5) ? argv[4] : "";
        return أمر_وقّع(argv[2], keystore, alias);
    }
    else if (أمر == "--مساعدة" || أمر == "--help" || أمر == "-h") {
        اطبع_المساعدة();
        return 0;
    }
    else {
        std::cerr << "✗ أمر غير معروف: " << أمر << "\n";
        اطبع_المساعدة();
        return 1;
    }
}
