#!/bin/busybox sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
export SAD_UI_FB_FONT=/font.psf
/wm-dyn > /dev/ttyS0 2>&1 &
/bin/busybox sleep 3600
