# CMake generated Testfile for 
# Source directory: C:/s/s_language/tests/backends/llvm
# Build directory: C:/s/s_language/tests/backends/llvm/build_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AllTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe")
  set_tests_properties(AllTests PROPERTIES  LABELS "LLVM;Backend;All" TIMEOUT "600" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;98;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AllTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe")
  set_tests_properties(AllTests PROPERTIES  LABELS "LLVM;Backend;All" TIMEOUT "600" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;98;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AllTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe")
  set_tests_properties(AllTests PROPERTIES  LABELS "LLVM;Backend;All" TIMEOUT "600" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;98;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AllTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe")
  set_tests_properties(AllTests PROPERTIES  LABELS "LLVM;Backend;All" TIMEOUT "600" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;98;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(AllTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LinkerTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMLinker")
  set_tests_properties(LinkerTests PROPERTIES  LABELS "LLVM;Backend;Linker" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;104;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LinkerTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMLinker")
  set_tests_properties(LinkerTests PROPERTIES  LABELS "LLVM;Backend;Linker" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;104;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LinkerTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMLinker")
  set_tests_properties(LinkerTests PROPERTIES  LABELS "LLVM;Backend;Linker" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;104;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LinkerTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMLinker")
  set_tests_properties(LinkerTests PROPERTIES  LABELS "LLVM;Backend;Linker" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;104;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(LinkerTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OptimizerTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMOptimizer")
  set_tests_properties(OptimizerTests PROPERTIES  LABELS "LLVM;Backend;Optimizer" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;110;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OptimizerTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMOptimizer")
  set_tests_properties(OptimizerTests PROPERTIES  LABELS "LLVM;Backend;Optimizer" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;110;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OptimizerTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMOptimizer")
  set_tests_properties(OptimizerTests PROPERTIES  LABELS "LLVM;Backend;Optimizer" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;110;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OptimizerTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMOptimizer")
  set_tests_properties(OptimizerTests PROPERTIES  LABELS "LLVM;Backend;Optimizer" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;110;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(OptimizerTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TargetTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMTarget")
  set_tests_properties(TargetTests PROPERTIES  LABELS "LLVM;Backend;Target" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;116;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TargetTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMTarget")
  set_tests_properties(TargetTests PROPERTIES  LABELS "LLVM;Backend;Target" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;116;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TargetTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMTarget")
  set_tests_properties(TargetTests PROPERTIES  LABELS "LLVM;Backend;Target" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;116;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TargetTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMTarget")
  set_tests_properties(TargetTests PROPERTIES  LABELS "LLVM;Backend;Target" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;116;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(TargetTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DebugTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMDebug")
  set_tests_properties(DebugTests PROPERTIES  LABELS "LLVM;Backend;Debug" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;122;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DebugTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMDebug")
  set_tests_properties(DebugTests PROPERTIES  LABELS "LLVM;Backend;Debug" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;122;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DebugTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMDebug")
  set_tests_properties(DebugTests PROPERTIES  LABELS "LLVM;Backend;Debug" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;122;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DebugTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMDebug")
  set_tests_properties(DebugTests PROPERTIES  LABELS "LLVM;Backend;Debug" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;122;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(DebugTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RuntimeTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMRuntime")
  set_tests_properties(RuntimeTests PROPERTIES  LABELS "LLVM;Backend;Runtime" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;128;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RuntimeTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMRuntime")
  set_tests_properties(RuntimeTests PROPERTIES  LABELS "LLVM;Backend;Runtime" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;128;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RuntimeTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMRuntime")
  set_tests_properties(RuntimeTests PROPERTIES  LABELS "LLVM;Backend;Runtime" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;128;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RuntimeTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMRuntime")
  set_tests_properties(RuntimeTests PROPERTIES  LABELS "LLVM;Backend;Runtime" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;128;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(RuntimeTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CodeGenTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "LLVMCodeGen")
  set_tests_properties(CodeGenTests PROPERTIES  LABELS "LLVM;Backend;CodeGen" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;134;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CodeGenTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "LLVMCodeGen")
  set_tests_properties(CodeGenTests PROPERTIES  LABELS "LLVM;Backend;CodeGen" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;134;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CodeGenTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "LLVMCodeGen")
  set_tests_properties(CodeGenTests PROPERTIES  LABELS "LLVM;Backend;CodeGen" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;134;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CodeGenTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "LLVMCodeGen")
  set_tests_properties(CodeGenTests PROPERTIES  LABELS "LLVM;Backend;CodeGen" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;134;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(CodeGenTests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(IntegrationTests "C:/s/s_language/tests/backends/llvm/build_tests/Debug/llvm_backend_tests.exe" "--suite" "Integration")
  set_tests_properties(IntegrationTests PROPERTIES  LABELS "LLVM;Backend;Integration" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;140;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(IntegrationTests "C:/s/s_language/tests/backends/llvm/build_tests/Release/llvm_backend_tests.exe" "--suite" "Integration")
  set_tests_properties(IntegrationTests PROPERTIES  LABELS "LLVM;Backend;Integration" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;140;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(IntegrationTests "C:/s/s_language/tests/backends/llvm/build_tests/MinSizeRel/llvm_backend_tests.exe" "--suite" "Integration")
  set_tests_properties(IntegrationTests PROPERTIES  LABELS "LLVM;Backend;Integration" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;140;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(IntegrationTests "C:/s/s_language/tests/backends/llvm/build_tests/RelWithDebInfo/llvm_backend_tests.exe" "--suite" "Integration")
  set_tests_properties(IntegrationTests PROPERTIES  LABELS "LLVM;Backend;Integration" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/s/s_language/tests/backends/llvm/CMakeLists.txt;140;add_test;C:/s/s_language/tests/backends/llvm/CMakeLists.txt;0;")
else()
  add_test(IntegrationTests NOT_AVAILABLE)
endif()
