"""
============================================================================
(AR) مُولِّد node_types_generated.h من language-truth/ui_nodes.yaml — لغة ص
(EN) Generator for sad_ui/generated/node_types_generated.h from ui_nodes.yaml
----------------------------------------------------------------------------
(AR) يقرأ مصدر الحقيقة لأنواع عُقَد الواجهة ويُنتج قائمتَي X-macro:
       - SAD_UI_NODE_TYPE_LIST(X)  ⇒ X(Id, "الاسم_القانونيّ")
         منها يُبنى تعدادُ UINodeType نفسُه وجدولُ (نوع ⇒ اسم) — فيستحيل
         أن ينحرف أحدُهما عن الآخر أو عن مصدر الحقيقة.
       - SAD_UI_NODE_ALT_NAME_LIST(X) ⇒ X(Id, "اسمٌ إضافيّ")
         أسماءُ القراءة الإضافيّة: أسماءُ المصانع المدمَجة (تُشتقّ آليًّا من
         builtins/ui_widgets.yaml) + دَينُ الهجرة legacy_names. منها يُكمَّل
         جدولُ (اسم ⇒ نوع) وحدَه — فلا تُطبَع هذه الأسماء أبدًا.
     كلّ سلسلة عربيّة تُصدَّر \\xHH (لا حرفيًّا) لتفادي صفحة ترميز MSVC.
     يستهلكه types.h/types.cpp داخلَ مكتبة الرسومات — فيراه **المحرّكان معًا**
     (المفسّر والمترجم) عبر المكتبة نفسِها، ولا نسخةَ تعدادٍ ثانية في أيٍّ منهما.

(EN) Emits two X-macro lists: the canonical node types (which build both the
     UINodeType enum and the type⇒name table, so they cannot drift) and the
     extra read-only names (builtin factory names, derived automatically, plus
     documented legacy migration debt) which complete the name⇒type table only.
     Arabic strings are hex-escaped. Consumed inside the graphics library, hence
     by BOTH engines through it.
============================================================================
"""
from __future__ import annotations

import argparse
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("[gen_ui_nodes] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# (AR) تحقّق المخطّط مشترك عبر _lib (اختياريّ — يُتخطّى بسلاسة إن غاب jsonschema).
try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    from _lib.validator import validate_no_duplicates      # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_YAML = _REPO_ROOT / "language-truth" / "ui_nodes.yaml"
_DEFAULT_WIDGETS = _REPO_ROOT / "language-truth" / "builtins" / "ui_widgets.yaml"
_DEFAULT_SCHEMA = _REPO_ROOT / "language-truth" / "_schemas" / "ui_nodes.schema.json"
_DEFAULT_HEADER = (
    _REPO_ROOT / "features" / "graphics" / "core" / "include" / "sad_ui" / "generated"
    / "node_types_generated.h"
)


def _hex(s: str) -> str:
    """(AR) ترميز \\xHH بايتيّ (UTF-8)؛ يُبقي ASCII الطباعيّ حرفيًّا. / byte-wise \\xHH."""
    out = []
    for b in str(s).encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


HEADER_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from language-truth/ui_nodes.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_nodes.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_nodes.py
//
// To modify: edit language-truth/ui_nodes.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_nodes.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأنواع عُقَد واجهة SadUI وأسمائها العربيّة.
//   يستهلكه — داخلَ مكتبة الرسومات — تعدادُ `UINodeType` في sad_ui/types.h
//   وجدولا الاسم في sad_ui/types.cpp، فيراه **المحرّكان معًا** (المفسّر
//   والمترجم) عبر المكتبة نفسِها: لا تعدادَ ثانٍ ولا اسمَ عقدةٍ حرفيّ في أيٍّ.
//   القائمتان:
//     • SAD_UI_NODE_TYPE_LIST     — الترتيبُ هو ترتيبُ التعداد (لا تُزحزَح القيم).
//     • SAD_UI_NODE_ALT_NAME_LIST — أسماءُ قراءةٍ إضافيّة لا تُطبَع.
// (EN) SoT for SadUI node types and their Arabic names. Consumed inside the
//   graphics library by types.h/types.cpp, hence by BOTH engines through it.
// ============================================================================

#pragma once

// ────────────────────────────────────────────────────────────────────────────
// (AR) X(Id, "الاسم_القانونيّ") — الترتيبُ هنا هو ترتيبُ أعضاء التعداد.
// (EN) X(Id, "canonical") — this order IS the enum order.
// ────────────────────────────────────────────────────────────────────────────
#define SAD_UI_NODE_TYPE_LIST(X) \\
{types}

// (AR) عددُ الأنواع — للتحقّق الساكن من تطابق التعداد مع مصدر الحقيقة.
#define SAD_UI_NODE_TYPE_COUNT {count}

// ────────────────────────────────────────────────────────────────────────────
// (AR) X(Id, "اسمٌ إضافيّ") — يُقرَأ ولا يُطبَع: أسماءُ المصانع المدمَجة
//      (مشتقّةٌ آليًّا من builtins/ui_widgets.yaml) + دَينُ الهجرة legacy_names.
// (EN) X(Id, "alt name") — read-only aliases: builtin factory names (derived)
//      plus documented legacy migration debt.
// ────────────────────────────────────────────────────────────────────────────
#define SAD_UI_NODE_ALT_NAME_LIST(X) \\
{alts}
"""


def _widget_canonicals(path: Path) -> dict[str, str]:
    """(AR) cpp_id ⇒ الاسم القانونيّ، من language-truth/builtins/ui_widgets.yaml."""
    data = yaml.safe_load(open(path, encoding="utf-8"))
    return {f["cpp_id"]: f["canonical"] for f in data.get("functions", [])}


def emit_types(nodes: list[dict[str, Any]]) -> str:
    lines = []
    for n in nodes:
        entry = f'    X({n["id"]}, "{_hex(n["canonical"])}")'
        lines.append(f'{entry:<78} /* {n["canonical"]} */ \\')
    return "\n".join(lines).rstrip(" \\")


def emit_alts(nodes: list[dict[str, Any]], canon: dict[str, str]) -> tuple[str, int]:
    """(AR) أسماءُ القراءة الإضافيّة: مصانعُ العقدة (عدا اسمِها القانونيّ) + الدَّين."""
    lines, total = [], 0
    # (AR) مالكُ كلِّ اسمٍ يُقرأ (قانونيًّا كان أو إضافيًّا): قائمةُ تهيئةِ
    #   unordered_map تُسقِط المكرَّرَ صامتًا، فيُحَلُّ الاسمُ إلى العقدةِ الأولى
    #   وحدَها. نُفشِل التوليدَ بدل بعثِ جدولٍ يحجُب مدخلةً.
    owner: dict[str, str] = {n["canonical"]: n["id"] for n in nodes}
    for n in nodes:
        names: list[str] = []
        for cpp_id in n.get("builtins", []):
            name = canon.get(cpp_id)
            if name and name != n["canonical"] and name not in names:
                names.append(name)
        for name in n.get("legacy_names", []) or []:
            if name != n["canonical"] and name not in names:
                names.append(name)
        for name in names:
            if owner.setdefault(name, n["id"]) != n["id"]:
                raise SystemExit(
                    f"ui_nodes: اسمُ القراءة «{name}» مشتركٌ بين {owner[name]} و{n['id']} "
                    "— الجدولُ العكسيُّ يحجُب أحدَهما صامتًا"
                )
            entry = f'    X({n["id"]}, "{_hex(name)}")'
            lines.append(f"{entry:<78} /* {name} */ \\")
            total += 1
    return "\n".join(lines).rstrip(" \\"), total


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate node_types_generated.h from ui_nodes.yaml")
    p.add_argument("--yaml", type=Path, default=_DEFAULT_YAML)
    p.add_argument("--widgets", type=Path, default=_DEFAULT_WIDGETS,
                   help="builtins/ui_widgets.yaml — لاشتقاق أسماء المصانع")
    p.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA,
                   help="Path to ui_nodes.schema.json (validated if jsonschema present)")
    p.add_argument("--header", type=Path, default=_DEFAULT_HEADER)
    p.add_argument("--quiet", action="store_true")
    return p.parse_args(argv)


def _validate(nodes: list[dict[str, Any]], schema_path: Path, quiet: bool) -> None:
    """(AR) يتحقّق من كلّ عقدة ضدّ المخطّط + تفرّد id/canonical (إن توفّر jsonschema)."""
    if not _HAVE_VALIDATION or not schema_path.exists():
        if not quiet:
            print("[gen_ui_nodes] (تحقّق المخطّط متخطّى — jsonschema/المخطّط غائب)")
        return
    schema = load_schema(schema_path)
    for node in nodes:
        validate_schema(node, schema)
    validate_no_duplicates(nodes, key="id", context="ui_nodes.yaml id")
    validate_no_duplicates(nodes, key="canonical", context="ui_nodes.yaml canonical")


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_nodes] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_nodes] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if not args.yaml.exists():
            print(f"[gen_ui_nodes] FATAL: YAML not found: {args.yaml}", file=sys.stderr)
            return 1
        data = yaml.safe_load(open(args.yaml, encoding="utf-8"))
        nodes = data.get("nodes", [])
        if not nodes:
            print("[gen_ui_nodes] ERROR: no nodes found", file=sys.stderr)
            return 1
        _validate(nodes, args.schema, args.quiet)
        canon = _widget_canonicals(args.widgets) if args.widgets.exists() else {}
        alts, alt_count = emit_alts(nodes, canon)
        content = HEADER_TEMPLATE.format(
            types=emit_types(nodes), count=len(nodes), alts=alts
        )
        write_if_changed(args.header, content, args.quiet)
        if not args.quiet:
            print(f"[gen_ui_nodes] {len(nodes)} nodes + {alt_count} alt names → {args.header}")
        return 0
    except Exception as exc:
        print(f"[gen_ui_nodes] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
