#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================================
(AR) توليدُ جدولِ رتبِ المدمجاتِ من مصدرِ الحقيقة.

     الرتبةُ كانت رقمًا حرفيًّا في ذراعِ الأماميّة، ومصدرُ الحقيقةِ لا يعرفُها —
     أي عقدٌ في الوثائقِ لا يقيسُه أحد. صارت تُعلَن في `language-truth/builtins/*.yaml`
     بحقلِ `arity` ويُولَّد منها هذا الرأسُ، وتُنادى ثوابتُه في مواضعِ الفحص.
     فالرقمُ نسخةٌ واحدةٌ لا نسختان (درسُ «العددُ المنثورُ نسخةٌ ثانيةٌ للحقيقة»).
(EN) Generates the builtin arity table from SoT so the number lives once.
============================================================================
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOT_DIR = ROOT / "language-truth" / "builtins"
OUT = ROOT / "shared" / "builtins" / "generated" / "builtin_arity_generated.h"

HEADER = """// ============================================================================
// AUTO-GENERATED from language-truth/builtins/*.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/builtins/*.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_builtins_arity.py
//
// (AR) رتبةُ كلِّ مدمجٍ يفرضُ المترجمُ رتبتَه: أقلُّ عددِ وسائطَ وأكثرُه.
//      الأسماءُ تطابقُ فضاءاتِ builtin_registry_generated.h ومعرِّفاتِها.
// ============================================================================

#pragma once

#include <cstddef>

namespace Sad
{
    namespace Builtins
    {
        namespace Arity
        {
            /// (AR) مدًى مغلقٌ لعددِ الوسائطِ المقبول. (EN) Closed argument-count range.
            struct Range
            {
                std::size_t min;
                std::size_t max;
            };

"""

FOOTER = """        } // namespace Arity
    } // namespace Builtins
} // namespace Sad
"""


def collect(sot_dir: Path) -> dict[str, list[tuple[str, int, int, str]]]:
    """(AR) {الفضاء: [(المعرّف، الأدنى، الأقصى، الاسمُ القانونيّ)]}"""
    table: dict[str, list[tuple[str, int, int, str]]] = {}
    for path in sorted(sot_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for fn in doc.get("functions") or []:
            arity = fn.get("arity")
            if not arity:
                continue
            table.setdefault(fn["namespace"], []).append(
                (fn["cpp_id"], int(arity["min"]), int(arity["max"]), fn["canonical"]))
    return table


def render(table: dict[str, list[tuple[str, int, int, str]]]) -> str:
    parts = [HEADER]
    for namespace in sorted(table):
        parts.append(f"            namespace {namespace}\n            {{\n")
        for cpp_id, lo, hi, canonical in sorted(table[namespace]):
            parts.append(f"                // (AR) {canonical}\n")
            parts.append(
                f"                inline constexpr Range {cpp_id}{{{lo}, {hi}}};\n")
        parts.append(f"            }} // namespace {namespace}\n\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser()
    parser.add_argument("--yaml-dir", default=str(SOT_DIR))
    parser.add_argument("--out-h", default=str(OUT))
    parser.add_argument("--quiet", action="store_true")
    ns = parser.parse_args()

    table = collect(Path(ns.yaml_dir))
    out = Path(ns.out_h)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(table), encoding="utf-8", newline="\n")
    if not ns.quiet:
        declared = sum(len(v) for v in table.values())
        print(f"✓ وُلِّد {out} ({declared} مدمجًا في {len(table)} فضاءً)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
