"""
============================================================================
(AR) مُولِّد جدول لهجة التجميع العربيّ من language-truth — لغة ص (م١ RFC اللهجات)
(EN) Generator for the Arabic assembly dialect table from language-truth
----------------------------------------------------------------------------
(AR) يقرأ:
       • language-truth/dialects/assembly.yaml            (بُنى الكتلة والتلويث واللصائق)
       • language-truth/dialects/assembly_mnemonics/i686.yaml (معجم المنمنمات والسجلّات)
     ويُنتج هيدرًا واحدًا constexpr يستهلكه المحلّل والفاحص الدلاليّ والمترجم:
       shared/dialects/generated/asm_dialect_generated.h

     كلّ سلسلة عربيّة تُصدَّر \\xHH بايتيًّا (لا حرفيًّا) لتفادي صفحة ترميز MSVC —
     مطابقةً لمولّدات الرسومات. المفتاح القانونيّ **مجرَّد التشكيل** (تُحذَف
     علامات U+064B..U+065F بما فيها الشدّة) ليطابق ما يُصدره المُشكِّل (يجرّد التشكيل).

(EN) Emits a single constexpr header consumed by the parser, semantic checker,
     and compiler. Arabic strings are byte hex-escaped; canonical keys are
     diacritic-stripped (U+064B..U+065F, incl. shadda) to match lexer output.
============================================================================
"""
from __future__ import annotations

import argparse
import io
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception:  # pragma: no cover
    pass

try:
    import yaml
except ImportError:
    print("[gen_asm_dialect] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]


def _strip_diacritics(s: str) -> str:
    """(AR) يحذف التشكيل U+064B..U+065F (يطابق المُشكِّل). / strip Arabic diacritics."""
    return "".join(ch for ch in s if not (0x064B <= ord(ch) <= 0x065F))


def _hex(s: str) -> str:
    """(AR) ترميز \\xHH بايتيّ (UTF-8)؛ يُبقي ASCII الطباعيّ حرفيًّا. / byte-wise \\xHH."""
    out = []
    for b in str(s).encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


# (AR) فاصل قائمة التلويث الضمنيّ (implicitClobbers) — يُصدَّر ثابتًا مولَّدًا
#      kImplicitClobberSep فيستهلكه الطرفان (المولّد هنا والمحلّل/الخافض) من
#      مصدر واحد بلا حرفيّة مكرَّرة.
# (EN) Implicit-clobber list separator — exported as the generated constant
#      kImplicitClobberSep so producer and consumers share one source.
_IMPLICIT_CLOBBER_SEP = ","

# (AR) تقابل صنف المعامل العربيّ ⇒ رمز حرف واحد يستهلكه المترجم/الفاحص.
#      w=وجهة(تُكتب) r=قراءة l=لصيقة m=ذاكرة i=عدد a=تعليمة(بادئة)
# (EN) operand class Arabic ⇒ single-char code for compiler/semantic.
_OPERAND_CLASS = {
    "وجهة": "w",
    "مصدر": "r",
    "لصيقة": "l",
    "هدف": "l",
    "ذاكرة": "m",
    "رقم": "i",
    "مقدار": "r",
    "أ": "r",
    "ب": "r",
    "تعليمة": "a",
}


HEADER_TOP = """\
// ============================================================================
// AUTO-GENERATED from language-truth/dialects/ — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/dialects/ — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_asm_dialect.py
//
// To modify: edit the YAML SoT then rebuild (python x.py gen).
// لإجراء تعديل: عدّل مصدر الحقيقة YAML ثم أعد التوليد (python x.py gen).
// ============================================================================
//
// (AR) جدول لهجة التجميع العربيّ (منمنمات/سجلّات/تلويث/كلمات الكتلة) — المفاتيح
//      القانونيّة مجرَّدة التشكيل (تطابق ما يُصدره المُشكِّل). يستهلكه المحلّل
//      والفاحص الدلاليّ والمترجم sadc.
#pragma once

#include <cstddef>
#include <cstring>

namespace Sad
{
    namespace Dialects
    {
        namespace Asm
        {
            // (AR) منمنمة واحدة: العربيّ القانونيّ ⇒ التعليمة الأصليّة + أصناف المعاملات.
            //      operandClasses سلسلة من رموز: w=وجهة r=قراءة l=لصيقة m=ذاكرة i=عدد a=بادئة.
            //      عدد المعاملات = طول السلسلة.
            //      readsDest: هل تُقرأ الوجهة قبل الكتابة (من reads_dest في SoT)؟
            //      true ⇒ ربط inout (اجمع/وافق/زد…)، false ⇒ خرج صِرف (انقل/حمّل_عنوان…).
            //      writesSource: المنمنمة تكتب معاملها المصدر أيضًا (بادل/xchg — من
            //      writes_source في SoT) ⇒ متغيّر ص في موضع المصدر يُرفَض SEM034.
            //      implicitClobbers: قيود تلويث LLVM مفصولة بفواصل لسجلّات يكتبها
            //      العتاد ضمنيًّا (من implicit_writes في SoT)، أو سلسلة فارغة.
            //      operandWidth: عرض معامل السجلّ بالبتّات حين يخالف الافتراض (0 =
            //      عرض كلمة الهدف الطبيعيّ ⇒ ${N})؛ 16 ⇒ يُصدر الخفض ${N:w} فيُختار
            //      السجلّ الفرعيّ 16-بت (ax لا eax) — لازم لمعامل r/m16 (ltr/str).
            struct Mnemonic
            {
                const char *ar;             // (AR) canonical Arabic (diacritic-stripped)
                const char *en;             // (EN) native mnemonic (lowered form)
                const char *operandClasses; // (AR) one char per operand
                bool readsDest;             // (AR) الوجهة تُقرأ قبل الكتابة / dest is read before written
                bool writesSource;          // (AR) المصدر يُكتب أيضًا (بادل) / source is also written (xchg)
                const char *implicitClobbers; // (AR) تلويث ضمنيّ "~{eax},~{edx}" أو "" / implicit clobbers or empty
                int operandWidth;           // (AR) عرض معامل السجلّ (0=افتراضيّ، 16=${N:w}) / register operand width
            };

            // (AR) سجلّ واحد: الاسم العربيّ ⇒ الاسم الأصليّ.
            struct Register
            {
                const char *ar;
                const char *en;
            };

            // (AR) هدف تلويث مخصوص (غير سجلّ): الاسم العربيّ ⇒ قيد LLVM.
            struct ClobberSpecial
            {
                const char *ar;
                const char *llvm;
            };

"""

HEADER_BOTTOM = """\
            // (AR) بحث عن منمنمة بالاسم العربيّ القانونيّ (مجرَّد التشكيل). / lookup mnemonic.
            inline const Mnemonic *findMnemonic(const char *ar)
            {
                for (std::size_t i = 0; i < kMnemonicCount; ++i)
                    if (std::strcmp(kMnemonics[i].ar, ar) == 0)
                        return &kMnemonics[i];
                return nullptr;
            }

            // (AR) بحث عن سجلّ بالاسم العربيّ. / lookup register.
            inline const Register *findRegister(const char *ar)
            {
                for (std::size_t i = 0; i < kRegisterCount; ++i)
                    if (std::strcmp(kRegisters[i].ar, ar) == 0)
                        return &kRegisters[i];
                return nullptr;
            }

            // (AR) بحث عن هدف تلويث مخصوص بالاسم العربيّ. / lookup special clobber.
            inline const ClobberSpecial *findClobberSpecial(const char *ar)
            {
                for (std::size_t i = 0; i < kClobberSpecialCount; ++i)
                    if (std::strcmp(kClobberSpecials[i].ar, ar) == 0)
                        return &kClobberSpecials[i];
                return nullptr;
            }
        } // namespace Asm
    } // namespace Dialects
} // namespace Sad
"""


def build_header(dialect: dict[str, Any], mnem: dict[str, Any]) -> str:
    lines: list[str] = [HEADER_TOP]

    # (AR) خريطة السجلّات المعجميّة (مجرَّدة التشكيل) — يحتاجها حارس implicit_writes.
    # (EN) Lexicon register map (diacritic-stripped) — needed by the implicit_writes guard.
    reg_map: dict[str, str] = {}
    for _group, regs in mnem["registers"].items():
        for r in regs:
            reg_map[_strip_diacritics(r["ar"])] = r["en"]

    # ── ثابت فاصل التلويث الضمنيّ ──
    lines.append("            // (AR) فاصل قائمة implicitClobbers — يستهلكه المحلّل والخافض بدل حرفيّة مكرَّرة.")
    lines.append("            // (EN) implicitClobbers list separator, shared by parser and lowering.")
    lines.append(f"            inline constexpr char kImplicitClobberSep = '{_IMPLICIT_CLOBBER_SEP}';")
    lines.append("")

    # ── المنمنمات ──
    lines.append("            // ─── المنمنمات / mnemonics ───")
    lines.append("            inline constexpr Mnemonic kMnemonics[] = {")
    seen: set[str] = set()
    for category, insts in mnem["instructions"].items():
        for it in insts:
            ar_key = _strip_diacritics(it["ar"])
            if ar_key in seen:
                raise SystemExit(f"[gen_asm_dialect] تكرار منمنمة بعد تجريد التشكيل: {ar_key}")
            seen.add(ar_key)
            classes = ""
            for op in it["operands"]:
                if op not in _OPERAND_CLASS:
                    raise SystemExit(f"[gen_asm_dialect] صنف معامل مجهول '{op}' في المنمنمة {it['ar']}")
                classes += _OPERAND_CLASS[op]
            # (AR) reads_dest إلزاميّ لكلّ منمنمة لها معامل وجهة (w)، وممنوع لغيرها —
            #      حارس يفرض المراجعة المعماريّة الصريحة في مصدر الحقيقة.
            # (EN) reads_dest is mandatory for every 'w'-operand mnemonic and
            #      forbidden otherwise — forces an explicit architectural review.
            has_dest = "w" in classes
            if has_dest and "reads_dest" not in it:
                raise SystemExit(
                    f"[gen_asm_dialect] المنمنمة {it['ar']} لها معامل «وجهة» بلا حقل reads_dest — صنّفها صراحةً في SoT"
                )
            if not has_dest and "reads_dest" in it:
                raise SystemExit(
                    f"[gen_asm_dialect] المنمنمة {it['ar']} بلا معامل «وجهة» لكن لها reads_dest — احذف الحقل"
                )
            reads_dest = "true" if it.get("reads_dest", False) else "false"
            # (AR) writes_source (بادل/xchg): مسموح فقط حيث «وجهة» و«مصدر» معًا —
            #      حارس يمنع تعميم العلم على منمنمات لا معنى له فيها.
            # (EN) writes_source guard: allowed only with both a dest and a source operand.
            if "writes_source" in it and not (has_dest and "r" in classes):
                raise SystemExit(
                    f"[gen_asm_dialect] المنمنمة {it['ar']} لها writes_source بلا معاملَي «وجهة» و«مصدر» معًا — احذف الحقل"
                )
            writes_source = "true" if it.get("writes_source", False) else "false"
            # (AR) implicit_writes: سجلّات معجميّة يكتبها العتاد ضمنيًّا — مسموحة فقط
            #      على منمنمة بلا معامل «وجهة» (كتابات ذات الوجهة يمثّلها reads_dest)،
            #      وكلّ اسم يجب أن يكون سجلًّا معجميًّا بلا تكرار.
            # (EN) implicit_writes guard: dest-less mnemonics only; every entry must be
            #      a lexicon register; duplicates rejected.
            implicit_clobbers = ""
            if "implicit_writes" in it:
                if has_dest:
                    raise SystemExit(
                        f"[gen_asm_dialect] المنمنمة {it['ar']} لها معامل «وجهة» ومعها implicit_writes — كتابة الوجهة يمثّلها reads_dest، احذف الحقل"
                    )
                seen_regs: set[str] = set()
                parts: list[str] = []
                for reg_ar in it["implicit_writes"]:
                    reg_key = _strip_diacritics(str(reg_ar))
                    if reg_key not in reg_map:
                        raise SystemExit(
                            f"[gen_asm_dialect] implicit_writes للمنمنمة {it['ar']} يذكر «{reg_ar}» وليس سجلًّا معجميًّا"
                        )
                    if reg_key in seen_regs:
                        raise SystemExit(
                            f"[gen_asm_dialect] implicit_writes للمنمنمة {it['ar']} يكرّر السجلّ «{reg_ar}»"
                        )
                    seen_regs.add(reg_key)
                    parts.append("~{" + reg_map[reg_key] + "}")
                implicit_clobbers = _IMPLICIT_CLOBBER_SEP.join(parts)
            # (AR) operand_width: عرض معامل السجلّ (16 وحده مدعوم) — مسموح فقط على
            #      منمنمة لها معامل سجلّ **واحد** (وجهة w أو مصدر r). المعامل الذاكريّ/
            #      الفوريّ لا معنى لمُعدِّل ${N:w} فيه (المُجمِّع يستنتج حجم الذاكرة)،
            #      والعرض لكلّ التعليمة لا لكلّ معامل (statement_asm يمرّره لكلّ المعاملات)
            #      ⇒ منمنمة ثنائيّة السجلّات ستُصدر :w على كليهما خطأً. حارس يمنع كلَيهما.
            # (EN) operand_width guard: exactly one register operand (w or r); the width
            #      applies per-instruction, so a two-register mnemonic would wrongly
            #      emit :w on both operands.
            operand_width = 0
            if "operand_width" in it:
                reg_operands = classes.count("w") + classes.count("r")
                if reg_operands != 1:
                    raise SystemExit(
                        f"[gen_asm_dialect] المنمنمة {it['ar']} لها operand_width مع {reg_operands} معامل سجلّ — مسموح فقط بمعامل سجلّ واحد (المُعدِّل يسري على كلّ المعاملات)، احذف الحقل أو صحّح المعاملات"
                    )
                operand_width = int(it["operand_width"])
            lines.append(
                f'                {{ "{_hex(ar_key)}", "{_hex(it["en"])}", "{_hex(classes)}", {reads_dest}, {writes_source}, "{_hex(implicit_clobbers)}", {operand_width} }},'
                f'  // {it["ar"]} => {it["en"]}'
            )
    lines.append("            };")
    lines.append("            inline constexpr std::size_t kMnemonicCount = sizeof(kMnemonics) / sizeof(kMnemonics[0]);")
    lines.append("")

    # ── السجلّات ──
    lines.append("            // ─── السجلّات / registers ───")
    lines.append("            inline constexpr Register kRegisters[] = {")
    rseen: set[str] = set()
    for group, regs in mnem["registers"].items():
        for r in regs:
            ar_key = _strip_diacritics(r["ar"])
            if ar_key in rseen:
                raise SystemExit(f"[gen_asm_dialect] تكرار سجلّ بعد تجريد التشكيل: {ar_key}")
            rseen.add(ar_key)
            lines.append(
                f'                {{ "{_hex(ar_key)}", "{_hex(r["en"])}" }},  // {r["ar"]} => {r["en"]}'
            )
    lines.append("            };")
    lines.append("            inline constexpr std::size_t kRegisterCount = sizeof(kRegisters) / sizeof(kRegisters[0]);")
    lines.append("")

    # ── أهداف التلويث المخصوصة ──
    lines.append("            // ─── أهداف التلويث المخصوصة / special clobber targets ───")
    lines.append("            inline constexpr ClobberSpecial kClobberSpecials[] = {")
    for t in dialect.get("clobbers", {}).get("special_targets", []):
        lines.append(
            f'                {{ "{_hex(_strip_diacritics(t["ar"]))}", "{_hex(t["llvm"])}" }},  // {t["ar"]} => {t["llvm"]}'
        )
    lines.append("            };")
    lines.append("            inline constexpr std::size_t kClobberSpecialCount = sizeof(kClobberSpecials) / sizeof(kClobberSpecials[0]);")
    lines.append("")

    # ── كلمات الكتلة القانونيّة (مجرَّدة التشكيل) ──
    block = dialect["block"]
    clob = dialect.get("clobbers", {})
    lines.append("            // ─── كلمات الكتلة القانونيّة (مجرَّدة التشكيل) / canonical block keywords ───")
    lines.append(f'            inline constexpr const char *kBlockOpener = "{_hex(_strip_diacritics(block["opener_ar"]))}";   // {block["opener_ar"]}')
    lines.append(f'            inline constexpr const char *kBlockCloser = "{_hex(_strip_diacritics(block["closer_ar"]))}";   // {block["closer_ar"]}')
    if "volatile_ar" in block:
        lines.append(f'            inline constexpr const char *kBlockVolatile = "{_hex(_strip_diacritics(block["volatile_ar"]))}"; // {block["volatile_ar"]}')
    if "keyword_ar" in clob:
        lines.append(f'            inline constexpr const char *kClobberKeyword = "{_hex(_strip_diacritics(clob["keyword_ar"]))}";  // {clob["keyword_ar"]}')
    lines.append("")

    lines.append(HEADER_BOTTOM)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Arabic assembly dialect header from language-truth")
    ap.add_argument("--dialect", required=True, help="path to dialects/assembly.yaml")
    ap.add_argument("--mnemonics", required=True, help="path to dialects/assembly_mnemonics/<arch>.yaml")
    ap.add_argument("--dialect-schema", default=str(_REPO_ROOT / "language-truth" / "_schemas" / "dialect.schema.json"))
    ap.add_argument("--mnemonics-schema", default=str(_REPO_ROOT / "language-truth" / "_schemas" / "assembly_mnemonics.schema.json"))
    ap.add_argument("--header", required=True, help="output header path")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    dialect = yaml.safe_load(Path(args.dialect).read_text(encoding="utf-8"))
    mnem = yaml.safe_load(Path(args.mnemonics).read_text(encoding="utf-8"))

    if _HAVE_VALIDATION:
        try:
            validate_schema(dialect, load_schema(Path(args.dialect_schema)))
            validate_schema(mnem, load_schema(Path(args.mnemonics_schema)))
        except Exception as e:  # pragma: no cover
            print(f"[gen_asm_dialect] schema validation failed: {e}", file=sys.stderr)
            return 2

    header = build_header(dialect, mnem)
    out = Path(args.header)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header, encoding="utf-8", newline="\n")
    if not args.quiet:
        print(f"[gen_asm_dialect] wrote {out}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except Exception:
        traceback.print_exc()
        sys.exit(1)
