"""
============================================================================
(AR) مُولِّد ألوان SadUI من language-truth/ui_colors.yaml — لغة ص
(EN) Generator for SadUI colors from language-truth/ui_colors.yaml
----------------------------------------------------------------------------
(AR) مصدرٌ واحد يُنتج مُخرَجَين يزيلان تباعد جدولَي الألوان السابقين ويجعلان
     الألوان تعدادًا مكتوبًا (لا نصوصًا قابلة للخطأ):

  1. color_prelude_generated.h — ثابت C++ يحمل مصدرَ تعداد `ألوان` بلغة ص
     (قيمة كلّ عضو = اسمه القانونيّ نصًّا). **المفسّر** يحلّله وينفّذه مرّةً عند
     الإقلاع (ensureBuiltinColorsRegistered) فيُعرَّف `ألوان.أحمر` (⇐ «أحمر»).
     **المترجم** لا يحلّل البادئة، بل يبذر `enumStringConstants_` من ماكرو
     SAD_UI_COLOR_MEMBERS (النتيجة متكافئة لوصول `ألوان.<عضو>`؛ إصلاح م0 جعل
     قيم التعداد النصّيّة متكافئة). الآليّتان مختلفتان لكنّ ناتج الـAPI واحد.

  2. color_table_generated.h — ثلاثة X-macros موحَّدة من نفس المصدر:
       SAD_UI_COLOR_NAME_HEX(X): X("اسم","#RRGGBB")     ⇐ getColorTable (الويب)
       SAD_UI_COLOR_BY_NAME(X):  X("اسم", NamedColorId)  ⇐ getColorByName (القلب)
       SAD_UI_COLOR_RGBA(X):     X(NamedColorId, 0xRRGGBBAA) ⇐ namedColorToRGBA
     فيشتقّ مسارا الويب والقلب من مصدرٍ واحد ⇒ لا تباعد صامت.

     كلّ سلسلة عربيّة تُصدَّر \\xHH بايتيًّا (تفاديًا لصفحة ترميز MSVC).

(EN) One SoT → the `ألوان` enum prelude + a unified name/hex/RGBA table that
     replaces the two previously divergent color tables. Arabic hex-escaped.
============================================================================
"""
from __future__ import annotations

import argparse
import io
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception:  # pragma: no cover
    pass

try:
    import yaml
except ImportError:
    print("[gen_ui_colors] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    from _lib.validator import validate_no_duplicates      # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_SCHEMA = _REPO_ROOT / "language-truth" / "_schemas" / "ui_colors.schema.json"


def _hex(s: str) -> str:
    """(AR) ترميز \\xHH بايتيّ (UTF-8)؛ يُبقي ASCII الطباعيّ حرفيًّا."""
    out = []
    for b in str(s).encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def _in_enum(c: dict[str, Any]) -> bool:
    """(AR) هل اللون عضوٌ في تعداد المطوّر؟ (الافتراض: نعم إن كان له اسم member)."""
    return bool(c.get("member")) and c.get("in_enum", True)


_PRELUDE_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from ui_colors.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من ui_colors.yaml — لا تعدّله يدوياً (x.py gen)
// (EN) Auto-generated by scripts/codegen/gen_ui_colors.py
// ============================================================================
//
// (AR) مصدرُ تعداد `ألوان` المدمَج بلغة ص (قيمة العضو = اسمه القانونيّ نصًّا).
//   **المفسّر فقط** يحلّل هذا المصدر وينفّذه مرّةً عند الإقلاع (فيُعرَّف
//   `ألوان.أحمر`). المترجم يبذر `enumStringConstants_` من ماكرو
//   SAD_UI_COLOR_MEMBERS (في color_table_generated.h) — لا يحلّل هذه البادئة.
// (EN) Builtin `ألوان` enum source. The INTERPRETER parses+executes this once at
//   startup; the COMPILER instead seeds enumStringConstants_ from the
//   SAD_UI_COLOR_MEMBERS macro (it does NOT parse this prelude).
// ============================================================================

#pragma once

namespace sad
{{
    namespace ui
    {{
        // (AR) مصدر ص لتعداد الألوان المدمَج (سلاسل عربيّة بترميز \\xHH).
        inline const char *colorEnumPrelude()
        {{
            return
{prelude_body};
        }}
    }} // namespace ui
}} // namespace sad
"""


def emit_prelude(colors: list[dict[str, Any]]) -> str:
    """(AR) يبني مصدرَ ص لتعداد الألوان سطرًا سطرًا (كلٌّ ثابتُ سلسلةٍ مُصعَّد)."""
    lines = [f'                "{_hex("تعداد ألوان")}\\n"']
    for c in colors:
        if not _in_enum(c):
            continue
        m = _hex(c["member"])
        lines.append(f'                "    {m} = \\"{m}\\"\\n"')
    lines.append(f'                "{_hex("نهاية")}\\n"')
    return "\n".join(lines)


_TABLE_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from ui_colors.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من ui_colors.yaml — لا تعدّله يدوياً (x.py gen)
// (EN) Auto-generated by scripts/codegen/gen_ui_colors.py
// ============================================================================
//
// (AR) جداول ألوان موحَّدة من مصدرٍ واحد — تُوسَّع في المكتبة:
//   SAD_UI_COLOR_NAME_HEX(X): X("اسم عربيّ", "#RRGGBB")   — جدول الاسم→hex (الويب).
//   SAD_UI_COLOR_BY_NAME(X):  X("اسم عربيّ", NamedColorId) — الاسم→NamedColor (القلب).
//   SAD_UI_COLOR_RGBA(X):     X(NamedColorId, 0xRRGGBBAA)  — NamedColor→RGBA.
//   SAD_UI_COLOR_MEMBERS(X):  X("ألوان.العضو", "العضو")   — يملأ enumStringConstants_
//                             في المترجم (المفسّر يسجّل التعداد عبر بادئته).
//   فيشتقّ مسارا الويب والقلب من نفس المصدر ⇒ لا تباعد صامت.
// (EN) Unified color tables from one SoT, expanded in the library.
// ============================================================================

#pragma once

// (AR) اسم تعداد المطوّر «ألوان» (بترميز \\xHH) — يستعمله المفسّر لتسجيل الخريطة.
#define SAD_UI_COLOR_ENUM_NAME "{enum_name}"

// (AR) استعمال: عرّف X ثمّ استدعِ الماكرو ثمّ ألغِ تعريف X.
#define SAD_UI_COLOR_NAME_HEX(X) \\
{name_hex}

#define SAD_UI_COLOR_BY_NAME(X) \\
{by_name}

#define SAD_UI_COLOR_RGBA(X) \\
{rgba}

// (AR) أعضاء تعداد المطوّر «ألوان» مؤهّلةً (للمترجم): X("ألوان.أحمر", "أحمر").
#define SAD_UI_COLOR_MEMBERS(X) \\
{members}
"""


def _emit_macro_rows(rows: list[str]) -> str:
    if not rows:
        return "    /* (فارغ) */"
    return " \\\n".join(f"    {r}" for r in rows)


def emit_tables(colors: list[dict[str, Any]]) -> dict[str, str]:
    name_hex_rows: list[str] = []
    by_name_rows: list[str] = []
    rgba_rows: list[str] = []
    member_rows: list[str] = []
    for c in colors:
        cid = c["id"]
        rgba = str(c["rgba"]).upper()
        member = c.get("member")
        if member:
            m = _hex(member)
            # (AR) hex للويب: #RRGGBB للمعتم، و#RRGGBBAA عند وجود شفافيّة (alpha≠FF)
            #   كي لا يُفقَد قناة alpha (مثل «شفاف») — CSS يقبل 8 خانات.
            hexweb = "#" + (rgba[:6] if rgba[6:8] == "FF" else rgba)
            name_hex_rows.append(f'X("{m}", "{hexweb}") /* {member} */')
            if c.get("named_color"):
                by_name_rows.append(f'X("{m}", {cid}) /* {member} */')
            if _in_enum(c):
                qualified = _hex("ألوان." + member)
                member_rows.append(f'X("{qualified}", "{m}") /* ألوان.{member} */')
        if c.get("named_color"):
            rgba_rows.append(f"X({cid}, 0x{rgba})")
    return {
        "name_hex": _emit_macro_rows(name_hex_rows),
        "by_name": _emit_macro_rows(by_name_rows),
        "rgba": _emit_macro_rows(rgba_rows),
        "members": _emit_macro_rows(member_rows),
    }


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate SadUI color prelude + tables from ui_colors.yaml")
    p.add_argument("--yaml", type=Path, default=_REPO_ROOT / "language-truth" / "ui_colors.yaml")
    p.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA)
    p.add_argument("--prelude", type=Path, required=True, help="Output color_prelude_generated.h")
    p.add_argument("--table", type=Path, required=True, help="Output color_table_generated.h")
    p.add_argument("--quiet", action="store_true")
    return p.parse_args(argv)


def _validate(colors: list[dict[str, Any]], schema_path: Path, quiet: bool) -> None:
    if not _HAVE_VALIDATION or not schema_path.exists():
        if not quiet:
            print("[gen_ui_colors] (تحقّق المخطّط متخطّى — jsonschema/المخطّط غائب)")
        return
    schema = load_schema(schema_path)
    for c in colors:
        validate_schema(c, schema)
    validate_no_duplicates(colors, key="id", context="ui_colors.yaml id")
    named = [c for c in colors if c.get("member")]
    validate_no_duplicates(named, key="member", context="ui_colors.yaml member")


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_colors] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_colors] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if not args.yaml.exists():
            print(f"[gen_ui_colors] FATAL: YAML not found: {args.yaml}", file=sys.stderr)
            return 1
        data = yaml.safe_load(args.yaml.read_text(encoding="utf-8"))
        colors = data.get("colors", [])
        if not colors:
            print("[gen_ui_colors] ERROR: no colors found", file=sys.stderr)
            return 1
        _validate(colors, args.schema, args.quiet)

        prelude = _PRELUDE_TEMPLATE.format(prelude_body=emit_prelude(colors))
        write_if_changed(args.prelude, prelude, args.quiet)

        tables = emit_tables(colors)
        enum_name = _hex(data.get("enum", "ألوان"))
        table = _TABLE_TEMPLATE.format(enum_name=enum_name, **tables)
        write_if_changed(args.table, table, args.quiet)

        if not args.quiet:
            n_enum = sum(1 for c in colors if _in_enum(c))
            print(f"[gen_ui_colors] {len(colors)} colors ({n_enum} in enum) -> prelude + table")
        return 0
    except Exception as exc:
        print(f"[gen_ui_colors] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
