#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================================
(AR) توليدُ جدولِ رتبِ المدمجاتِ من مصدرِ الحقيقة.

     الرتبةُ كانت رقمًا حرفيًّا في ذراعِ الأماميّة، ومصدرُ الحقيقةِ لا يعرفُها —
     أي عقدٌ في الوثائقِ لا يقيسُه أحد. صارت تُعلَن في `language-truth/builtins/*.yaml`
     بحقلِ `arity` ويُولَّد منها هذا الرأسُ، وتُنادى ثوابتُه في مواضعِ الفحص.
     فالرقمُ نسخةٌ واحدةٌ لا نسختان (درسُ «العددُ المنثورُ نسخةٌ ثانيةٌ للحقيقة»).
(EN) Generates the builtin arity table from SoT so the number lives once.
============================================================================
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOT_DIR = ROOT / "language-truth" / "builtins"
OUT = ROOT / "shared" / "builtins" / "generated" / "builtin_arity_generated.h"

HEADER = """// ============================================================================
// AUTO-GENERATED from language-truth/builtins/*.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/builtins/*.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_builtins_arity.py
//
// (AR) رتبةُ كلِّ مدمجٍ يفرضُ المترجمُ رتبتَه: أقلُّ عددِ وسائطَ وأكثرُه.
//      الأسماءُ تطابقُ فضاءاتِ builtin_registry_generated.h ومعرِّفاتِها.
// ============================================================================

#pragma once

#include <cstddef>
#include <cstring>
#include <string>

namespace Sad
{
    namespace Builtins
    {
        namespace Arity
        {
            /// (AR) مدًى مغلقٌ لعددِ الوسائطِ المقبول. (EN) Closed argument-count range.
            /// (AR) والرتبةُ المفتوحةُ أعلاها (`variadic: true` في مصدرِ الحقيقة)
            ///      تُخفَّض بأقصى ما يسعُه العدّاد: الحدُّ قائمٌ شكلًا ولا يمنعُ نداءً
            ///      صحيحًا، فيبقى فاحصُ الرتبةِ واحدًا لا فرعَ فيه.
            struct Range
            {
                std::size_t min;
                std::size_t max;
            };

            /// (AR) لا حدَّ أعلى. (EN) No upper bound.
            inline constexpr std::size_t UNBOUNDED = static_cast<std::size_t>(-1);

"""

FOOTER = """        } // namespace Arity
    } // namespace Builtins
} // namespace Sad
"""



# (AR) طرائقُ الأنواع (`م.عين(ك، ق)`) سطحٌ ثانٍ لا يقلُّ عن المدمجاتِ خطرًا:
#      قِيس تبخّرُ `خ.عين("ك")` صامتًا. ومعرِّفاتُها تُشتَقُّ من `method_en`
#      بالخوارزميّةِ **نفسِها** التي يستعملها مولِّدُ الأسماء، وإلّا سمّى كلُّ
#      مولِّدٍ الشيءَ باسم — وهو انحرافٌ لا يحمرُّ.
TYPE_METHODS = ROOT / "language-truth" / "type_methods.yaml"
_TARGET_LABEL = {"ARRAY": "Array", "STRING": "String", "MAP": "Map",
                 "CHANNEL": "Channel", "ANY": "Any"}


def _method_cpp_id(method: dict, used: dict[str, int]) -> str:
    base = re.sub(r"[^a-zA-Z0-9]", "_", str(method.get("method_en", ""))).upper().strip("_")
    if not base or base[0].isdigit() or not any(c.isalpha() for c in base):
        base = "METHOD"
    if base not in used:
        used[base] = 1
        return base
    count = used[base]
    used[base] = count + 1
    return f"{base}_{count}"


# (AR) الأنواعُ التي تُفرَضُ رتبتُها في موضعِ الإرسالِ الواحد. و«أي» **مستثناةٌ
#      عن قياس**: طرائقُها تتصادمُ بالهجاءِ مع طرائقِ الأنواعِ المحدَّدة برتبٍ
#      مختلفة (`عين` للخريطةِ ٢ ولِـ«مستقبل» ١)، ونوعُ المستقبِلِ الحقيقيُّ
#      مجهولٌ عند التصريف — ففرضُ عقدٍ هناك يردُّ نداءً صحيحًا. تُعلَنُ رتبتُها
#      ولا تُفرَض، وذلك مصرَّحٌ به لا مسكوتٌ عنه.
#      ولا «قناة» كذلك: لا وسمَ لها في `SadTypeKind` فلا يبلغُها موضعُ الإرسال.
#      ووجودُ صفٍّ لا يستطيعُ أحدٌ الوصولَ إليه يُقرأُ حراسةً وليس بحراسة.
_ENFORCED_TARGETS = ("ARRAY", "STRING", "MAP")


def collect_lookup(path: Path) -> list[tuple[str, str, int, str]]:
    """(AR) [(الهدف، الاسم، الأدنى، الأعلى)] لكلِّ هجاءٍ يُنادى به."""
    if not path.exists():
        return []
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    rows: list[tuple[str, str, int, str]] = []
    seen: set[tuple[str, str]] = set()
    for method in doc.get("methods") or []:
        target = method.get("target_type", "ANY")
        arity = method.get("arity")
        if target not in _ENFORCED_TARGETS or not arity:
            continue
        top = "UNBOUNDED" if arity.get("variadic") else str(int(arity["max"]))
        for spelling in (method.get("method"), method.get("method_en")):
            if not spelling or (target, spelling) in seen:
                continue
            seen.add((target, spelling))
            rows.append((target, str(spelling), int(arity["min"]), top))
    return rows


def collect_type_methods(path: Path) -> dict[str, list[tuple[str, int, str, str]]]:
    """(AR) {الهدف: [(المعرّف، الأدنى، الأعلى، الاسمُ العربيّ)]} لِما له `arity`."""
    if not path.exists():
        return {}
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    by_target: dict[str, list[dict]] = {}
    for method in doc.get("methods") or []:
        by_target.setdefault(method.get("target_type", "ANY"), []).append(method)
    table: dict[str, list[tuple[str, int, str, str]]] = {}
    for target, methods in by_target.items():
        used: dict[str, int] = {}
        for method in methods:
            cpp_id = _method_cpp_id(method, used)  # (AR) يُستهلَك للجميعِ لِيتطابقَ الترقيم
            arity = method.get("arity")
            if not arity:
                continue
            top = "UNBOUNDED" if arity.get("variadic") else str(int(arity["max"]))
            table.setdefault(_TARGET_LABEL.get(target, target), []).append(
                (cpp_id, int(arity["min"]), top, method["method"]))
    return table


def collect(sot_dir: Path) -> dict[str, list[tuple[str, int, str, str]]]:
    """(AR) {الفضاء: [(المعرّف، الأدنى، الأقصى، الاسمُ القانونيّ)]}"""
    table: dict[str, list[tuple[str, int, str, str]]] = {}
    for path in sorted(sot_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for fn in doc.get("functions") or []:
            arity = fn.get("arity")
            if not arity:
                continue
            # (AR) `variadic: true` تعني «لا حدَّ أعلى» ويُمنَع معها `max` —
            #      فالعلمُ يُقرَأ ولا يُخمَّن معنى رقمٍ سحريّ.
            top = "UNBOUNDED" if arity.get("variadic") else str(int(arity["max"]))
            table.setdefault(fn["namespace"], []).append(
                (fn["cpp_id"], int(arity["min"]), top, fn["canonical"]))
    return table


def collect_by_name(sot_dir: Path):
    """(AR) [(الاسمُ العربيّ، الأدنى، الأعلى)] لِما رتبتُه **لا لبسَ فيها**.

    🔑 لماذا جدولٌ ثانٍ بالاسمِ والأوّلُ بالمعرّف؟ لأنّ المحرّكَين يسألانِ
    سؤالَين مختلفَين: المترجّمُ يعرفُ في موضعِ التخفيضِ **أيَّ** مدمَجٍ يُخفِّض
    فيقرأُ ثابتًا بالمعرّف؛ والمفسّرُ لا يملكُ إلّا الاسمَ وقتَ التشغيل. وكان
    أثرُ غيابِ هذا الجدولِ أنّ حقلَ `arity` يبلغُ محرّكًا واحدًا: يستهلكُه
    المترجّمُ في ٢١ ملفًّا والمفسّرُ في صفر، فالرتبةُ المُعلَنةُ عقدٌ نصفُه
    مفروضٌ ونصفُه حبرٌ على ورق.

    والاسمُ المُعلَنُ برتبتَين مختلفتَين **يُحذَفُ ولا يُخمَّن**: `استبدل`
    مُعلَنٌ (1,1) في `ui_widgets` و(3,3) في `strings` و`http_client`. اختيارُ
    أحدِهما يرفضُ نداءً صحيحًا، وتوحيدُهما اتّحادًا يقبلُ نداءً خاطئًا —
    وكلاهما اختراعٌ لا قياس. فالسكوتُ عن غيرِ المقيسِ أصدقُ (نظيرُ ما تفعله
    `TypeMethods::lookup` إذ تُرجِعُ nullptr لِما لا عقدَ له).

    🔑 و**غيابُ الرتبةِ تضاربٌ كسائرِ التضارب**. كانت الإعلاناتُ بلا `arity`
    تُتخطّى قبلَ العدّ، فيُقرأُ الاسمُ «لا لبسَ فيه» وتُفرَضُ عليه رتبةُ
    إعلانِه الآخر — وهو الاختراعُ نفسُه الذي حُذف `استبدل` لاجتنابِه، عائدًا
    من بابٍ خلفيّ. وقِيس أثرُه: `أرسل` تأخذُ (3,3) من `http_client` فيُرفَضُ
    `أرسل(ق، 42)` على قناةِ `تزامن_متقدم` وهو نداءٌ صحيح. ثمانيةُ أسماء.
    """
    ranges: dict[str, set] = {}
    for path in sorted(sot_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for fn in doc.get("functions") or []:
            arity = fn.get("arity")
            # (AR) `None` يدخلُ المجموعةَ ولا يُتخطّى: إعلانٌ بلا عقدٍ ينقضُ
            #      عقدَ أخيه، فلا يُفرَضُ عقدُ أحدِهما على الآخر.
            entry = None
            if arity:
                top = "UNBOUNDED" if arity.get("variadic") else str(int(arity["max"]))
                entry = (int(arity["min"]), top)
            ranges.setdefault(fn["canonical"], set()).add(entry)
    unambiguous = sorted((name, *next(iter(v))) for name, v in ranges.items()
                         if len(v) == 1 and next(iter(v)) is not None)
    conflicting = sorted(name for name, v in ranges.items()
                         if len(v) > 1 or next(iter(v)) is None)
    # (AR) لا يُذكَرُ في الترويسةِ إلّا ما له إعلانٌ برتبةٍ فعلًا: ذِكرُ سبعِ
    #      مئةِ اسمٍ بلا `arity` ضجيجٌ يُخفي الثمانيةَ التي يهمُّ أمرُها.
    conflicting = [n for n in conflicting if any(
        e is not None for e in ranges[n])]
    return unambiguous, conflicting


def render_by_name(sot_dir: Path) -> str:
    rows, conflicting = collect_by_name(sot_dir)
    # (AR) 🔑 والدعوى تُقاسُ على التنفيذِ قبلَ أن تُفرَض. `arity` في مصدرِ
    #      الحقيقةِ دعوى، وجسمُ المدمَجِ في المفسّرِ واقع، وقد اختلفا في ثلاثة:
    #      `تأكد_أكبر` يقرأُ `args[2]` وSoT يقول (2,2)؛ و`ارسم_خط`/`ارسم_مستطيل`
    #      يشترطانِ `args.size() >= 6` وSoT يقول (5,5) — أي أنّهما **غيرُ
    #      قابلَين للنداء**. وفرضُ الدعوى قبلَ تصحيحِها رفضٌ لنداءٍ صحيح.
    #      ولا يُصلَحُ بتوسيعِ SoT بلا تروٍّ: `ارسم_خط` في المترجّمِ أوپكودُ
    #      إطارِ عرضٍ للوضعِ الحرّ لا نداءُ لوحة — تنفيذانِ تحت اسمٍ واحد،
    #      وتوسيعُ الرتبةِ يغيّرُ مسارَ النواةِ صامتًا. فيُقصى الاسمُ ويُسمّى،
    #      أثرًا للقاعدةِ نفسِها التي حُذف بها `استبدل`: لا تُفرَضُ رتبةٌ على
    #      اسمٍ يُختلَفُ فيه.
    # (AR) 🔑 والقاعدةُ انقلبت بعدَ ثلاثِ جولاتِ مراجعةٍ: كانت «تُحرَسُ الأسماءُ
    #      كلُّها إلّا ما ثبتَ خلافُه»، وكلُّ جولةٍ كشفت أسماءً أخرى تُرفَضُ
    #      نداءاتُها الصحيحة (`تأكد_أكبر` `ارسم_خط` ثمّ `بحث` `دمج` `رتب`
    #      `فهرس_مصفوفة` `إزالة_عنصر`) — لأنّ نفيَ الخلافِ يعتمدُ على ماسحٍ
    #      أخطأ ثلاثًا، وقِيس أنّه لا يبلغُ إلّا ١٥ اسمًا من ٤٤٨ بطرفَيه.
    #      فصارت: **لا يُحرَسُ إلّا ما ثبتَ اتّفاقُه**. صمتُ الماسحِ لم يعُد
    #      إذنًا بالفرض، وهو المبدأُ نفسُه الذي حكم هذا الفرعَ كلَّه:
    #      لا تُفرَضُ دعوى لم تُقَس، والعددُ القليلُ الصادقُ خيرٌ من الكثيرِ
    #      المُدَّعى. ونموُّه سبيلُه توسيعُ القياسِ لا توسيعُ الثقة.
    from builtin_impl_arity import observed_ranges, ROOT as IMPL_ROOT  # noqa: PLC0415
    # (AR) 🔑 الماسحُ يقرأُ شجرتَهُ هو (مُشتَقَّةً من موضعِ ملفِّه)، بينما
    #      `--yaml-dir` قد يشيرُ إلى شجرةٍ أخرى. فيُقاسُ عندئذٍ إعلانُ شجرةٍ
    #      على تنفيذِ غيرِها، ويُبنى الجدولُ على «اتّفاقٍ» بين طرفَين لا
    #      يلتقيان. لا يُخمَّنُ ولا يُصمَتُ عنه: يُوقَف.
    try:
        sot_dir.resolve().relative_to(IMPL_ROOT)
    except ValueError:
        raise SystemExit(
            "✗ --yaml-dir خارجَ شجرةِ الماسح:\n"
            f"    الإعلانُ من: {sot_dir.resolve()}\n"
            f"    والتنفيذُ من: {IMPL_ROOT}\n"
            "  الجدولُ يُبنى على اتّفاقِ الطرفَين، فلا يُبنى من شجرتَين.")
    observed = observed_ranges()
    proven, unproven = [], []
    for name, lo, hi in rows:
        seen = observed.get(name)
        declared = (lo, None if hi == "UNBOUNDED" else int(hi))
        if seen and seen[0] is not None and seen[1] is not None and seen == declared:
            proven.append((name, lo, hi))
        else:
            unproven.append(name)
    rows, mismatched = proven, {}
    out = [
        "            namespace ByName\n            {\n",
        "                /// (AR) رتبةُ المدمَجِ مطلوبةً **بالاسمِ العربيِّ وقتَ\n"
        "                ///      التشغيل** — يستهلكُها المفسّرُ في نقطةِ اختناقِ\n"
        "                ///      النداء، كما يستهلكُ المترجّمُ ثوابتَ المعرّفات.\n"
        "                ///      فالعقدُ المُعلَنُ في مصدرِ الحقيقةِ يبلغُ المحرّكَين.\n",
    ]
    if conflicting:
        out.append("                ///\n"
                   "                /// (AR) وهذه أسماءٌ أُعلِنت برتبتَين مختلفتَين — أو\n"
                   "                ///      بإعلانٍ برتبةٍ وآخرَ بلا رتبةٍ، وغيابُ العقدِ\n"
                   "                ///      نقضٌ للعقدِ لا سكوتٌ عنه — فحُذفت:\n")
        for name in conflicting:
            out.append(f"                ///        · {name}\n")
        out.append("                ///      لا تُخمَّن رتبتُها ولا تُفرَض — لا عقدَ لها.\n")
    if unproven:
        out.append("                ///\n"
                   "                /// (AR) 🔑 ولا يُحرَسُ إلّا ما **ثبتَ اتّفاقُه**: دعوى\n"
                   "                ///      `arity` في مصدرِ الحقيقةِ تُقابَلُ بعقدِ التنفيذِ\n"
                   "                ///      في المفسّر (builtin_impl_arity.py)، فما لم\n"
                   "                ///      يُقرَأ طرفاه ويتطابقا لا تُفرَضُ رتبتُه.\n"
                   "                ///      وسببُ القلبِ مقيس: كانت القاعدةُ «احرُس إلّا ما\n"
                   "                ///      ثبتَ خلافُه»، فكشفت كلُّ جولةِ مراجعةٍ أسماءً\n"
                   "                ///      تُرفَضُ نداءاتُها الصحيحة — لأنّ نفيَ الخلافِ\n"
                   "                ///      يقومُ على صمتِ ماسحٍ لا على قياس. والقليلُ\n"
                   "                ///      الصادقُ خيرٌ من الكثيرِ المُدَّعى، ونموُّه\n"
                   "                ///      سبيلُه توسيعُ القياسِ لا توسيعُ الثقة.\n")
        out.append(f"                ///      لم يثبُت اتّفاقُ {len(unproven)} اسمٍ فلم تُحرَس.\n")
    out.append("                struct NamedRange\n                {\n"
               "                    const char *name;\n"
               "                    Range range;\n                };\n\n"
               "                inline constexpr NamedRange TABLE[] = {\n")
    for name, lo, hi in rows:
        out.append(f'                    {{"{name}", {{{lo}, {hi}}}}},\n')
    out.append(
        "                };\n\n"
        "                /// (AR) يُعيد nullptr لِما لا عقدَ له — والسكوتُ عن غيرِ\n"
        "                ///      المقيسِ أصدقُ من فرضِ رتبةٍ مُخترَعة.\n"
        "                inline const Range *lookup(const std::string &name) noexcept\n"
        "                {\n"
        "                    for (const NamedRange &e : TABLE)\n"
        "                        if (name == e.name)\n"
        "                            return &e.range;\n"
        "                    return nullptr;\n"
        "                }\n\n"
        "            } // namespace ByName\n\n")
    return "".join(out)


def render(table: dict[str, list[tuple[str, int, str, str]]],
           sot_dir: Path = SOT_DIR) -> str:
    parts = [HEADER]
    for namespace in sorted(table):
        parts.append(f"            namespace {namespace}\n            {{\n")
        for cpp_id, lo, hi, canonical in sorted(table[namespace]):
            parts.append(f"                // (AR) {canonical}\n")
            parts.append(
                f"                inline constexpr Range {cpp_id}{{{lo}, {hi}}};\n")
        parts.append(f"            }} // namespace {namespace}\n\n")
    methods = collect_type_methods(TYPE_METHODS)
    if methods:
        parts.append("            namespace TypeMethods\n            {\n")
        for target in sorted(methods):
            parts.append(f"                namespace {target}\n                {{\n")
            for cpp_id, lo, hi, canonical in sorted(methods[target]):
                parts.append(f"                    // (AR) {canonical}\n")
                parts.append(
                    f"                    inline constexpr Range {cpp_id}"
                    f"{{{lo}, {hi}}};\n")
            parts.append(f"                }} // namespace {target}\n\n")
        rows = collect_lookup(TYPE_METHODS)
        parts.append(
            "                /// (AR) جدولُ البحثِ بالهجاءِ والنوع — يُستهلَك في\n"
            "                ///      موضعِ الإرسالِ الواحدِ فيُفرَضُ العقدُ مرّةً لا\n"
            "                ///      في كلِّ فرعٍ على حِدة. و«أي» ليست فيه عن قصد.\n"
            "                struct Entry\n                {\n"
            "                    const char *target;\n"
            "                    const char *name;\n"
            "                    Range range;\n                };\n\n"
            "                inline constexpr Entry TABLE[] = {\n")
        for target, name, lo, hi in sorted(rows):
            parts.append(f'                    {{"{target}", "{name}", {{{lo}, {hi}}}}},\n')
        parts.append(
            "                };\n\n"
            "                /// (AR) يُعيد nullptr لِما لا عقدَ له — فالسكوتُ عن\n"
            "                ///      غيرِ المقيسِ أصدقُ من فرضِ رتبةٍ مُخترَعة.\n"
            "                inline const Range *lookup(const char *target,\n"
            "                                           const std::string &name) noexcept\n"
            "                {\n"
            "                    for (const Entry &e : TABLE)\n"
            "                        if (name == e.name && std::strcmp(target, e.target) == 0)\n"
            "                            return &e.range;\n"
            "                    return nullptr;\n"
            "                }\n\n")
        parts.append("            } // namespace TypeMethods\n\n")
    parts.append(render_by_name(sot_dir))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser()
    parser.add_argument("--yaml-dir", default=str(SOT_DIR))
    parser.add_argument("--out-h", default=str(OUT))
    parser.add_argument("--quiet", action="store_true")
    ns = parser.parse_args()

    yaml_dir = Path(ns.yaml_dir)
    table = collect(yaml_dir)
    out = Path(ns.out_h)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(table, yaml_dir), encoding="utf-8", newline="\n")
    if not ns.quiet:
        declared = sum(len(v) for v in table.values())
        by_name, conflicting = collect_by_name(yaml_dir)
        print(f"✓ وُلِّد {out} ({declared} مدمجًا في {len(table)} فضاءً)")
        print(f"  وجدولُ البحثِ بالاسم: {len(by_name)} اسمًا لا لبسَ في رتبتِه"
              + (("، و%d محذوفٌ للتضارب: %s" % (len(conflicting),
                                                 "، ".join(conflicting)))
                 if conflicting else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
