"""
============================================================================
(AR) مُولِّد مفردات SadUI النصّيّة (حركة/منحنيات/أحداث) من language-truth — لغة ص
(EN) Generator for SadUI string vocabularies (animations/easings/events)
----------------------------------------------------------------------------
(AR) يقرأ ملفَّ مصدرِ حقيقةٍ لمفردةٍ (enum عربيّ ↔ اسم قانونيّ) ويُنتج هيدر
     X-macro واحدًا يعرّف قائمةً تُوسَّع مرّتين في المكتبة: مرّةً لبناء جدول
     enum→اسم، ومرّةً لجدول اسم→enum. فتبقى الجهتان من مصدرٍ واحد لا تنحرفان.

     مثال الناتج:
         #define SAD_UI_ANIMATION_VOCAB(X) \
             X(FadeIn, "\\xd8\\xb8\\xd9\\x87\\xd9\\x88\\xd8\\xb1") /* ظهور */ \
             ...

     كلّ سلسلة عربيّة تُصدَّر \\xHH بايتيًّا (لا حرفيًّا) لتفادي صفحة ترميز MSVC —
     مطابقةً لبقيّة مولّدات الرسومات (gen_ui_props/gen_ui_modifiers). الاسم
     القانونيّ **بلا تشكيل**؛ المكتبة تجرّد تشكيل الوسيط قبل المطابقة
     (sad::ui::stripArabicDiacritics في text_normalize.h).

(EN) Reads one vocabulary SoT (enum id ↔ canonical Arabic name) and emits a
     single X-macro header expanded twice in the library (enum→name and
     name→enum), keeping both directions from one source. Arabic hex-escaped.
============================================================================
"""
from __future__ import annotations

import argparse
import io
import sys
import traceback
from pathlib import Path
from typing import Any

# (AR) اطبع UTF-8 دائمًا (طرفيّة Windows قد تكون cp1255 فتنهار على «→»/العربيّة).
try:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
except Exception:  # pragma: no cover
    pass

try:
    import yaml
except ImportError:
    print("[gen_ui_vocab] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# (AR) تحقّق المخطّط مشترك عبر _lib (اختياريّ — يُتخطّى بسلاسة إن غاب jsonschema).
try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    from _lib.validator import validate_no_duplicates      # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_SCHEMA = _REPO_ROOT / "language-truth" / "_schemas" / "ui_vocab.schema.json"


def _hex(s: str) -> str:
    """(AR) ترميز \\xHH بايتيّ (UTF-8)؛ يُبقي ASCII الطباعيّ حرفيًّا. / byte-wise \\xHH."""
    out = []
    for b in str(s).encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


HEADER_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from {yaml_name} — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من {yaml_name} — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_vocab.py
//
// To modify: edit {yaml_name} then rebuild (x.py gen).
// لإجراء تعديل: عدّل {yaml_name} ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) قائمة X-macro لمفردة «{desc_ar}» — تُوسَّع في المكتبة لبناء اتّجاهَي
//   التحويل (enum ↔ اسم عربيّ قانونيّ) من مصدرٍ واحد. كلّ عنصر:
//     X(<قيمة enum {enum}>, "<اسم قانونيّ بلا تشكيل، \\xHH>")
//   الأسماء بلا تشكيل؛ تُجرَّد المطابقةُ في المكتبة عبر stripArabicDiacritics.
// (EN) X-macro list for the "{desc_en}" vocabulary — expanded in the library to
//   build both conversion directions from one source. Diacritic-free canonical.
// ============================================================================

#pragma once

// (AR) استعمال: عرّف X ثمّ استدعِ {macro}(X) ثمّ ألغِ تعريف X.
// (EN) Usage: define X, invoke {macro}(X), then undef X.
#define {macro}(X) \\
{body}
"""


def emit_body(entries: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    n = len(entries)
    for i, e in enumerate(entries):
        eid = e["id"]
        canonical = e["canonical"]
        cont = "" if i == n - 1 else " \\"
        # (AR) تعليقٌ عربيّ للقراءة (بعد الـ\\ للاستمرار — آمنٌ لأنّه على نفس السطر).
        lines.append(f'    X({eid}, "{_hex(canonical)}") /* {canonical} */{cont}')
    return "\n".join(lines)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate a SadUI vocabulary X-macro header")
    p.add_argument("--yaml", type=Path, required=True, help="Path to the vocabulary SoT YAML")
    p.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA,
                   help="Path to ui_vocab.schema.json (validated if jsonschema present)")
    p.add_argument("--header", type=Path, required=True, help="Output C++ header path")
    p.add_argument("--quiet", action="store_true")
    return p.parse_args(argv)


def _validate(entries: list[dict[str, Any]], schema_path: Path, quiet: bool) -> None:
    if not _HAVE_VALIDATION or not schema_path.exists():
        if not quiet:
            print("[gen_ui_vocab] (تحقّق المخطّط متخطّى — jsonschema/المخطّط غائب)")
        return
    schema = load_schema(schema_path)
    for e in entries:
        validate_schema(e, schema)
    validate_no_duplicates(entries, key="id", context="ui_vocab id")
    validate_no_duplicates(entries, key="canonical", context="ui_vocab canonical")


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_vocab] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_vocab] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if not args.yaml.exists():
            print(f"[gen_ui_vocab] FATAL: YAML not found: {args.yaml}", file=sys.stderr)
            return 1
        data = yaml.safe_load(args.yaml.read_text(encoding="utf-8"))
        entries = data.get("entries", [])
        if not entries:
            print("[gen_ui_vocab] ERROR: no entries found", file=sys.stderr)
            return 1
        macro = data.get("macro")
        enum = data.get("enum", "")
        if not macro:
            print("[gen_ui_vocab] ERROR: 'macro' missing in SoT", file=sys.stderr)
            return 1
        _validate(entries, args.schema, args.quiet)
        content = HEADER_TEMPLATE.format(
            yaml_name=args.yaml.name,
            macro=macro,
            enum=enum,
            desc_ar=data.get("description_ar", macro),
            desc_en=data.get("description_en", macro),
            body=emit_body(entries),
        )
        write_if_changed(args.header, content, args.quiet)
        if not args.quiet:
            print(f"[gen_ui_vocab] {len(entries)} entries → {args.header}")
        return 0
    except Exception as exc:
        print(f"[gen_ui_vocab] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
