"""
============================================================================
(AR) مُولِّد prop_keys.h من language-truth/ui_props.yaml — لغة ص
(EN) Generator for sad_ui/prop_keys.h from language-truth/ui_props.yaml
----------------------------------------------------------------------------
(AR) يقرأ مصدر الحقيقة لمفاتيح خصائص عناصر الواجهة ويُنتج الهيدر:
       namespace sad::ui::props { inline constexpr const char* ID = "\\x.."; }
     كلّ سلسلة عربيّة تُصدَّر بترميز \\xHH سِتّ عشريّ (لا حرفيًّا) لتفادي مشكلات
     صفحة ترميز MSVC في المصدر — مطابقةً للنهج المُثبَت في الهيدر اليدويّ السابق.

     الطبقيّة محفوظة: الهيدر المولَّد مُلتزَمٌ وذاتيّ الاكتفاء، فتبقى sad_graphics
     مكتبة طرفيّة لا تعتمد shared/builtins (التوليد وقت البناء لا وقت التشغيل).

(EN) Reads the SoT for UI property keys and emits the header with each Arabic
     string hex-escaped (\\xHH) — matching the proven hand-written header — so
     MSVC source-codepage issues never arise. The generated header is committed
     and self-contained, so sad_graphics stays a leaf library.

الاستخدام / Usage:
    python gen_ui_props.py \\
        --yaml   language-truth/ui_props.yaml \\
        --header features/graphics/core/include/sad_ui/prop_keys.h \\
        --quiet
============================================================================
"""

from __future__ import annotations

import argparse
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("[gen_ui_props] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# (AR) تحقّق المخطّط مشترك عبر _lib (اختياريّ — يُتخطّى بسلاسة إن غاب jsonschema).
try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    from _lib.validator import validate_no_duplicates      # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_YAML = _REPO_ROOT / "language-truth" / "ui_props.yaml"
_DEFAULT_SCHEMA = _REPO_ROOT / "language-truth" / "_schemas" / "ui_props.schema.json"
_DEFAULT_HEADER = _REPO_ROOT / "features" / "graphics" / "core" / "include" / "sad_ui" / "prop_keys.h"


def _hex_escape(s: str) -> str:
    """
    @brief (AR) يحوّل سلسلة إلى ترميز \\xHH بايتًا بايتًا (UTF-8).
    @brief (EN) Encode a string as byte-wise \\xHH escapes (UTF-8).
    (AR) يُطبَّق على غير-ASCII فقط؛ يُبقي ASCII الطباعيّ حرفيًّا (مثل "text").
    """
    out = []
    for b in s.encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


HEADER_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from language-truth/ui_props.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_props.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_props.py
//
// To modify: edit language-truth/ui_props.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_props.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأسماء مفاتيح خصائص عناصر الواجهة (IR keys).
//   يستهلكه ثلاثةُ منتِجين/مستهلِكين كي لا تنحرف المفاتيح بينهم انحرافًا صامتًا:
//     1. مصنع العناصر في المفسّر (widget_builtins.cpp) — يَكتب المفتاح.
//     2. مُرسِّم سطح المكتب (backends/desktop/renderer*.cpp) — يقرؤه.
//     3. مُصرِّفات الويب/أندرويد/iOS/macOS — تقرؤه.
//   القاعدة: ممنوع سلاسلُ مفاتيحَ حرفيّةٌ مباشرةٌ في أيٍّ من هؤلاء؛ استعمل هذه
//   الثوابت حصرًا (قاعدة المشروع «لا literals منطقيّة مباشرة»).
//
// (EN) Single source of truth for UI IR property-key names, shared by the
//   interpreter widget factory, the desktop renderer, and every codegen backend
//   so the keys can never silently diverge.
// ============================================================================

#pragma once

namespace sad
{{
    namespace ui
    {{
        namespace props
        {{
{keys_section}

            // ================================================================
            // (AR) مفاتيح **عدديّة** (value_type: عدد في ui_props.yaml).
            //   لماذا: المصرّف يختار أوپكود SET_PROP بحسب نوع القيمة وقت الترجمة،
            //   لكنّ قيمًا كثيرة نوعها يتقرّر زمنَ التشغيل (نتيجة `/` مثلًا نوعها
            //   Any لأنّ صحيح/صحيح قد يكون صحيحًا أو عشريًّا). كان المجهولُ يسقط
            //   إلى SET_PROP_STR فتُخزَّن «نصف_قطر» **نصًّا** ويقرؤها المُرسِّم صفرًا
            //   (مقيس بالبكسل: `نصف_قطر(22)` قرصٌ، و`نصف_قطر(قطر / 2)` مربّع).
            //   بهذا الجدول يحسم المصرّفُ بالمفتاح لا بالقيمة، ومن SoT لا بسلسلة
            //   حرفيّة — التزامًا بقاعدة «لا literals منطقيّة مباشرة».
            // (EN) Numeric keys (value_type: عدد). The compiler picks the SET_PROP
            //   opcode from the compile-time value type, but some values are typed
            //   at runtime (`/` yields Any). Unknown fell back to SET_PROP_STR, so a
            //   numeric key was stored as text and read back as 0 by the renderer.
            //   This table lets the compiler decide by key, sourced from the SoT.
            // ================================================================
            inline bool isNumericPropKey(const char *name)
            {{
                if (!name)
                    return false;
                static const char *const NUMERIC_KEYS[] = {{
{numeric_keys_section}
                }};
                for (const char *k : NUMERIC_KEYS)
                {{
                    const char *a = k;
                    const char *b = name;
                    while (*a && *a == *b)
                    {{
                        ++a;
                        ++b;
                    }}
                    if (*a == '\\0' && *b == '\\0')
                        return true;
                }}
                return false;
            }}
            // ================================================================
            // (AR) X(ID) — جردُ **كلِّ** مفاتيحِ الخصائصِ القانونيّة.
            //   يستهلكه المفسّرُ للتحقّقِ من اسمِ المعدّلِ قبلَ كتابتِه: كان فضاءُ
            //   المعدّلاتِ مفتوحًا بلا تحقّق، فخطأٌ إملائيٌّ («نصف_قطرر») يُكتَب
            //   خاصّيّةً لا قارئَ لها ويُبتلَع صامتًا — يظهر أثرُه بكسلًا مفقودًا
            //   لا رسالةَ خطأ. الجردُ من مصدرِ الحقيقةِ فلا قائمةَ ثانيةٌ تنحرف.
            // (EN) X(ID) — inventory of every canonical property key; the
            //   interpreter validates modifier names against it, so a typo warns
            //   instead of being silently written as an unread property.
            // ================================================================
#define SAD_UI_PROP_KEY_LIST(X) \\
{key_list}

#define SAD_UI_PROP_KEY_COUNT {key_count}
        }} // namespace props

        // ====================================================================
        // (AR) **قِيَم** الخصائص القانونيّة (لا أسماؤها): «وسط»، «يمين»، «صحيح»…
        //   كانت مكتوبةً حرفيًّا في كلّ مُرسِّمٍ ومولّدٍ على حِدة، فاختلفت القوائم
        //   بينها صامتةً (مُرسِّمُ سطحِ المكتبِ كان يقارن بـ"يمين" الحرفيّةِ بينما
        //   المشترَكُ يقارن بثابتٍ مسمًّى). رفعُها إلى مصدرِ الحقيقةِ يجعل
        //   المقارنةَ واحدةً في كلِّ مسار.
        // (EN) Canonical property *values* (not key names), generated from SoT so
        //   every renderer and code generator compares against one list.
        // ====================================================================
        namespace propval
        {{
{values_section}
        }} // namespace propval
    }} // namespace ui
}} // namespace sad
"""


def emit_keys(keys: list[dict[str, Any]]) -> str:
    """
    @brief (AR) يُولِّد أسطر الثوابت لكلّ مفتاح خاصّيّة.
    @brief (EN) Emit the constant lines for each property key.
    """
    lines: list[str] = []
    for k in keys:
        cid = k["id"]
        canonical = k["canonical"]
        desc_ar = k.get("description_ar", canonical)
        escaped = _hex_escape(str(canonical))
        lines.append(f'            // (AR) {desc_ar} — «{canonical}».')
        lines.append(f'            inline constexpr const char *{cid} = "{escaped}";')
    return "\n".join(lines)


# (AR) قيمة value_type التي تعني «عدد» في ui_props.yaml (مصدر الحقيقة).
_NUMERIC_VALUE_TYPE = "عدد"  # عدد


def emit_numeric_keys(keys: list[dict[str, Any]]) -> str:
    """
    @brief (AR) يُولِّد جدول المفاتيح العدديّة (value_type: عدد) لدالّة isNumericPropKey.
    @brief (EN) Emit the numeric-key table (value_type: عدد) for isNumericPropKey.
    """
    lines: list[str] = []
    for k in keys:
        if str(k.get("value_type", "")).strip() != _NUMERIC_VALUE_TYPE:
            continue
        lines.append(f'                    {k["id"]},  // {k["canonical"]}')
    return "\n".join(lines)


def emit_key_list(keys: list[dict[str, Any]]) -> str:
    """@brief (AR) جردُ كلِّ معرّفاتِ المفاتيح لقائمةِ X-macro."""
    lines = []
    for k in keys:
        lines.append('    X(' + k["id"] + ') /* ' + str(k["canonical"]) + ' */ \\')
    if lines:
        lines[-1] = lines[-1].rstrip(' \\')
    return chr(10).join(lines)


def emit_values(values: list[dict[str, Any]]) -> str:
    """
    @brief (AR) يُولِّد ثوابت **قِيَم** الخصائص القانونيّة (namespace propval).
    @brief (EN) Emit canonical property-value constants (namespace propval).
    """
    lines: list[str] = []
    for v in values:
        vid = v["id"]
        literal = str(v["value"])
        desc_ar = v.get("description_ar", literal)
        lines.append(f'            // (AR) {desc_ar} — «{literal}».')
        lines.append(f'            inline constexpr const char *{vid} = "{_hex_escape(literal)}";')
    return "\n".join(lines)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate prop_keys.h from ui_props.yaml")
    p.add_argument("--yaml", type=Path, default=_DEFAULT_YAML,
                   help="Path to language-truth/ui_props.yaml")
    p.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA,
                   help="Path to ui_props.schema.json (validated if jsonschema present)")
    p.add_argument("--header", type=Path, default=_DEFAULT_HEADER,
                   help="Output C++ header path")
    p.add_argument("--quiet", action="store_true", help="Suppress info messages")
    return p.parse_args(argv)


def _validate(keys: list[dict[str, Any]], schema_path: Path, quiet: bool) -> None:
    """(AR) يتحقّق من كلّ مفتاح ضدّ المخطّط + تفرّد id/canonical (إن توفّر jsonschema)."""
    if not _HAVE_VALIDATION or not schema_path.exists():
        if not quiet:
            print("[gen_ui_props] (تحقّق المخطّط متخطّى — jsonschema/المخطّط غائب)")
        return
    schema = load_schema(schema_path)
    for k in keys:
        validate_schema(k, schema)
    validate_no_duplicates(keys, key="id", context="ui_props.yaml id")
    validate_no_duplicates(keys, key="canonical", context="ui_props.yaml canonical")


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    """
    @brief (AR) يكتب الملف فقط إذا تغيَّر المحتوى (LF مفروض عبر المنصّات).
    @brief (EN) Write only if changed; force LF to avoid false drift on Windows.
    """
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_props] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_props] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if not args.yaml.exists():
            print(f"[gen_ui_props] FATAL: YAML not found: {args.yaml}", file=sys.stderr)
            return 1
        with open(args.yaml, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        keys = data.get("keys", [])
        if not keys:
            print("[gen_ui_props] ERROR: no keys found", file=sys.stderr)
            return 1
        _validate(keys, args.schema, args.quiet)
        values = data.get("values", [])
        content = HEADER_TEMPLATE.format(keys_section=emit_keys(keys),
                                         numeric_keys_section=emit_numeric_keys(keys),
                                         values_section=emit_values(values),
                                         key_list=emit_key_list(keys),
                                         key_count=len(keys))
        write_if_changed(args.header, content, args.quiet)
        if not args.quiet:
            print(f"[gen_ui_props] {len(keys)} property keys, "
                  f"{len(values)} property values -> {args.header}")
        return 0
    except Exception as exc:
        print(f"[gen_ui_props] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
