"""
============================================================================
(AR) مُولِّد جردِ الكلماتِ المحجوزةِ للمُلوِّنِ النحويِّ في مكتبةِ الرسومات.
(EN) Generator for the graphics-library syntax-highlighter keyword inventory.
----------------------------------------------------------------------------
(AR) لماذا مُولَّدٌ وليس مكتوبًا بيد:

     كان المُلوِّنُ يحمل ستّةَ جداولَ مكتوبةٍ يدويًّا (٧٢ سلسلةً عربيّةً حرفيّة)،
     فانحرفت عن `language-truth/keywords.yaml` انحرافًا **مقيسًا**: ٣١ كلمةً
     محجوزةً في مصدرِ الحقيقةِ لا يلوّنها المُلوِّن (أجّل، أنتج، حالة، فضاء،
     قالب، ماكرو، طبيعي…). والتعليقُ في رأسِ الجدولِ كان يقول «(40)» — عددٌ
     مثبَّتٌ بيدٍ صار كاذبًا. أيْ أنّ عقدةَ «كتلة_كود» تعرض كودَ ص بتلوينٍ
     ناقصٍ صامتًا: لا خطأَ بناءٍ ولا تشغيل، فقط كلماتٌ بلونِ النصِّ العاديّ.

     ولماذا رأسٌ خاصٌّ بالرسومات ولا نستهلك `shared/lexer/generated/
     keywords_generated.h` مباشرةً: ذاك الرأسُ يضمّ `token.h` ويعتمد دالّةً
     (`allEntries()`) تحتاج ربطًا — واستهلاكُه يجعل `sad_graphics` تعتمد طبقةَ
     المحلّل، وهي **مكتبةٌ طرفيّةٌ** بحكمِ تصميمِ المشروع. فالحلُّ نفسُ حلِّ
     `prop_keys.h`: مصدرُ حقيقةٍ واحدٌ ومخرَجانِ مولَّدان، كلٌّ في طبقتِه.

(EN) The highlighter's six hand-written tables had drifted from keywords.yaml
     by 31 measured keywords. We generate a self-contained header for the
     graphics leaf library instead of consuming the lexer's header (which pulls
     token.h and needs linking) — same pattern as prop_keys.h.

الاستخدام / Usage:
    python gen_ui_syntax_keywords.py \\
        --yaml   language-truth/keywords.yaml \\
        --header features/graphics/core/include/sad_ui/generated/syntax_keywords_generated.h
============================================================================
"""

from __future__ import annotations

import argparse
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("[gen_ui_syntax_keywords] FATAL: pyyaml not installed.", file=sys.stderr)
    sys.exit(1)

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_YAML = _REPO_ROOT / "language-truth" / "keywords.yaml"
_DEFAULT_BUILTINS = _REPO_ROOT / "language-truth" / "builtins" / "core.yaml"
_DEFAULT_HEADER = (
    _REPO_ROOT / "features" / "graphics" / "core" / "include" / "sad_ui" / "generated"
    / "syntax_keywords_generated.h"
)

# (AR) تصنيفُ مصدرِ الحقيقة ⇒ اسمُ قائمةِ الماكرو في الرأسِ المولَّد.
#      «reserved» و«operators» كلاهما يُلوَّن كلمةً محجوزةً في المُلوِّن الحاليّ.
_CATEGORY_LISTS = {
    "reserved": "SAD_UI_SYNTAX_KEYWORD_LIST",
    "operators": "SAD_UI_SYNTAX_LOGICAL_OP_LIST",
    "contextual": "SAD_UI_SYNTAX_CONTEXT_KEYWORD_LIST",
    "builtin_types": "SAD_UI_SYNTAX_TYPE_NAME_LIST",
}

# (AR) «صحيح/خطأ/لاشيء» تسكن تصنيفَ `reserved` في مصدرِ الحقيقة (وهي محجوزةٌ
#   فعلًا)، لكنّ المُلوِّنَ يمنحُها لونَينِ مستقلَّينِ عن لونِ الكلمةِ المحجوزة.
#   وترتيبُ الفحصِ في `classifyIdent` يبدأ بالكلماتِ المحجوزة، فلو تُركت فيها
#   لعادت `Keyword` ولَما بلغت `Boolean`/`NullLiteral` أبدًا — انحدارٌ صامتٌ في
#   اللون. فنفصلها هنا بـ`tokenType` لا بالاسم: مصدرُ الحقيقةِ يُصنّفها أصلًا.
_LITERAL_TOKEN_TYPES = {
    "LITERAL_TRUE": "SAD_UI_SYNTAX_BOOLEAN_LIST",
    "LITERAL_FALSE": "SAD_UI_SYNTAX_BOOLEAN_LIST",
    "LITERAL_NULL": "SAD_UI_SYNTAX_NULL_LIST",
}

# (AR) الدوالُّ المدمجةُ العامّة (بلا `استورد`) — `core.yaml` وحدَه: اطبع،
#   اطبع_سطر، اقرأ، طول، نوع… وهي ما يعدّه المُلوِّنُ «مدمجًا». ما وراءَها
#   (مصفوفات/نواة/واجهة) يلزمه استيرادٌ أو فضاءُ اسمٍ فليس مدمجًا عامًّا.
_BUILTIN_LIST = "SAD_UI_SYNTAX_BUILTIN_LIST"


def _hex(text: str) -> str:
    """(AR) ترميز \\xHH بايتيّ — صفحةُ ترميز MSVC تكسر العربيّةَ الحرفيّة."""
    out: list[str] = []
    prev_escaped = False
    for byte in str(text).encode("utf-8"):
        if 0x20 <= byte < 0x7F and chr(byte) not in ('"', "\\"):
            if prev_escaped and chr(byte) in "0123456789abcdefABCDEF":
                out.append('""')
            out.append(chr(byte))
            prev_escaped = False
        else:
            out.append(f"\\x{byte:02x}")
            prev_escaped = True
    return "".join(out)


HEADER_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from language-truth/keywords.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/keywords.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_syntax_keywords.py
//
// To modify: edit language-truth/keywords.yaml then rebuild (x.py gen).
// ============================================================================
//
// (AR) جردُ مفرداتِ لغةِ ص كما يراها المُلوِّنُ النحويُّ في مكتبةِ الرسومات
//   (عقدةُ «كتلة_كود»). كانت هذه الجداولُ مكتوبةً بيدٍ فانحرفت عن مصدرِ
//   الحقيقةِ بـ٣١ كلمةً محجوزةً — انحرافٌ صامتٌ لا يُنتج خطأً، فقط كلماتٌ
//   تظهر بلونِ النصِّ العاديّ.
//
//   رأسٌ **ذاتيُّ الاكتفاء** عمدًا: `sad_graphics` مكتبةٌ طرفيّةٌ لا تعتمد
//   طبقةَ المحلّل، فلا نستهلك رأسَ المعجمِ هناك (يضمّ token.h ويحتاج ربطًا).
//   مصدرُ حقيقةٍ واحدٌ ومخرَجانِ مولَّدان — نظيرُ prop_keys.h تمامًا.
// (EN) Sad-language vocabulary as seen by the graphics-library syntax
//   highlighter. Self-contained by design: the graphics leaf library must not
//   depend on the lexer layer. One SoT, two generated outputs.
// ============================================================================

#pragma once

// (AR) X("الكلمة") — كلماتٌ محجوزةٌ تُلوَّن لونَ الكلمةِ المحجوزة.
#define {reserved_macro}(X) \\
{reserved}

#define {reserved_macro}_COUNT {reserved_count}

// (AR) X("الكلمة") — عوامل منطقيّة (و/أو/ليس) تُلوَّن لونَ الكلمةِ المحجوزة.
#define {operators_macro}(X) \\
{operators}

#define {operators_macro}_COUNT {operators_count}

// (AR) X("الكلمة") — كلماتٌ سياقيّةٌ (غير_متزامن، لامدا…) بلونٍ مستقلّ.
#define {contextual_macro}(X) \\
{contextual}

#define {contextual_macro}_COUNT {contextual_count}

// (AR) X("الكلمة") — أسماءُ الأنواعِ المدمَجة (رقم، نص، عشري…).
#define {types_macro}(X) \\
{types}

#define {types_macro}_COUNT {types_count}

// (AR) X("الكلمة") — القيمُ المنطقيّة. مفصولةٌ عن الكلماتِ المحجوزةِ **بـtokenType**
//   لا بالاسم، لأنّ فحصَ المُلوِّنِ يبدأ بالمحجوزةِ فتبتلعُها لو بقيت فيها.
#define {booleans_macro}(X) \\
{booleans}

#define {booleans_macro}_COUNT {booleans_count}

// (AR) X("الكلمة") — قيمةُ العدم.
#define {nulls_macro}(X) \\
{nulls}

#define {nulls_macro}_COUNT {nulls_count}

// (AR) X("الاسم") — الدوالُّ المدمجةُ العامّة (بلا `استورد`) من builtins/core.yaml.
#define {builtins_macro}(X) \\
{builtins}

#define {builtins_macro}_COUNT {builtins_count}
"""


def _words(category: dict[str, Any]) -> list[str]:
    """(AR) كلماتُ تصنيفٍ واحد، بلا تكرار وبترتيبِ مصدرِ الحقيقة."""
    seen: list[str] = []
    for entry in category.get("keywords", []) or []:
        word = str(entry.get("word", "")).strip()
        if word and word not in seen:
            seen.append(word)
    return seen


def _split_literals(category: dict[str, Any]) -> tuple[list[str], list[str], list[str]]:
    """(AR) يفصلُ المحجوزةَ عن القيمِ المنطقيّةِ والعدمِ بحقلِ `tokenType`."""
    reserved: list[str] = []
    booleans: list[str] = []
    nulls: list[str] = []
    for entry in category.get("keywords", []) or []:
        word = str(entry.get("word", "")).strip()
        if not word:
            continue
        target = _LITERAL_TOKEN_TYPES.get(str(entry.get("tokenType", "")))
        bucket = (
            booleans if target == "SAD_UI_SYNTAX_BOOLEAN_LIST"
            else nulls if target == "SAD_UI_SYNTAX_NULL_LIST"
            else reserved
        )
        if word not in bucket:
            bucket.append(word)
    return reserved, booleans, nulls


def _global_builtins(path: Path) -> list[str]:
    """(AR) أسماءُ الدوالِّ المدمجةِ التي لا تحتاج `استورد` — بترتيبِ المصدر."""
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    entries = data if isinstance(data, list) else (data.get("functions") or [])
    names: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict) or entry.get("require_import"):
            continue
        name = str(entry.get("canonical", "")).strip()
        if name and name not in names:
            names.append(name)
    return names


def _emit(words: list[str]) -> str:
    lines = [f'    X("{_hex(w)}") /* {w} */ \\' for w in words]
    if lines:
        lines[-1] = lines[-1].rstrip(" \\")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_syntax_keywords] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_syntax_keywords] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the highlighter keyword header")
    parser.add_argument("--yaml", type=Path, default=_DEFAULT_YAML)
    parser.add_argument("--builtins", type=Path, default=_DEFAULT_BUILTINS)
    parser.add_argument("--header", type=Path, default=_DEFAULT_HEADER)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)
    try:
        data = yaml.safe_load(args.yaml.read_text(encoding="utf-8")) or {}
        categories = data.get("categories", {})
        buckets = {name: _words(categories.get(name, {}) or {}) for name in _CATEGORY_LISTS}
        buckets["reserved"], booleans, nulls = _split_literals(categories.get("reserved", {}) or {})
        builtins = _global_builtins(args.builtins)
        missing = [name for name, words in buckets.items() if not words]
        if not booleans or not nulls or not builtins:
            missing.append("literals/builtins")
        if missing:
            print(f"[gen_ui_syntax_keywords] ERROR: empty categories: {missing}", file=sys.stderr)
            return 1

        content = HEADER_TEMPLATE.format(
            reserved_macro=_CATEGORY_LISTS["reserved"],
            reserved=_emit(buckets["reserved"]),
            reserved_count=len(buckets["reserved"]),
            operators_macro=_CATEGORY_LISTS["operators"],
            operators=_emit(buckets["operators"]),
            operators_count=len(buckets["operators"]),
            contextual_macro=_CATEGORY_LISTS["contextual"],
            contextual=_emit(buckets["contextual"]),
            contextual_count=len(buckets["contextual"]),
            types_macro=_CATEGORY_LISTS["builtin_types"],
            types=_emit(buckets["builtin_types"]),
            types_count=len(buckets["builtin_types"]),
            booleans_macro=_LITERAL_TOKEN_TYPES["LITERAL_TRUE"],
            booleans=_emit(booleans),
            booleans_count=len(booleans),
            nulls_macro=_LITERAL_TOKEN_TYPES["LITERAL_NULL"],
            nulls=_emit(nulls),
            nulls_count=len(nulls),
            builtins_macro=_BUILTIN_LIST,
            builtins=_emit(builtins),
            builtins_count=len(builtins),
        )
        write_if_changed(args.header, content, args.quiet)
        if not args.quiet:
            total = sum(len(w) for w in buckets.values()) + len(booleans) + len(nulls) + len(builtins)
            print(f"[gen_ui_syntax_keywords] {total} keywords -> {args.header}")
        return 0
    except Exception as exc:  # pragma: no cover
        print(f"[gen_ui_syntax_keywords] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
