"""
============================================================================
(AR) مُولِّد ui_modifiers.h من language-truth/ui_modifiers.yaml — لغة ص
(EN) Generator for sad_ui/ui_modifiers.h from language-truth/ui_modifiers.yaml
----------------------------------------------------------------------------
(AR) يقرأ مصدر الحقيقة لطرق (معدّلات) عناصر الواجهة ويُنتج لكلّ معدّل:
       - ثابتًا قانونيًّا  inline constexpr const char* ID = "…";
       - قالب تطابق        inline bool is<Id>(std::string_view m) { … }
     يطابق المعدّلُ اسمَه القانونيّ حصرًا (exact) أو كبادئة (prefix). سياسة
     «الأسماء القانونيّة فقط، لا بدائل» — المخطّط يمنع حقل aliases.
     كلّ سلسلة عربيّة تُصدَّر \\xHH (لا حرفيًّا) لتفادي صفحة ترميز MSVC.
     يستهلكه موزّع المعدّلات في المفسّر (ui_widget_method_call.cpp) والمترجم،
     فتزول السلاسل الحرفيّة المباشرة (قاعدة «لا literals منطقيّة») ويصير المصدرُ SoT.

(EN) Emits, per modifier, a canonical constant and an `is<Id>()` predicate that
     matches the canonical name (exact) or as a prefix. Canonical-only policy —
     no aliases (schema forbids them). Arabic strings are hex-escaped. Consumed
     by the modifier dispatcher in both engines.
============================================================================
"""
from __future__ import annotations

import argparse
import re
import sys
import traceback
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("[gen_ui_modifiers] FATAL: pyyaml not installed. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# (AR) تحقّق المخطّط مشترك عبر _lib (اختياريّ — يُتخطّى بسلاسة إن غاب jsonschema).
try:
    from _lib.loader import load_schema, validate_schema  # type: ignore
    from _lib.validator import validate_no_duplicates      # type: ignore
    _HAVE_VALIDATION = True
except Exception:  # pragma: no cover
    _HAVE_VALIDATION = False

_THIS_DIR = Path(__file__).parent
_REPO_ROOT = _THIS_DIR.parents[1]
_DEFAULT_YAML = _REPO_ROOT / "language-truth" / "ui_modifiers.yaml"
_DEFAULT_SCHEMA = _REPO_ROOT / "language-truth" / "_schemas" / "ui_modifiers.schema.json"
_DEFAULT_HEADER = _REPO_ROOT / "features" / "graphics" / "core" / "include" / "sad_ui" / "ui_modifiers.h"


def _hex(s: str) -> str:
    """(AR) ترميز \\xHH بايتيّ (UTF-8)؛ يُبقي ASCII الطباعيّ حرفيًّا. / byte-wise \\xHH."""
    out = []
    for b in str(s).encode("utf-8"):
        if 0x20 <= b < 0x7F and chr(b) not in ('"', "\\"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def _pascal(cid: str) -> str:
    """CHILD → Child ، AUTO_REVERSE → AutoReverse."""
    return "".join(p.capitalize() for p in cid.split("_"))


HEADER_TEMPLATE = """\
// ============================================================================
// AUTO-GENERATED from language-truth/ui_modifiers.yaml — DO NOT EDIT MANUALLY
// (AR) مُولَّد تلقائياً من language-truth/ui_modifiers.yaml — لا تعدّله يدوياً
// (EN) Auto-generated by scripts/codegen/gen_ui_modifiers.py
//
// To modify: edit language-truth/ui_modifiers.yaml then rebuild (x.py gen).
// لإجراء تعديل: عدّل language-truth/ui_modifiers.yaml ثم أعد التوليد (x.py gen).
// ============================================================================
//
// (AR) مصدر الحقيقة الوحيد لأسماء طرق (معدّلات) عناصر الواجهة الانسيابيّة.
//   يستهلكه موزّع المعدّلات في **المحرّكين معًا** (المفسّر ui_widget_method_call.cpp
//   والمترجم call_method_dispatch.cpp) مباشرةً عبر دوالّ is<Id> — فلا اسمَ معدّلٍ
//   حرفيّ في أيٍّ منهما (قاعدة «لا literals منطقيّة مباشرة»).
//   سياسة: الأسماء القانونيّة فقط، لا بدائل (المخطّط يمنع aliases).
// (EN) SoT for SadUI fluent modifier names, consumed DIRECTLY by BOTH engines
//   (interpreter + compiler) via the is<Id> predicates — no literal modifier name
//   in either. Canonical-only policy: no aliases (schema forbids them).
// ============================================================================

#pragma once

#include <string_view>

namespace sad
{{
    namespace ui
    {{
        namespace mods
        {{
{body}
        }} // namespace mods
    }} // namespace ui
}} // namespace sad
"""


def emit_body(modifiers: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    for m in modifiers:
        cid = m["id"]
        canonical = m["canonical"]
        match = m.get("match", "exact")
        desc = m.get("description_ar", canonical)
        # الثابت القانونيّ (لا بدائل — سياسة الأسماء القانونيّة فقط)
        lines.append(f'            // (AR) {desc} — «{canonical}».')
        lines.append(f'            inline constexpr const char *{cid} = "{_hex(canonical)}";')
        # قالب التطابق is<Pascal> على الاسم القانونيّ حصرًا
        fn = f"is{_pascal(cid)}"
        if match == "prefix":
            cond = f'm.rfind("{_hex(canonical)}", 0) == 0'
            lines.append(f'            // (AR) يطابق أيّ اسمٍ يبدأ بالبادئة (عائلة {canonical}*).')
        else:
            cond = f'm == "{_hex(canonical)}"'
        lines.append(f"            inline bool {fn}(std::string_view m) {{ return {cond}; }}")
        lines.append("")
    return "\n".join(lines).rstrip("\n")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate ui_modifiers.h from ui_modifiers.yaml")
    p.add_argument("--yaml", type=Path, default=_DEFAULT_YAML)
    p.add_argument("--schema", type=Path, default=_DEFAULT_SCHEMA,
                   help="Path to ui_modifiers.schema.json (validated if jsonschema present)")
    p.add_argument("--header", type=Path, default=_DEFAULT_HEADER)
    p.add_argument("--quiet", action="store_true")
    return p.parse_args(argv)


def _validate(modifiers: list[dict[str, Any]], schema_path: Path, quiet: bool) -> None:
    """(AR) يتحقّق من كلّ معدّل ضدّ المخطّط + تفرّد id/canonical (إن توفّر jsonschema)."""
    if not _HAVE_VALIDATION or not schema_path.exists():
        if not quiet:
            print("[gen_ui_modifiers] (تحقّق المخطّط متخطّى — jsonschema/المخطّط غائب)")
        return
    schema = load_schema(schema_path)
    for mod in modifiers:
        validate_schema(mod, schema)
    validate_no_duplicates(modifiers, key="id", context="ui_modifiers.yaml id")
    validate_no_duplicates(modifiers, key="canonical", context="ui_modifiers.yaml canonical")


def write_if_changed(path: Path, content: str, quiet: bool) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        if not quiet:
            print(f"[gen_ui_modifiers] No changes: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    if not quiet:
        print(f"[gen_ui_modifiers] Written: {path}")


def run(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        if not args.yaml.exists():
            print(f"[gen_ui_modifiers] FATAL: YAML not found: {args.yaml}", file=sys.stderr)
            return 1
        data = yaml.safe_load(open(args.yaml, encoding="utf-8"))
        modifiers = data.get("modifiers", [])
        if not modifiers:
            print("[gen_ui_modifiers] ERROR: no modifiers found", file=sys.stderr)
            return 1
        _validate(modifiers, args.schema, args.quiet)
        content = HEADER_TEMPLATE.format(body=emit_body(modifiers))
        write_if_changed(args.header, content, args.quiet)
        if not args.quiet:
            print(f"[gen_ui_modifiers] {len(modifiers)} modifiers → {args.header}")
        return 0
    except Exception as exc:
        print(f"[gen_ui_modifiers] FATAL: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(run())
